### ISSUE TITLE
dot `.` changes behaviour inside [ ] and only matches dot-literal

### ISSUE THREAD

**Issue by colin-kiegel** [rust-lang/regex#100]
When a dot `.` is moved inside of `[ ]` the dot changes it's behaviour and only matches dot-literals instead of anything except new lines. `(?:\n|.)` should be equivalent to `[\n.]` but it is not, because test B works fine, while test C fails.

Motivation: We don't have behaviour-modifiers in this library (like for example `PCRE_DOTALL`: making the dot `.` match new lines too). Therefore it is sometimes necessary to use workarounds. `[.\n]` for example should be a drop-in replacement for `.` + `PCRE_DOTALL`.

However it does not work (see test C ... FAILED below).

```rust
use regex::Regex;

#[test]
fn A() {
    let re = Regex::new(r"^[\n].*$").unwrap();
    assert!(re.is_match("\n.,"));
}

#[test]
fn B() {
    let re = Regex::new(r"^(?:\n|.)*$").unwrap();
    assert!(re.is_match("\n.,"));
}

#[test]
fn C() {
    let re = Regex::new(r"^[\n.]*$").unwrap();
    assert!(re.is_match("\n.,"));
}
```

------------------
running 3 tests
test A ... ok
test B ... ok
test C ... FAILED

failures:

---- C stdout ----
	thread 'C' panicked at 'assertion failed: re.is_match("\n.,")', file.rs:123

**Comment by colin-kiegel** [comment]
I am using rust 1.1.0 stable and these are my regex versions:

[[package]]
name = "regex"
version = "0.1.33"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "regex-syntax 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "regex-syntax"
version = "0.1.2"
source = "registry+https://github.com/rust-lang/crates.io-index"

**Comment by BurntSushi** [comment]
> We don't have behaviour-modifiers in this library

That's not true. :-) You can use `(?s).` to get "dot all" behavior. There are other flags too, such as case insensitive matching. See the docs: http://doc.rust-lang.org/regex/regex/index.html#grouping-and-flags

I'm happy to change this to reflect common behavior among other regex engines. (I'm not sure what that is yet.)

**Comment by colin-kiegel** [comment]
Thanks for the tip!

And I am sorry - I just checked other engines also change the dot-behaviour inside of `[ ]` - kind of unbelivable to me .. It seems the engine is working fine and regexes are just weird here.

**Comment by BurntSushi** [comment]
It's not completely crazy. At least the following characters have a different meaning inside `[` and `]` when compared to outside: `-`, `(`, `)`, `*`, `+`, `?`. On the other hand, none of those characters make much sense with their original meaning when used in `[` and `]`.

Incidentally, other forms of classes such as `\pL` or `[:upper:]` retain their meaning inside `[` and `]`. It seems like `.` should too.

But alas, I think we should be consistent with other engines on this point.
