### ISSUE TITLE
Array out of bound Bug in regex_syntax::hir::LookSet::read_repr

### ISSUE THREAD

**Issue by XizheYin-NJU** [rust-lang/regex#1008]
#### What version of regex are you using?
```
regex-syntax = "=0.7.2"
```

#### Describe the bug at a high level.

When calling regex_syntax::hir::LookSet::read_repr, if the length of the slice is less than 2, the program crashes. It is necessary to add an array bounds check to prevent this issue.

#### What are the steps to reproduce the behavior?

source code:
```rust
fn main() {
    //println!("_param1 = {:?}", _param1);
    let _local1 = regex_syntax::hir::LookSet::read_repr(&[0]);
}
```

#### What is the actual behavior?

it crashed.
```
thread 'main' panicked at 'range end index 2 out of range for slice of length 1', /home/yxz/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/regex-syntax-0.7.2/src/hir/mod.rs:2748:39
```

**Comment by BurntSushi** [comment]
This is behaving as documented: https://docs.rs/regex-syntax/latest/regex_syntax/hir/struct.LookSet.html#panics
