### ISSUE TITLE
[:word:] character class does not match underscore

### ISSUE THREAD

**Issue by seifertm** [rust-lang/regex#101]
The ASCII character class `[:word:]` does not match the underscore char `_`.

The following assertion fails with regex v0.1.41:

    extern crate regex;
    
    fn main() {
        let re = regex::Regex::new(r"[:word:]").unwrap();
        assert!(re.is_match("_"));
    }

**Comment by huonw** [comment]
Is there a reason it should match? E.g. what do other regex engines do?

**Comment by eseifert** [comment]
It's what documentation says:
```
[:word:]     word characters ([0-9A-Za-z_])
```
As far as I can tell the underscore char is also matched by Perl, Python, PHP, and JavaScript.

**Comment by BurntSushi** [comment]
Nice find. I've pushed the fix out to crates.io in `regex-syntax 0.2.1`.

**Comment by seifertm** [comment]
Great, thanks!
