### ISSUE TITLE
README std::cell::OnceCell usage example

### ISSUE THREAD

**Issue by nyurik** [rust-lang/regex#1034]
Rust v1.70 introduced a new [std::cell::OnceCell](https://doc.rust-lang.org/std/cell/struct.OnceCell.html) primitive that should (in theory) replace the commonly used [once_cell](https://crates.io/crates/once_cell) crate.

Regex README [documents](https://github.com/rust-lang/regex/tree/5e8eaf1f7ab92b68bfabaa004561ccb1269ecb9f#usage-avoid-compiling-the-same-regex-in-a-loop) how to use the once_cell crate.  Should it be updated with the now standardized OnceCell?

**Comment by BurntSushi** [comment]
I think you mean [`std::sync::OnceLock`](https://doc.rust-lang.org/std/sync/struct.OnceLock.html).

`OnceLock` is a slightly lower level primitive and is a little more annoying to use. It's also very new. I'd rather stick with `once_cell` for now. I do expect I'll update this at some point.

**Comment by nyurik** [comment]
Sure, and thx, you are right - I meant OnceLock.  Just in case someone would like to use the Readme example with OnceLock, posting bellow.  Could you clarify what you meant by a bit lower level - it seems the usage is nearly identical?

```rust
use regex::Regex;
use std::sync::OnceLock;

fn some_helper_function(haystack: &str) -> bool {
    static RE: OnceLock<Regex> = OnceLock::new();
    RE.get_or_init(|| Regex::new(r"...").unwrap())
        .is_match(haystack)
}

fn main() {
    assert!(some_helper_function("abc"));
    assert!(!some_helper_function("ac"));
}
```

**Comment by BurntSushi** [comment]
Compare `static RE: Lazy<Regex> = Lazy::new(|| Regex::new(r"...").unwrap());` with what you have, which is two lines. It's a small thing, but the `Lazy<Regex>` approach is definitely a little nicer.

The `once_cell` crate docs do have a `regex!` macro that uses `OnceCell` and its use is pretty nice:

```
macro_rules! regex {
    ($re:literal $(,)?) => {{
        static RE: once_cell::sync::OnceCell<regex::Regex> = once_cell::sync::OnceCell::new();
        RE.get_or_init(|| regex::Regex::new($re).unwrap())
    }};
}
```

There is some more discussion about that in #709.

I overall don't think it's a huge problem to leave it as-is. I'm sure it will get migrated eventually, but I prefer to move more slowly.

**Comment by dharmesh404** [comment]
> Sure, and thx, you are right - I meant OnceLock. Just in case someone would like to use the Readme example with OnceLock, posting bellow. Could you clarify what you meant by a bit lower level - it seems the usage is nearly identical?
> 
> use regex::Regex;
> use std::sync::OnceLock;
> 
> fn some_helper_function(haystack: &str) -> bool {
>     static RE: OnceLock<Regex> = OnceLock::new();
>     RE.get_or_init(|| Regex::new(r"...").unwrap())
>         .is_match(haystack)
> }
> 
> fn main() {
>     assert!(some_helper_function("abc"));
>     assert!(!some_helper_function("ac"));
> }

Rust documentation for get_or_init says:
pub fn get_or_init<F>(&self, f: F) -> &T
where
    F: FnOnce() -> T,
It is an error to reentrantly initialize the cell from f. The exact outcome is unspecified. Current implementation deadlocks, but this may be changed to a panic in the future.

Should this be handled in the above mentioned code ?

**Comment by nyurik** [comment]
By now the much better alternative is [LazyLock](https://doc.rust-lang.org/std/sync/struct.LazyLock.html)


```rust
use regex::Regex;
use std::sync::LazyLock;

fn some_helper_function(haystack: &str) -> bool {
    static RE: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"...").unwrap());

    RE.is_match(haystack)
}

fn main() {
    assert!(some_helper_function("abc"));
    assert!(!some_helper_function("ac"));
}
```
