### ISSUE TITLE
`case_fold_simple` for negated classes

### ISSUE THREAD

**Issue by plusvic** [rust-lang/regex#1055]
#### Describe your feature request

The [case_fold_simple](https://docs.rs/regex-syntax/latest/regex_syntax/hir/enum.Class.html#method.case_fold_simple) method  does a great job at expanding a class like `[a-f]` to  `[a-fA-F]`. However, for negated classes like `[^a-f]` no similar alternative exists that produces the class `[^a-fA-F]`.  Using `case_fold_simple` with class `[^a-f]` produces a class that contains all possible characters.

Currently,`case_fold_simple` does the following:

1) For every lower-case character (`[a-z]`) in the class, add the corresponding upper-case character.
2) For every upper-case character (`[A-Z]`) in the class, add the corresponding lower-case character. 

Implementing a function that does the same for negated classes would be simple:

1) For every lower-case character (`[a-z]`) in the class, remove the corresponding upper-case character.
2) For every upper-case character (`[A-Z]`) in the class, remove the corresponding lower-case character.

However, the underlying issue that renders this solution useless is that there's no way for knowing if a class is a negated class or not. The HIR doesn't know about negated classes, all classes are represented in a positive way by indicating which characters are present in the class, and the information about whether it was originally a negated class is lost.

Does it make sense to propagate that information from the AST to the HIR? 

By having a boolean at the HIR level that tell us whether a class was originally negated, `case_fold_simple` could behave in one way or the other (I believe it should not break any existing code, as using `case_fold_simple` on a class like `[^a-z]` seems useless at this moment anyways).

In the other hand it opens other questions, like whether the result of the `negate` method should  be a class where the `negated` flag is set or not.

I'm not sure which could be a reasonable solution to this issue, if such solution exists. Any thoughts on this?

**Comment by BurntSushi** [comment]
> At this point, I think we need to pop up a level and look at the problem you're trying to solve that led to the solution proposed here.

Taking a crack at this, if it's, "I care about the specific expressive forms written by a human in the concrete syntax of the regex" in order to determine the semantics of what something means, then I'm afraid the right solution there is to solve your problem from the `Ast` and not the `Hir`. (This could arguably be quite a bit of work as HIR translation is doing a fair bit of Unicode heavy lifting for you.)

**Comment by plusvic** [comment]
Agreed. By looking at the source code I also got the impression that adding that flag to the HIR was against the design principles of the HIR itself. So, my question was more in the line of: is there any solution to this issue that fits well in the current design? The more I look at the code, and given some examples like `[a-z[^A-Z]]`, it's getting clear to me that the solution doesn't exist and I need to change my strategy.

Let me shed more light on why I need this. I'm using `regex-syntax` to parse regular expressions from source to HIR, and also use a HIR as the data structure to represent other [kinds of patterns](https://yara.readthedocs.io/en/stable/writingrules.html#hexadecimal-strings) that are really a subset of regular expressions. I use the literal extraction features offered by the HIR for extracting literals from the regexp that I can use to speed up searches by using Aho-Corasick for finding points where there's a potential match. But extracting prefix and postfix literals is not enough in my case, I also need to be able to extract infix literals. In a regexp like `a.*foo123*z` I can't afford searching for `a` or `z` when I can search for `foo1` (I use 4 byte literals). My literal extraction logic also realizes that in the case of case-insensitive regexps, it's better to use `o123` instead of `foo1` because the former only have two variants (`o123` and `O123`), while the latter has 8. In order to make this logic simpler, I build the HIR as if the regular expression is always case-sensitive, and case-insensitiveness is handled during the generation of my own NFA. But then I found this issue with case-insensitive negated class, where I can't be sure that if the original class was negated or not, and can't make the class case-insensitive without having this information. The trick of `negate -> casefold -> negate` doesn't work without knowing if you need to use the trick in the first place, doing that to a non-negated class like `[a-z]` results in an empty class.

It looks like the solution in my case is building the HIR taking case-sensitiveness into account, even if this makes literal extraction more complex.

**Comment by plusvic** [comment]
At the end I changed my strategy and stopped forcing the HIR to be case-insensitive, it requires some changes in my original design but it doesn't look that complex. Sorry for taking your time, the feedback was appreciated anyways!

**Comment by BurntSushi** [comment]
Ah that's an exciting problem! Glad you found a different strategy.

I contemplated adding inner literal extraction to `regex-syntax`, but it just felt too heuristic-y to me. I did wind up [writing an inner literal extractor based on `literal::Seq` for ripgrep though.](https://github.com/BurntSushi/ripgrep/blob/053a1669bb10482f0e09fd4faf9e80b1b5d1200a/crates/regex/src/literal.rs#L547-L574) It's mostly the same as the prefix extractor, but with [even more suspicious heuristics](https://github.com/BurntSushi/ripgrep/blob/master/crates/regex/src/literal.rs#L547-L574).

Out of curiosity, how are you avoiding the worst case quadratic behavior that usually comes with looking for inner literals? See for example [this](https://github.com/BurntSushi/rebar/blob/0203f1af6bb1d19071658c74e7541bcc3ad30a53/benchmarks/definitions/opt/reverse-suffix.toml) and [this](https://github.com/BurntSushi/rebar/blob/0203f1af6bb1d19071658c74e7541bcc3ad30a53/benchmarks/definitions/opt/reverse-inner.toml). Or do you have constraints on the size of a haystack that let you take some other shortcut?

(Sorry for the off topic question!)

**Comment by plusvic** [comment]
I have a limit on the number of bytes the NFA can match both in backward and forward direction. If the literal is found at offset `X`, the NFA only explores the range  `[X-N, X+N]`. I don't use any other type of mitigations, but in the future I would like to explore the idea of aborting the backward search when it reaches a point in the haystack that was already scanned.

Another technique that I use is splitting regexps into multiple chained regexps. For example `abc.*def` is split into `abc` and `def`, where `def` is "chained" to `abc` (assuming here that `.*` matches every possible byte, which is not the case when `.` doesn't match newlines). The idea here is that once I find `abc` I keep it as an unconfirmed match, that is confirmed only when `def` is found. I do this for bounded repetitions as well, like `abc.{0,400}def`, when the "gap" can be larger than a certain threshold I use this technique, if it is small enough I treat it in the usual way.
