### ISSUE TITLE
Dependency outdated

### ISSUE THREAD

**Issue by QuarticCat** [rust-lang/regex#1056]
`regex-automata v0.3.3` depends on `regex-syntax v0.7.0`. However, it actually relies on `line_terminator` which doesn't exists in `regex-syntax v0.7.0`. This dependency version should be bumped.

**Comment by BurntSushi** [comment]
This is fixed in `regex-automata 0.3.4` on crates.io.

I used to have a minimal versions check in CI but it proved too difficult to maintain because others in the ecosystem were specifically and intentionally non-cooperative with it. But perhaps that has changed.
