### ISSUE TITLE
Support Quotation `\Q` and `\E`

### ISSUE THREAD

**Issue by MarcusDunn** [rust-lang/regex#1093]
I have a rust web service that takes in a regex as an parameter and generates tokens from an LLM matching the regex. I consume this service from a Kotlin/Java program.

I sometimes want the LLM to generate one of a series of options. (i.e `true` or `false` responses to a question)

the naive solution for generating the regex on the Java/Kotlin side works fine provided the `values` are simple strings.

```kotlin
// ["hello", "world"] -> (hello)|(world)
values.joinToString("|") { "($it)" }
```

But allowing for more exotic options means doing something like this

```kotlin
// ["hello", "world"] -> (\Qhello\E)|(\Qworld\E)
values.joinToString("|") { "(${Regex.quote(it)})" }
```

Which compiling something like `(\Qhello\E)|(\Qworld\E)` on the rust side yields `error: unrecognized escape sequence`

This may just be a "I cannot read docs correctly" and there is a supported sequence in the lib - but I cannot find it.

Also perhaps of note, I am building the regex using `regex-automata` and stepping through it manually for perf reasons. 

Edit: I found `regex::escape` which quotes every meta character. I cannot quite implement this on my end without knowing the details of `is_meta_character` inside my Kotlin/Java server. So for now I'll do preprocessing of the regex string where I replace the quoted sections with the result of `regex::escape`. I'll keep the issue around in case something like this would be a worthwhile addition.

**Comment by BurntSushi** [comment]
Implementing your own quoting routine is the way to go here. One thing that might make you feel better about depending on how `is_meta_character` works is that it pretty much already exposes its internals:

> Note that the set of characters for which this function returns true or false is fixed and won’t change in a semver compatible release. (In this case, “semver compatible release” actually refers to the regex crate itself, since reducing or expanding the set of meta characters would be a breaking change for not just regex-syntax but also regex itself.)

In other words, the `match` statement that corresponds to the implementation of `is_meta_character` can only change when a hypothetical `regex 2.0` is released. Not only are there no current plans for releasing a 2.0, but I can't see `is_meta_character` changing even if there was.

With respect to `\Q...\E`, indeed, this crate does not support it. The main problem I have with it is that it leads to a false sense of security. And it doesn't actually permit one to insert arbitrary strings. For example, if you try to interpolate `\Q{foo}\E` by replacing `{foo}` with a string that contains `\E` inside of it somewhere, then anything appearing after `\E` is now able to use arbitrary regex features. This is especially bad if you're accepting user input that you always want to treat literally. The only safe way to do that is to quote it.

I grant that `\Q...\E` is convenient in some cases, but in experience it's usually just a bug waiting to happen.

**Comment by MarcusDunn** [comment]
I missed the docs on `is_meta_character`, that keeps things simple on my end - Thanks!
