### ISSUE TITLE
crates.io seems to be out of sync for regex_macros 0.1.1

### ISSUE THREAD

**Issue by oderwat** [rust-lang/regex#11]
I try to compile a project with "myslq" and get the following:

`~/.cargo/registry/src/github.com-1ecc6299db9ec823/regex_macros-0.1.1/src/lib.rs:604     fn vec_expr<T, It: Iterator<T>>(&self, xs: It,`

Looking in the actual code of 0.1.1 the line was updated. Is there a version bump missing?

**Comment by huonw** [comment]
Updated!
