### ISSUE TITLE
hexadecimal literal is not a Unicode scalar value

### ISSUE THREAD

**Issue by LuckyTurtleDev** [rust-lang/regex#1115]
#### What version of regex are you using?

If it isn't the latest version, then please upgrade and check whether the bug
is still present.

#### Describe the bug at a high level.
I have try to use [this regex](https://ihateregex.io/expr/emoji/) to match emojis.
```
 (\u00a9|\u00ae|[\u2000-\u3300]|\ud83c[\ud000-\udfff]|\ud83d[\ud000-\udfff]|\ud83e[\ud000-\udfff]) 
```
But calling `Regex::new()` on it creates the error  `hexadecimal literal is not a Unicode scalar value`.

#### What are the steps to reproduce the behavior?
Minimal example, which include only the unicode sequence, which fail.
```rust
fn main() {
    regex:Regex::new(r"\ud83c").unwrap();
}
```
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=beac1c548adb05dee7a5cedd4df549f7

#### What is the actual behavior?
```rust
error: path separator must be a double colon
 --> src/main.rs:2:10
  |
2 |     regex:Regex::new(r"\ud83c").unwrap();
  |          ^ help: use a double colon instead: `::`

error: could not compile `playground` (bin "playground") due to previous error
```

#### What is the expected behavior?

return `Ok` instead of `Err` :question:

**Comment by BurntSushi** [comment]
You're using `regex:Regex` instead of `regex::Regex`. As a result, the error emitted from your reproduction is not the Unicode scalar value error.

Otherwise, the scalar value error is correct. `\ud83c` is a surrogate codepoint, not a scalar value. Surrogate codepoints are only used with UTF-16. This crate uses UTF-8.

**Comment by LuckyTurtleDev** [comment]
> You're using regex:Regex instead of regex::Regex. As a result, the error emitted from your reproduction is not the Unicode scalar value error.

Looks like I have mess up creating the example without notice it. :facepalm: I have fix this now.

> Surrogate codepoints are only used with UTF-16. This crate uses UTF-8.

Can I still use this if I split it in two bytes or will this create an error, because it is not valid uf8?
What happen if I match a regex against a utf-16 string?

**Comment by LuckyTurtleDev** [comment]
Never mind I can simple use `\p{Emoji}`
