### ISSUE TITLE
Mention MSRV change in CHANGELOG.md

### ISSUE THREAD

**Issue by Wilfred** [rust-lang/regex#1119]
It looks like regex 1.10.0 bumped MSRV from 1.60 to 1.65. Could you mention this in the changelog? It looks like previous MSRV bumps are documented there.

**Comment by BurntSushi** [comment]
It was mentioned. The third sentence. From the [`1.10.0` tag](https://github.com/rust-lang/regex/blob/1.10.0/CHANGELOG.md):

> The minimum supported Rust version has also been raised to 1.65, which was released about one year ago.
