### ISSUE TITLE
Add/replace std::OnceCell mention in the Readme

### ISSUE THREAD

**Issue by dustdfg** [rust-lang/regex#1123]
Inside the readme in section [Usage: Avoid compiling the same regex in a loop](https://github.com/rust-lang/regex#usage-avoid-compiling-the-same-regex-in-a-loop) is used external library. Standard library (even core crate) includes [OnceCell since 1.70](https://doc.rust-lang.org/nightly/core/cell/struct.OnceCell.html) so I think it should be added/replaced...

**Comment by BurntSushi** [comment]
This has been requested before. I'm on mobile but please search issue tracker.
