### ISSUE TITLE
Have a way to iterate over sub matches with names included

### ISSUE THREAD

**Issue by tmccombs** [rust-lang/regex#1151]
In cases where the regex pattern is dynamic, for example because it is user supplied, it would be nice if it was possible to iterate over the captures in a way that had access to the name of the capture group, if any. 

It is possible to work around this by using `Regex::capture_names`. 

Looking at the implementation of [regex_automata::util::captures::CapturesPatternIter](https://docs.rs/regex-automata/latest/regex_automata/util/captures/struct.CapturesPatternIter.html#) it looks like the iterator does have access to the names, but it doesn't expose it.

**Comment by BurntSushi** [comment]
I think you should use `Regex::capture_names`. I wouldn't really call it a "work-around," but rather, orthogonal and composable APIs. It should be possible to zip it with the iterator on `Captures`.

I don't want to expose yet another iterator type. I don't think it would be commonly used (iterating over captures is already somewhat niche) enough to justify its existence.
