### ISSUE TITLE
Valgrind reports "possible lost" when using static `Regex`

### ISSUE THREAD

**Issue by wyfo** [rust-lang/regex#1205]
#### What version of regex are you using?

`regex = "1.10.5"`

#### Describe the bug at a high level.

Valgrind reports "possible lost" when using static `Regex`.

#### What are the steps to reproduce the behavior?

use regex::Regex;

static mut REGEX: Option<Regex> = None;

fn main() {
    unsafe {
        REGEX = Regex::new(r"").ok();
        REGEX.as_ref().unwrap().captures("");
    }
}

#### What is the actual behavior?

Here is valgrind command and report:

#### What is the expected behavior?

What do you expect the output to be?

**Comment by BurntSushi** [comment]
Yeah, so? You're sticking the `Regex` in a global mutable variable. Its destructor will never run.

**Comment by wyfo** [comment]
Sorry, I missclicked and submitted without the full text. I've edited the description.
I know the destructor is never run, but usually (at least in my short experience), it results in `still reachable` and not in `possible lost`. 
Quoting the Valgrind documentation:
> "possibly lost" means your program is leaking memory, unless you're doing unusual things with pointers that could cause them to point into the middle of an allocated block; see the user manual for some possible causes. Use --show-possibly-lost=no if you don't want to see these reports.

> "still reachable" means your program is probably ok -- it didn't free some memory it could have. This is quite common and often reasonable. Don't use --show-reachable=yes if you don't want to see these reports.

`possible lost` may thus indicate a possible bug, that's why `valgrind` default behavior is to treat them as an error.

My question is then: does these `possible lost` blocks fall in the category of "unusual things with pointers that could cause them to point into the middle of an allocated block", or may it be a non trivial memory leak?

**Comment by wyfo** [comment]
To give some context, I'm facing this possible leak using `tracing_subscriber::EnvFilter`, which uses `Lazy<Regex>` internally https://github.com/tokio-rs/tracing/blob/master/tracing-subscriber/src/filter/env/directive.rs#L123.

About the `still reachable`/`possible lost` distinction, `tracing` is using a static subscriber, and that results in a `still reachable`, see https://github.com/tokio-rs/tracing/issues/2069, and that's totally fine. However, when using `EnvFilter` the leak changes of category, "because" of this `Lazy<Regex>`.

**Comment by wyfo** [comment]
Another maybe useful information, the `possibly lost` blocks number and size changes with the regex.
For example: 
- `Regex::new(r"")` -> `possibly lost: 216 bytes in 2 blocks`
- `Regex::new(r"\w")` -> `possibly lost: 416 bytes in 2 blocks`
- `Regex::new(r"(?P<name>\w)")` -> `possibly lost: 524 bytes in 3 blocks`

**Comment by wyfo** [comment]
Ok, I've understood that it felt in the case "doing unusual things with pointers", sorry for the bother. Seem's I've to add a `valgrind` *suppression*.

**Comment by BurntSushi** [comment]
My prior is that valgrind reports false positives, and that its behavior at least partially depends on the allocator being used. So I need more evidence.

Otherwise, I don't really see anything wrong here. Like yes... you have a leak because you aren't running a regex's destructor. And yes, it changes with different patterns because different patterns require different amounts of heap... I'm not sure why you would expect anything different.

**Comment by BurntSushi** [comment]
Also, `regex` internally doesn't really do anything that would cause leaks in the first place. Rust is itself doing a lot of leak checking already.
