### ISSUE TITLE
valgrind reports "Conditional jump or move depends on uninitialised value(s)"

### ISSUE THREAD

**Issue by radkum** [rust-lang/regex#1211]
Hello guys,
When running a simple single line program I get a valgrind error:
```
let _ = Regex::new(r"(\}\})|\{(\{|[^{}}]+\})");
```
![screenshot-4](https://github.com/user-attachments/assets/3ec491ef-c0d4-41a5-a4bf-2b068fea4e44)

I saw very similar issue here, but I'm not sure it's the same case: https://github.com/rust-lang/regex/issues/274

Can you look at it?

Crate version: Latest (1.10.5)

**Comment by BurntSushi** [comment]
I don't see anything suspicious there. As mentioned in #274, valgrind is known for giving false positives in Rust programs. That doesn't mean it's always wrong, but please do more investigation first. Consider, for example, that the regex crate is tested with Miri.

**Comment by BurntSushi** [comment]
Also, please provide textual reproductions in the future. When you provide a screenshot, you're asking others to re-type everything shown in the image.......
