### ISSUE TITLE
no_std support and cargo.toml doc comments 

### ISSUE THREAD

**Issue by mspiegel** [rust-lang/regex#1212]
On the main branch, the Cargo.toml has a paragraph of comments about the 'std' feature. Are those comments up to date? I was able to compile regex 1.10.5 with default-features = false. It seems to be working.

**Comment by BurntSushi** [comment]
It's an outdated comment. The crate features are documented in the crate documentation: https://docs.rs/regex/latest/regex/#crate-features

**Comment by mspiegel** [comment]
Thanks. I opened https://github.com/rust-lang/regex/pull/1213 with a fix and it enables the integration tests for no_std.
