### ISSUE TITLE
Rust unstable API change causes compilation error of unstable `pattern` feature

### ISSUE THREAD

**Issue by yhx-12243** [rust-lang/regex#1231]
As the title says, the rust standard library [add a function to the unstable `Pattern` trait](https://github.com/rust-lang/rust/commit/4484085b18df4b10243b503a21602bb71836e8b3#diff-501aca1598977b7479bb663f9ea6b0bc2a89dd5dd8851b7bd414ec6aab9788c7R163-R166), so these code will cause a compilation error.

https://github.com/rust-lang/regex/blob/bcbe40342628b15ab2543d386c745f7f0811b791/src/pattern.rs#L13-L24

**Comment by BurntSushi** [comment]
https://github.com/rust-lang/regex/pull/1232
