### ISSUE TITLE
Expose `group_info()` for Regex::Captures

### ISSUE THREAD

**Issue by wesleyel** [rust-lang/regex#1238]
Hi there!

I'm writing a wrapper for regex crate's [`Regex::Captures`](https://docs.rs/regex/latest/regex/struct.Captures.html) struct, and for this I need to get the `group_info` member of [`regex_automata::util::captures::Captures`](https://github.com/rust-lang/regex/blob/1a069b9232c607b34c4937122361aa075ef573fa/regex-automata/src/util/captures.rs#L134). 

But I found that the `Regex::Captures` type currently does not have a way to export its caps attribute or the [`group_info()`](https://github.com/rust-lang/regex/blob/1a069b9232c607b34c4937122361aa075ef573fa/regex-automata/src/util/captures.rs#L674C1-L676C6) method of the caps attribute.

Would regex willing to accept a patch that expose `group_info()`? Or Maybe I should head to use `regex_automata`?

Thanks!

**Comment by BurntSushi** [comment]
You can't just expose `GroupInfo`. That would make `regex-automata` a public dependency of `regex`, which it is very intentionally and very carefully not. So to do that, we'd need to make a wrapper type for it.

In general, I do not expand the API of `regex` without good reason, and I don't see any motivating examples here to argue in favor of that direction.

Yes, you should be using `regex-automata`.
