### ISSUE TITLE
remove is_match free function

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang/regex#165]
I think it was unwise to ever add this and I didn't give much thought to it. I saw it as a convenience for just quickly matching a regex against some text, but:
1. It's more explicit to just create the `Regex` value and us that to match.
2. It encourages compiling the regex every time it's used to search text, which is an anti-pattern because compilation is much slower relative to execution.

**Comment by kevincox** [comment]
While I see the benefit of the function, the full API is so simple to use that it has little benefit and as you mentioned it encourages bad usage patterns. I don't feel strongly either way.
