### ISSUE TITLE
optimize use of `^`/`\A`

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang/regex#17]
At the moment, the VM always scans the [entire input](https://github.com/rust-lang/regex/blob/master/src/vm.rs#L139) unless one of the two following things happens:

* The regex has a *literal prefix* and that prefix cannot be found anywhere in the input. (This always scans the entire input.)
* A match is found. This may *not* scan the entire input, but it requires a match.

Ideally, given a regex `^{something}...`, it could terminate the search early if `{something}` doesn't match at the start of the input.

**Comment by BurntSushi** [comment]
@alexcrichton Is this the right place to report issues for `regex`? There are some issues on the `rust` repo...

Also, if changes get made to this repo, do they get pulled into `rust` repo? Or is it the other way around?

**Comment by alexcrichton** [comment]
Sure! I think any existing issues should be migrated here as well. Feel free to ping nrc on IRC for any lingering issues, he's got a script which will auto-transfer issues between repos.
