### ISSUE TITLE
documentation site is 404

### ISSUE THREAD

**Issue by majewsky** [rust-lang/regex#309]
https://crates.io/crates/regex has a "Documentation" link going to https://doc.rust-lang.org/regex, but that page is 404:

![screenshot_20161229_131700](https://cloud.githubusercontent.com/assets/24696/21543701/1fb81e80-cdc9-11e6-979a-e0e972b764f6.png)

**Comment by BurntSushi** [comment]
We just moved regex from rust-lang-nursery to rust-lang,. This appears to be fallout from that. 

With that said, I don't think I can personally fix this one. @alexcrichton? :-)

**Comment by alexcrichton** [comment]
Oops, fixed!
