### ISSUE TITLE
Regex docs don't point people to crates.io dependency

### ISSUE THREAD

**Issue by hjr3** [rust-lang/regex#31]
Reading http://doc.rust-lang.org/regex/regex/index.html and http://doc.rust-lang.org/regex/regex/enum.Regex.html there is no hint to the user that they should be updating `Cargo.toml` with something like:

```toml
[dependencies]
regex = "*"
regex_macros = "*"
```
The error doesn't help either:

```
   Compiling example v0.0.1 (file:///path/to/projects/example)
src/main.rs:5:1: 5:27 error: can't find crate for `regex_macros`
src/main.rs:5 extern crate regex_macros;
```

**Comment by m-bra** [comment]
+1
