### ISSUE TITLE
x flag not working as expected

### ISSUE THREAD

**Issue by Ekleog** [rust-lang/regex#311]
Hello,

Trying to run the following code:
```rust
fn main() {
   lazy_static! {
       static ref ARG_RE: regex::Regex = regex::Regex::new(r"(?x)
           ^arg\s*\[\s*(?P<arg>[0-5])\s*\]\s+                   # arg[a]
           (?P<op>==|<=|<|>=|>|has bits|has no bits|in bits)\s+ # operator
           (?P<val>[1-9][0-9]*)$                                # value, integer
       ").unwrap();
       static ref RE2: regex::Regex = regex::Regex::new(
           r"^arg\s*\[\s*(?P<arg>[0-5])\s*\]\s+(?P<op>==|<=|<|>=|>|has bits|has no bits|in bits)\s+(?P<val>[1-9][0-9]*)$"
       ).unwrap();
   }
   println!("REGEX TEST: {:?}", ARG_RE.captures("arg[1] has no bits 3"));
   println!("REGEX TEST: {:?}", RE2.captures("arg[1] has no bits 3"));
}
```

I get a different result after each of the two calls. However, as the two regexes differ only in whitespace and #-comments (as far as I can tell), they should have the same effect.

Is there something I missed?

**Comment by BurntSushi** [comment]
Can you please simplify the regexes?

**Comment by BurntSushi** [comment]
Your regexes have significant spaces in them, e.g., "has bits". The x flag
and significant whitespace are incompatible. You can either selectively
disable the x flag or use hex escapes.

**Comment by Ekleog** [comment]
Oh, thanks! Sorry, I had tried simplifying the regexes but the issue disappeared, so I thought it was a simple example… but it was just that I was removing the significant spaces.

Thanks for your time and sorry!

**Comment by BurntSushi** [comment]
@Ekleog No worries! The best bugs are the ones that fix themselves. :-)
