### ISSUE TITLE
PartialEq is not implemented in version 0.2

### ISSUE THREAD

**Issue by tredoe** [rust-lang/regex#313]
With the version 0.2, I get:
```
error[E0369]: binary operation `==` cannot be applied to type `std::option::Option<regex::Regex>`

note: an implementation of `std::cmp::PartialEq` might be missing for `std::option::Option<regex::Regex>`
```

**Comment by BurntSushi** [comment]
Indeed it is not. See the changelog please. :-)

**Comment by tredoe** [comment]
Please, could you add an example about how do it? For beginners
Thanks!

**Comment by BurntSushi** [comment]
Oh absolutely! I'm on mobile right now, so it's a a little tough to write it the code, but I'll try to get the idea across and then clean it up later. :-)

The low tech solution is to just change `re1 == re2` to `re1.as_str() == re2.as_str()`. That might be all you need. But if you're, say, using regexes as keys in a btree map, then you'll need a wrapper type that implements `PartialEq` for you.

First, you need to define a wrapper type: `struct MyRegex(regex::Regex)`. For convenience, you'll want to implement the `std::ops::Deref` trait. This will make it so you can call all of the methods on Regex through your MyRegex type. Second, you'll need to implement the `std::cmp::PartialEq` on your MyRegex type, which can be done using the the as_str methods from the "low tech" solution above.
