### ISSUE TITLE
Captures.get(x) returns Option<Match> while Captures[x] returns &str

### ISSUE THREAD

**Issue by shssoichiro** [rust-lang/regex#320]
In core and std data structures, `Index` is generally used as a shorthand for `.get().unwrap()`. This decision in `regex` may have been done intentionally, but it seems to me that having `.get()` return a different type than `Index` violates the principle of least astonishment (I would expect `Index` to return a `Match` here).

**Comment by BurntSushi** [comment]
It was done intentionally. The reason why is because `caps[index]` is very useful as a shorthand to reference the matched text. The indices themselves are rarely needed in my experience, in which case, it seems fine to expect to fall back to the `get`/`name` methods.
