### ISSUE TITLE
plan for 1.0 beta/stable channel?

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang/regex#33]
This is mostly about `regex_macros` and its future. Once beta hits, `regex_macros` will fail to compile on anything but the nighties until a plugin API has been stabilized. How are we going to manage that in this repository? i.e., The repo would contain one crate (`regex`) that should work on Rust 1.0 stable (which currently has a `dev-dependency` on `regex_macros`) and another crate (`regex_macros`) that can only work on Rust nightlies. Is it possible for them to cohabitate?

Of secondary concern is the docs. There is a lot of language strongly suggesting use of the `regex!` macro. Methinks this has to be removed or changed, because teasing users with such an awesome feature is going to make them mad. :-)

Of third concern is the programming shootout. There is a `regex-dna` benchmark. How do we handle it? Oh, wait, errmm, it [appears to have disappeared](https://github.com/rust-lang/rust/tree/master/src/test/bench)? Ah, [found the commit](https://github.com/rust-lang/rust/commit/6c29708bf906fa9075bb96b76fd7f6cc81eda43c). That's reasonable. Will it not be included in the shootout any more?

N.B. @erickt is working on [rust-syntex](https://github.com/erickt/rust-syntex), which I think ought to support use of the `regex!` macro. This may help with the docs, but `regex_macros` still needs to be handled.

**Comment by alexcrichton** [comment]
> How are we going to manage that in this repository?

Having a `dev-dependency` on `regex_macros` only kicks in during development, so publication to crates.io for `regex` should work fine on and off nightly. It just means that if you use `regex_macros` with stable rust you'll get some compile errors.

> Is it possible for them to cohabitate?

I think the implication is that this repository must be developed with nightly, but that's not necessarily the end of the world!

> Methinks this has to be removed or changed, because teasing users with such an awesome feature is going to make them mad. :-)

I'd be fine with this!

> Of third concern is the programming shootout.

Oh I meant to do this, I'd be fine moving the shootout benchmark into this repo under `benches`

> N.B. @erickt is working on rust-syntex, which I think ought to support use of the regex! macro

That'd be pretty sweet to get the compile time optimizations on stable rust so quickly!

**Comment by BurntSushi** [comment]
> I think the implication is that this repository must be developed with nightly, but that's not necessarily the end of the world!

I'm definitely OK with this, but how do we test the `regex` crate on Rust 1.0 stable? i.e., Because of the `dev-dependency` on `regex_macros`, `cargo test` on Rust 1.0 stable should fail I think.

**Comment by BurntSushi** [comment]
Oh, and I'll bring the shootout benchmark back into this repo tonight. :-) Happy to see it live on!

**Comment by alexcrichton** [comment]
To test `regex` on stable we would probably want to move all the `regex!` tests into the `regex_macros` crate so testing the `regex` crate would only test `Regex::new` and testing `regex_macros` would test `regex!

**Comment by BurntSushi** [comment]
I think all of the issues listed here have been fixed in: https://github.com/rust-lang/regex/commit/2d0e77a457c17772f067e40b9ddceb615b9bf7be.
