### ISSUE TITLE
add example using curly braces in replacement string

### ISSUE THREAD

**Issue by nathanaeljones** [rust-lang/regex#333]
This used to work:
`assert_eq!(Regex::new("(.)").unwrap().replace_all("a", "$1_"), "a_" );`

But now produces "" instead of "a_". 

It would appear that underscores somehow cause the replacement to be deleted instead of added. 

Named captures don't fix it:

`assert_eq!(Regex::new("(?P<char>.)").unwrap().replace_all("a", "$char_"), "a_" ); //actual: ""`

But inserting a space between the capture and underscore works!

`assert_eq!(Regex::new("(.)").unwrap().replace_all("a", "$1 _"), "a _" );`
`assert_eq!(Regex::new("(?P<char>.)").unwrap().replace_all("a", "$char _"), "a _" );`

As does using curly braces around the identifier (the only apparent workaround)

`assert_eq!(Regex::new("(?P<char>.)").unwrap().replace_all("a", "${char}_"), "a_" );`

**Comment by BurntSushi** [comment]
This was an intended but undocumented breaking change. Note the docs for `expand` say:

> name may be an integer corresponding to the index of the capture group (counted by order of opening parenthesis where 0 is the entire match) or it can be a name (consisting of letters, digits or underscores) corresponding to a named capture group.

and also

> The longest possible name is used. e.g., $1a looks up the capture group named 1a and not the capture group at index 1. To exert more precise control over the name, use braces, e.g., ${1}a.

So this means that the reason why you're getting the behavior you see is that `1_` is used as the capture group name, and since that doesn't refer to any valid capture, it is replaced with the empty string. Indeed, the fix is to use curly braces.

**Comment by nathanaeljones** [comment]
Ah. My assumption was that the replacement string was parsed in the context of the regex, and that non-existent captures would fail to expand instead.

It'd probably be good to emphasize this, and stick to the curly brace syntax for examples. I'm not aware of other regex implementations with this behavior, thus my confusion :)

**Comment by BurntSushi** [comment]
@nathanaeljones Go's regexp engine has precisely the same semantics. But yes, better docs here would be great.
