### ISSUE TITLE
please include license files into crates.io archive

### ISSUE THREAD

**Issue by ignatenkobrain** [rust-lang/regex#342]
I see that licenses are in repo, but not included in sub-crates. ASL 2.0 requires license text to be presented along with sources

**Comment by BurntSushi** [comment]
@alexcrichton Is there a way to do this with some `Cargo.toml` options? Or should I just copy the license files into each crate directory?

**Comment by clarcharr** [comment]
@BurntSushi `package.license-file` in `Cargo.toml`

**Comment by ignatenkobrain** [comment]
@BurntSushi but it's only one file, what about second one?

**Comment by alexcrichton** [comment]
@BurntSushi ah unfortunately I think you'd have to copy them around, I hadn't thought of this...
