### ISSUE TITLE
Consider allowing unescaped `{` to be a literal when there's no preceeding expression

### ISSUE THREAD

**Issue by robinst** [rust-lang/regex#356]
Other engines such as Oniguruma and PCRE allow `{` as a literal in places where it can not be a quantifier (e.g. at the beginning of a pattern or group), to quote [PCRE 2 docs](http://www.pcre.org/current/doc/html/pcre2pattern.html#SEC17):

> An opening curly bracket that appears in a position where a quantifier is not allowed, or one that does not match the syntax of a quantifier, is taken as a literal character. For example, {,6} is not a quantifier, but a literal string of four characters.

So for example, the regex `{` matches a single literal `{` (equivalent to `\{`). Currently, the regex crate doesn't compile such a regex:

> Error parsing regex near '{' at character offset 0: Missing expression for repetition operator.

Did you consider supporting that or is it intentionally strict about this? If so, close this issue without hesitation. Just reported it because Raph brought it up here: https://github.com/google/fancy-regex/pull/6#issuecomment-293459686

Thanks for your time.

**Comment by BurntSushi** [comment]
I'm generally not a fan of rules like this. I don't know if I've ever considered this specific rule, but certainly there have been other opportunities to do things like "try parsing this construct, and if it fails, just treat it as a literal." The rules seem too implicit to me. I'd rather the regex parser be more strict and helpful as opposed to implicitly accepting a syntax.

**Comment by robinst** [comment]
Thanks. I agree with that in general. In this case it's really simple for the user too, just escape the curly. It also seems fitting for the Rust regex crate to be strict instead of accepting potentially confusing syntax.

Closing this.
