### ISSUE TITLE
macro undefined: regex!

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang/regex#36]
I'm trying to fix `regex_macros`, but replacing `#[plugin] #[no_link] extern crate regex_macros;` with `#![plugin(regex_macros)]` doesn't seem to be working. Here's a gist of my change and output of running `cargo test`: https://gist.github.com/9a19a08b72413ef86e44 --- What am I missing?

cc @alexcrichton @kmcallister

**Comment by alexcrichton** [comment]
Hm I think that should work, are you sure you had the right compiler? For example this was the commit I needed to update to master: https://github.com/rust-lang/regex/commit/5e2b292b9afeec2a80ba612a6f417b60152aa3be

**Comment by BurntSushi** [comment]
Do'h. I updated `rustc` on one machine and tried updating `regex` on another. :disappointed:  Bah. Sorry for the noise!
