### ISSUE TITLE
derive Clone on Error

### ISSUE THREAD

**Issue by remexre** [rust-lang/regex#379]
Is there a reason why Error isn't Clone?

**Comment by BurntSushi** [comment]
@remexre Hmm, I don't think so. [Note that regex-syntax's `Error` already impls `Clone`](https://docs.rs/regex-syntax/0.4.1/regex_syntax/struct.Error.html). It seems like `Clone` would be just fine for the `regex` error too. A PR for this one is welcome. :-)
