### ISSUE TITLE
Seemingly valid regex does not compile

### ISSUE THREAD

**Issue by wezm** [rust-lang/regex#383]
I was porting a regex from Perl and ran into a case where it would not compile, but I thought it should. I reduced the problematic expression down to the following:

```rust
let re = Regex::new(r"(?x) _* [ ]").expect("unable to compile regex")
```

which produces this error:

```
'unable to compile regex: Syntax("Error parsing regex near \'* [ ]\' at character offset 11: Character class was not closed before the end of the regex (missing a \']\').")'
```

**OS**: Linux
**rust:** rustc 1.18.0 (03fc9d622 2017-06-06)
**crate:**

```
[[package]]
name = "regex"
version = "0.2.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
```

**Comment by BurntSushi** [comment]
This seems correct to me? What do you expect to happen? You are using the `x` flag, which enables whitespace insensitivity mode. The whitespace inside your character class is ignored, so it's interpreted as if it was `[]`, which is itself a syntax error.

**Comment by wezm** [comment]
In Perl and Ruby (but apparently not Python upon further investigation) `[ ]` is a typical way to match a space when `/x` is enabled, which is why it tripped me up.

```ruby
irb(main):002:0> "asdf bleh" =~ /f [ ] b/x
=> 3
```

I worked around it using `\x20` but it might trip up others used to how those regex engines behave. If you don't want to support it, might be enough to document the workaround in the documentation of `(?x)`.

**Comment by BurntSushi** [comment]
I think I'd rather stick with the existing behavior, since it's consistent with the fact that `[]` is a syntax error.

If you want to use a space in `x` mode, then you can also just escape it: `\ `.

**Comment by BurntSushi** [comment]
With respect to documentation, there are *many* subtle differences between various regex engines. It probably needs a more dedicated treatment.
