### ISSUE TITLE
Possible bug in `split`

### ISSUE THREAD

**Issue by CamJN** [rust-lang/regex#387]
It seems like either there's a missing note at: https://doc.rust-lang.org/regex/regex/struct.Regex.html#method.split or a bug in split. If you use a non-capturing group in the pattern, the character that the non-capturing group matches isn't included in the results.

```
fn split_with_escapes() {
        let re = Regex::new(r"(?:[^\\])\.").unwrap();
        let fields:Vec<String> = re.split(r"a.b\.c").map(|s|s.replace(r"\.",".")).collect();

        assert_eq!(vec!["a","b.c"], fields);
    }
```

`assertion failed: '(left == right)' (left: '["a", "b.c"]', right: '["", "b.c"]')`

**Comment by BurntSushi** [comment]
I don't see any bug here. Note this part of the documentation:

> Namely, each element of the iterator corresponds to text that isn't matched by the regular expression.

In particular, your regex `(?:[^\\])\.` matches `a.` in `a.b\.c`.

> If you use a non-capturing group

It doesn't seem like a non-capturing group is relevant here. Removing the capturing group from your regex doesn't change its observable behavior.

**Comment by CamJN** [comment]
Sorry I was conflating look-around with non-capturing. You're right.
