### ISSUE TITLE
Update to more recent version of Unicode

### ISSUE THREAD

**Issue by H2CO3** [rust-lang/regex#391]
This still uses Unicode 7.0.0 which causes serious discrepancies in the handling of e.g. `XID_Start` and `XID_Continue` properties. For instance, `^\p{XID_Continue}$` doesn't match `U+17828`, whereas [unicode-xid](https://crates.io/crates/unicode-xid)'s `UnicodeXID::is_xid_continue()` correctly returns `true` for this code point.

**Comment by H2CO3** [comment]
Awesome! 🍾 👍 I don't want to sound like a pain, but is it possible that we'll see a 0.2.3 release soon with this – quite important – improvement? 😃

**Comment by BurntSushi** [comment]
I'm not sure I appreciate the importance here, but I'd like to get a couple more of the outstanding PRs merged first before cutting a release.
