### ISSUE TITLE
GitHub page links to http://doc.rust-lang.org instead of https://

### ISSUE THREAD

**Issue by jplatte** [rust-lang/regex#392]
Title should be self-explanatory.

**Comment by BurntSushi** [comment]
I fixed this (and changed the links to docs.rs).

**Comment by jplatte** [comment]
I don't know what you fixed, but it's not what I meant. The project page on GitHub still has the http link on it. Here's a screenshot so you know exactly what I'm talking about: https://screenshots.firefox.com/5bHKbS4m4EIryK9q/github.com

**Comment by BurntSushi** [comment]
@jplatte Oh I see! Thanks for clarifying. I don't have access to change that apparently.

@alexcrichton Could you change the repository description to use the link `https://docs.rs/regex` instead of the `rust-lang.org` one?

**Comment by alexcrichton** [comment]
Done!

**Comment by BurntSushi** [comment]
Woohoo! Thanks!
