### ISSUE TITLE
Replace doesn't work as expected with `\b`

### ISSUE THREAD

**Issue by emilio** [rust-lang/regex#397]
Feel free to close if this is really behaving as expected.

The following code:

```rust
extern crate regex;

use regex::Regex;

fn main() {
    let mut result = "                pub mErrorLine: root::nsTString<u16>,".to_owned();
    let r = Regex::new(r"\broot::nsTString<u16>\b").unwrap();
    
    result = r.replace_all(&result, "::nsstring::nsStringRepr").to_string();
    
    println!("{:?}", result);
}
```

Will not be able to replace the `root::nsTString<u16>`, while removing the last `\b` from the regex does.

**Comment by upsuper** [comment]
OK, I guess this actually works as expected. By definition, `\b` should be equal to `(?<=\W)(?=\w)|(?<=\w)(?=\W)`, and both `,` and `>` are not word characters, so `\b` shouldn't match there. This behavior matches other regexp engines as well.

**Comment by BurntSushi** [comment]
Yup, this is as expected.
