### ISSUE TITLE
\p{Co} does not match all Co characters

### ISSUE THREAD

**Issue by dscorbett** [rust-lang/regex#40]
`\p{Co}` only matches U+E000, U+F8FF, U+F0000, U+FFFFD, U+100000, and U+10FFFD, i.e. the first and last characters in each private-use character range.

This test fails:

```rust
extern crate regex;

use regex::Regex;

fn main() {
    let re = match Regex::new(r"\p{Co}") {
        Ok(re) => re,
        Err(err) => panic!("{}", err),
    };
    assert_eq!(re.is_match("\u{e001}"), true);
}
```

**Comment by BurntSushi** [comment]
Ug, that might mean that the Unicode character classes are being generated wrong, which is in the `unicode` crate: http://doc.rust-lang.org/unicode/regex/

**Comment by dscorbett** [comment]
This bug applies to every range in `UnicodeData.txt` which uses the `<Range, First>`/`<Range, Last>` format.

**Comment by kwantam** [comment]
@dscorbett I can't reproduce this issue, and examining the code and the Co table I can't see how it's the case. I'll take a look through the commit history and see if something has caused this to be fixed since you reported it, but afaict this bug can be closed.

**Comment by dscorbett** [comment]
My commit was for a different bug, but yes, this can be closed now.
