### ISSUE TITLE
Unicode escape syntax \x{2603} is inconsistent with Rust's \u{2603}

### ISSUE THREAD

**Issue by kevinmehall** [rust-lang/regex#402]
This crate uses `\x` for both `\xNN` and `\x{NNNN}` escapes, while Rust string literals use `\xNN` for two hex digits, but `\u{NNNN}` for an arbitrary code point .

Not a huge deal, but something to think about before 1.0.

**Comment by BurntSushi** [comment]
This matches the RE2 style of syntax. You can still use Rust Unicode literals/escapes in non-raw regex strings.

Yes, we aren't at 1.0, but I'm not changing this.
