### ISSUE TITLE
`unicode` crate availability?

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang/regex#41]
At some point, it looks like all of the character class definitions got migrated out of `regex` and into a separate `unicode` crate: http://doc.rust-lang.org/unicode/regex/ --- What are the stability plans for `unicode`? My guess is that things like `PERLD` aren't going to be included in the Rust distribution, so we'll need to plan to move forward on that.

**Comment by lfairy** [comment]
Would it be worth spinning these tables out into a separate `unicodedata` crate? These tables are quite useful outside of `regex`, and with unstable stuff being moved out the distribution, crates.io would be the perfect home for them.

**Comment by alexcrichton** [comment]
Currently there are not plans to distribute or stabilize `unicode` in the near future, so I believe this functionality will need to be folded back into the `regex` crate.

**Comment by BurntSushi** [comment]
We dropped reliance on the `unicode` crate in https://github.com/rust-lang/regex/commit/787d81214f0723f215274f519a657b5719834983, so this is no longer relevant.
