### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by carllerche** [rust-lang/regex#411]
The licensing of this repository states:

> `regex` is primarily distributed under the terms of both the MIT license and
the Apache License (Version 2.0), with portions covered by various BSD-like
licenses.

* *which* portions are covered by "various BSD-like licenses"?
* What is a BSD-like license? Which license?
* How is software licensed under MIT **AND** Apache 2? This implies that it carries the super set of both licenses (not that the user gets to pick). What does the super set of both licenses mean?

**Comment by BurntSushi** [comment]
The same exact phrasing is used for `rust` proper. Probably "... with portions covered by various BSD-like licenses" doesn't make sense in this context. The *intent* was to match the licensing of the Rust project proper.

Perhaps `rust` is the wrong precise example to copy. Maybe [Cargo](https://github.com/rust-lang/cargo#license)'s verbiage would be better? I note though that your last question still applies to Cargo's verbiage, but that no longer seems specific to this crate.

**Comment by carllerche** [comment]
The rust repo contains this file: https://github.com/rust-lang/rust/blob/master/COPYRIGHT

The `and` verbiage is included as part of "Short version for non-lawyers:"

In the longer version:

```
Except as otherwise noted (below and/or in individual files), Rust is
licensed under the Apache License, Version 2.0 <LICENSE-APACHE> or
<http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
<LICENSE-MIT> or <http://opensource.org/licenses/MIT>, at your option.
```

It seems to me that the short version using the `and` terminology is not an official license statement.

**Comment by BurntSushi** [comment]
cc @alexcrichton @aturon

**Comment by BurntSushi** [comment]
@carllerche Could you please respond to my comments about Cargo?

**Comment by carllerche** [comment]
@BurntSushi Yes, this issue is not limited to this crate.

I believe that using `and` terminology does not mean the intent (dual licensing). I believe every crate that copied the "short version" of the copyright snippet from the Rust repository did so incorrectly as the correct verbiage is below.

Something like this would be (more) correct (I believe): https://github.com/seanmonstar/reqwest#license

Of course, I am not a lawyer and I also don't think any of this has been tested in court. I only am bringing it up because I believe the verbiage does not convey the licensing intent and this could cause problems for organizations that require clear licensing.

**Comment by BurntSushi** [comment]
I'm happy with whatever the Rust project decides. (In other words, I think this issue is filled in the wrong place, but I'm not sure what the right place is.)

**Comment by alexcrichton** [comment]
@BurntSushi I've [done this](https://github.com/alexcrichton/flate2-rs/commit/baf66689e22055bb896656f34c45cbab8dfb244b) in all my projects.
