### ISSUE TITLE
Make it compile for wasm

### ISSUE THREAD

**Issue by vmx** [rust-lang/regex#422]
There's been a fruitful discussion at #421 on how to get regex to compile on the wasm32 target.

I decided to open a new issue to outline the next steps.

 - Make a new release of  [memchr](https://github.com/BurntSushi/rust-memchr/). Current HEAD already contains the changes that are needed.
 - Make a new release of [libc](https://github.com/rust-lang/libc/). Current HEAD has already changes that make memchr compile smoothly on wasm32.

Let's see if that's enough or further things are needed. I'll check ones the above ones are done.

**Comment by BurntSushi** [comment]
`memchr 2.0.1` is out. I can't do anything about `libc`. :-)

**Comment by vmx** [comment]
@BurntSushi: I've one more for you. [aho-corasick](https://github.com/BurntSushi/aho-corasick) needs a new release. The current one is still using memchr 1.x.

**Comment by BurntSushi** [comment]
@vmx Done. I also put out a new release of `regex`, which also hadn't been seen a release since `memchr` got bumped.

**Comment by vmx** [comment]
I've open an issue on libc (https://github.com/rust-lang/libc/issues/861) to do a new release. After that it should be possible to compile regex for wasm32.

**Comment by BurntSushi** [comment]
@vmx Looks like this is done! I fully expect to be using this regex crate in the browser by tonight. :P

**Comment by vmx** [comment]
My LALRPOP grammer (which uses regex) works in the browser, hence I consider this done. Thanks again everyone that was involved.

**Comment by BurntSushi** [comment]
@vmx w00t! If there's a way to share a demo that would be really awesome!
