### ISSUE TITLE
Case-folding bug.

### ISSUE THREAD

**Issue by SeanRBurton** [rust-lang/regex#428]
This fails for me on master:

```
 fn main() {
     let re = regex::bytes::Regex::new("(?iu:ŉ)").unwrap();
     let s = "ʼN";
     assert!(re.is_match(s.as_bytes()));
 }
```

Note that here `ŉ` is `U+0149`, Latin Small Letter N Preceded By Apostrophe.

**Comment by BurntSushi** [comment]
This is not a bug. The regex crate uses simple case folding, not full case folding. It is documented [here](https://docs.rs/regex/0.2.3/regex/#unicode):

> Only simple case folding is supported. Namely, when matching case-insensitively, the characters are first mapped using the simple case folding mapping before matching.
