### ISSUE TITLE
Add benchmarks for D's std.regex

### ISSUE THREAD

**Issue by mrmonday** [rust-lang/regex#430]
It would be interesting to include benchmarks for D's std.regex.

I have initial work for it, but it is not ready to be a pull request, and I probably won't find the time to clean it up:

Branch: https://github.com/mrmonday/regex/tree/d-phobos-benchmarks
Diff:  https://github.com/rust-lang/regex/compare/master...mrmonday:d-phobos-benchmarks

General notes/notes for Rustaceans who don't read D:

 * Phobos is the name of D's standard library
 * There are 2*2 cargo features, which specify the compiler (`ldc` (LLVM) vs `dmd` (Digital Mars/Reference compiler)), and the regex mode - runtime (no extension), or generated at compile time (`-ct`). There's also a gdc (GNU based) compiler, but it's not in the arch repo's, so I didn't test it.
 * Various things are hardcoded/half-baked "just make it work"
 * There's a `src/ffi/build_d.sh` file with the commands needed to build things on the D side. These should be moved into the `build.sh`
 * Everything was built/tested using the ldc/dmd versions from the Arch Linux repositories
    ```
    # ldc
    LDC - the LLVM D compiler (1.6.0):
      based on DMD v2.076.1 and LLVM 5.0.0
      built with DMD64 D Compiler v2.077.0
    # dmd
    DMD64 D Compiler v2.077.1 
    ```
 * Most of the regex is rather hackily parsed directly out of the Rust files on the D side at compile time, with some of the regex hard coded on the D side where it's anything but a string literal. It's probably easier/quicker to hard code it, but that's not what I did.
 * All the misc benchmarks run, most of sherlock runs (still some work to do), I haven't tested regexdna
 * Documentation for D's std.regex is here: https://dlang.org/phobos/std_regex.html

I'm happy to answer any questions to help this along, if I can.

**Comment by BurntSushi** [comment]
@mrmonday I just wanted to chime in and say thanks so much for doing this. I do actually plan on grabbing that branch and finding a way to get it merged. From the looks of it, I may omit the compile time regexes though, particularly after your findings that it wasn't much of an improvement.
