### ISSUE TITLE
Adding Deref for convenience to Match

### ISSUE THREAD

**Issue by hellow554** [rust-lang/regex#434]
When first working with this regex create I was confused, that I couldn't use match as a string, but have to call `as_str`/`as_bytes` by hand. 

My idea would be now to derive from [Deref](https://doc.rust-lang.org/std/ops/trait.Deref.html) and just call the methods mentioned above. 

What do you think? Is this feasible and practical? Do you have any concerns?

If you would like to see this feature, I'd love to contribute and implement this.

**Comment by BurntSushi** [comment]
Thanks for the request. I have certainly thought about it, but ultimately believe it is a misuse of deref. I would encourage you to read its documentation: https://doc.rust-lang.org/std/ops/trait.Deref.html --- In particular, it explicitly says that deref should only be implemented by smart pointers.

I do think there is grey area. For example, mutex guards impl deref, but I wouldn't consider them smart pointers.

Match it's not a smart pointer, and it isn't anything like a mutex guard either.

**Comment by hellow554** [comment]
You actually can argue, that it is a "smart pointer", because it's holding it's information inside and encapsulates it. 
It's totally up to you and you decision, but I would find it very convenient to implement Deref.

**Comment by BurntSushi** [comment]
You can certainly make that argument, but I'm not sure I buy it. A Match, conceptually, is a container that describes a single match of a regular expression. I don't see how you could call that a smart pointer.

@rust-lang/libs What do you think about implementing Deref on regex::Match?

**Comment by sfackler** [comment]
This is definitely not a smart pointer situation. Mixing normal string methods with `.start()` and `.end()` seems like it'd be a bit weird/confusing IMO.

**Comment by BurntSushi** [comment]
Aside from agreeing that deref impl isn't appropriate on its own, the lifetime mismatch seals the deal. This ain't happening.
