### ISSUE TITLE
escape into a formatter

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/regex#435]
Currently, `escape` allocates a new string for its output. It's often the case that you want to use the output of `escape` in a larger string to specify the regex. It would be more convenient if the escaping method implements `Display` so it can be used directly in a format string without allocation. To get an allocated string, one can then always use the `to_string` method.

Suggested API:
```rust
struct Escape { ... }

impl Escape {
  fn new(text: &str) -> Self { ... }
}

impl Display for Escape { ... }
```

**Comment by BurntSushi** [comment]
I guess in principle I agree, but can you actually come up with a benchmark where this matters? I'd be surprised if you could.

**Comment by RReverser** [comment]
Alternatively, it could return an iterator like std library does for [`EscapeDefault`](https://doc.rust-lang.org/std/char/struct.EscapeDefault.html) and [`EscapeDebug`](https://doc.rust-lang.org/std/char/struct.EscapeDebug.html).

**Comment by BurntSushi** [comment]
If someone can give me a good use case for avoiding allocation for something like this, then I'd be happy to revisit an API like this. But otherwise I don't think it's worth doing.
