### ISSUE TITLE
running regex compiler under valgrind causes it to panic

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang/regex#460]
This is baffling to me, but simple to reproduce. Note that I've (AFAIK) switched to using the system allocator, since I think that's necessary to make any sensible use of valgrind:

```rust
#![feature(alloc_system)]

extern crate alloc_system;
extern crate regex;

use regex::Regex;

fn main() {
    let re1 = {
        Regex::new(r"^5.5.5-(\d{1,2})\.(\d{1,2})\.(\d{1,3})-MariaDB").unwrap()
    };

    println!("{:?}", re1);
}
```

Compiling and running the program in debug and release mode works as expected:

```
$ cargo build
$ ./target/debug/regex-panic
^5.5.5-(\d{1,2})\.(\d{1,2})\.(\d{1,3})-MariaDB
$ cargo build --release
$ ./target/release/regex-panic
^5.5.5-(\d{1,2})\.(\d{1,2})\.(\d{1,3})-MariaDB
```

But running either of the above under valgrind causes a segfault:

```
$ valgrind ./target/debug/regex-panic > debug-valgrind.log 2>&1
Segmentation fault (core dumped)
$ valgrind --tool=massif ./target/debug/regex-panic > debug-valgrind-massif.log 2>&1
Segmentation fault (core dumped)
$ valgrind ./target/release/regex-panic > release-valgrind.log 2>&1
Segmentation fault (core dumped)
$ valgrind --tool=massif ./target/release/regex-panic > release-valgrind-massif.log 2>&1
Segmentation fault (core dumped)
```

I've attached the outputs of each of the above command to this issue. See below. (I enabled `debug = true` for `profile.release` to make output better, but I did confirm that the error occurs even without that.)

I'm not sure exactly what's going on. Is this is a false positive? To the best of my knowledge, there is zero unsafe in the regex library in the code path exercises here. (regex does use unsafe in places, but all of those places occur during match time.)

cc @alexcrichton 

[debug-valgrind.log](https://github.com/rust-lang/regex/files/1845475/debug-valgrind.log)
[debug-valgrind-massif.log](https://github.com/rust-lang/regex/files/1845476/debug-valgrind-massif.log)
[release-valgrind.log](https://github.com/rust-lang/regex/files/1845477/release-valgrind.log)
[release-valgrind-massif.log](https://github.com/rust-lang/regex/files/1845478/release-valgrind-massif.log)

**Comment by BurntSushi** [comment]
I originally found this thanks to @shepmaster pinging me on https://stackoverflow.com/questions/49475104/why-does-connecting-to-mysql-in-rust-crash-when-executed-via-massif

**Comment by alexcrichton** [comment]
I've seen this as well recently but I think it's specifically related to jemalloc, if you switch to the system allocator I think that it will help?

**Comment by shepmaster** [comment]
> if you switch to the system allocator

Is there another way than what is already shown in the first comment?

> Note that I've (AFAIK) switched to using the system allocator

**Comment by shepmaster** [comment]
One thing to highlight is that the program isn't just randomly crashing, it's panicking:

```
index out of bounds: the len is 29 but the index is 102854846', /checkout/src/libcore/slice/mod.rs:871:14
```

@BurntSushi can you try to see if `RUST_BACKTRACE` shows anything useful?

**Comment by shepmaster** [comment]
One of the [comments on SO](https://stackoverflow.com/questions/49475104/why-does-connecting-to-mysql-in-rust-crash-when-executed-via-massif#comment85958446_49475104) says:

> I wouldn't be too surprised if tools such as this made C-centric assumptions that do not hold for Rust. I remember having problems with 0-sized types for example (which C doesn't allow). 

That type of thing might still be here even when using a different allocator.

You could try running with [nulgrind](http://valgrind.org/docs/manual/nl-manual.html) to see if the problem is just by running it in the harness.

**Comment by BurntSushi** [comment]
@alexcrichton AFAIK, the code I pasted does use the system allocator. :)

**Comment by alexcrichton** [comment]
Oh dear, sorry about that, I misunderstood!

Unfortunately that's not actually using the system allocator, the newer syntax for that nowadays is:

```rust
#![feature(global_allocator, allocator_api)]

use std::heap::System;

#[global_allocator]
static A: System = System;

fn main() {
    // use allocator ...
}
```

**Comment by BurntSushi** [comment]
@alexcrichton OK, thanks for that! Switching that causes valgrind to be happy (with and without `--tool=massif`), so that's a relief!

The full code is here:

```rust
#![feature(allocator_api, global_allocator)]

extern crate regex;

use std::heap::System;

use regex::Regex;

#[global_allocator]
static A: System = System;

fn main() {
    let re1 = {
        Regex::new(r"^5.5.5-(\d{1,2})\.(\d{1,2})\.(\d{1,3})-MariaDB").unwrap()
    };

    println!("{:?}", re1);
}
```
