### ISSUE TITLE
Naming of use_std feature

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/regex#474]
The [C-FEATURE](https://rust-lang-nursery.github.io/api-guidelines/naming.html#c-feature) guideline discourages calling a Cargo feature `"use_std"`. I would recommend `"std"` instead.

**Comment by BurntSushi** [comment]
Funnily enough, I was using `std`, but switched to `use_std` just before the release because it's what `libc` uses.

I think this can be done in a backwards compatible way, but we'd need to keep `use_std` around. Not sure whether I prefer just `use_std` or having both...

**Comment by ethanpailes** [comment]
Personally I would rather have just one way to do it. Small api surface and all that.
