### ISSUE TITLE
Regex(Set)Builder: option to create regexes that match the whole string?

### ISSUE THREAD

**Issue by vthriller** [rust-lang/regex#475]
I'm aware this is something that can be easily worked around; I'm just creating this issue wondering whether a feature in question, if implemented, would even be useful performance-wise. Say, could something like

```rust
RegexSetBuilder::new(regexes)
    .whole_string(true)
    .build()?
    .is_match("whatever")
```

potentially be faster than

```rust
RegexSet::new(
    regexes.map(|r| format!("^{}$", r)
)?.is_match("whatever")
```

?

**Comment by BurntSushi** [comment]
No, I don't think so. The cost of the latter over the former is merely a single allocation. Compared to what the regex compiler is doing behind the scenes, it's peanuts.
