### ISSUE TITLE
Using version `1.0.0`, without default features, fails with compile error  [edited:  not an issue]

### ISSUE THREAD

**Issue by cipriancraciun** [rust-lang/regex#481]
[Not sure if this is an issue indeed, or a small "feature request".]

----

As the subject says, trying to use the `regex` crate version `1.0.0`, without the default features, and with the latest nightly (2018-05-18) fails with the following compile time error:

````
error[E0432]: unresolved import `Error`
  --> /home/ciprian/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.0/src/compile.rs:25:5
   |
25 | use Error;
   |     ^^^^^ no `Error` in the root. Did you mean to use `error`?

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
````

The way I include the dependency is:
````
[dependencies.regex]
version = "~1.0.0"
optional = true
features = []
default-features = false
````

----

It seems that with the `default-features = true` and without any additional features enabled, it succeeds.  On further investigation it seems that requiring (without default features) just `use_std` succeeds, which is in fact the default.

If the crate does require that one always use `use_std`, then perhaps a compile time error would be helpful, like for example:

````
#[ cfg ( not ( feature = "use_std" ) ) ]
compile_error! ("`use_std` feature is currently required to build this crate");
````

**Comment by BurntSushi** [comment]
This is intentional, as documented in the [changelog](https://github.com/rust-lang/regex/blob/master/CHANGELOG.md#100-2018-05-01).

I don't think I knew about the existence of `compile_error!`. PRs are welcome. :-)

**Comment by cipriancraciun** [comment]
Pull request done:  https://github.com/rust-lang/regex/pull/482

----

Regarding the changelog, indeed it is listed there exactly as it happens...  However I guess not many read the changelogs of all their dependencies...  (Indeed this is an "user" error, but to the "user" defense, there are so many dependencies these days...)  :)
