### ISSUE TITLE
regex_syntax: "dot" gets printed as \x00-\t\x0b-\U0010ffff

### ISSUE THREAD

**Issue by d33tah** [rust-lang/regex#498]
Consider the following code:

```
extern crate regex_syntax;

use regex_syntax::Parser;



fn main() {
    let s = "(?P<filename>.*)/(?P<extension>.csv.gz)";
    let hir = Parser::new().parse(s).unwrap();
    println!("{}", hir);
}
```

And the terminal output:

```
$ cargo run | python -c "print(repr(open('/dev/stdin').read()))"
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/nienawidzezycia`
'(?P<filename>[\x00-\t\x0b-\U0010ffff]*)/(?P<extension>[\x00-\t\x0b-\U0010ffff]csv[\x00-\t\x0b-\U0010ffff]gz)\n'
```

This looks strange in terminal and I worry that it might be sematically different. Is there a reason not to use a dot instead of \x00-\t\x0b-\U0010ffff here?

**Comment by BurntSushi** [comment]
This is precisely the intended behavior. You're printing the HIR, not the AST. The AST will likely have a format that is more friendly to humans. Compare and contrast the documentation for the [AST printer](https://docs.rs/regex-syntax/0.6.1/regex_syntax/ast/print/struct.Printer.html) and the [HIR printer](https://docs.rs/regex-syntax/0.6.1/regex_syntax/hir/print/struct.Printer.html), for example.

> I worry that it might be sematically different

If it is, then there's a bug. The intent of HIR's printer is to provide a means to build a regular expression after mutating the HIR.

> Is there a reason not to use a dot instead of `\x00-\t\x0b-\U0010ffff` here?

The HIR doesn't know about `.`: https://docs.rs/regex-syntax/0.6.1/regex_syntax/hir/enum.HirKind.html
