### ISSUE TITLE
Dead link to regex-syntax in documentation

### ISSUE THREAD

**Issue by theindigamer** [rust-lang/regex#505]
For this line:

https://github.com/rust-lang/regex/blob/6b342fc768d643fddd677b109f8e36fd54252399/src/lib.rs#L290

Clicking on the corresponding link from the `docs.rs` page leads to:

https://docs.rs/regex/1.0.2/regex_syntax/index.html

which says "The requested resource does not exist". Perhaps the docs didn't get generated for that crate? I'm guessing this is an upstream issue but I thought better report it here first ...

**Comment by BurntSushi** [comment]
I think it probably needs to be an absolute link to `https://docs.rs/regex-syntax` instead.
