### ISSUE TITLE
Using both regex-0.2 and 1.0

### ISSUE THREAD

**Issue by Marwes** [rust-lang/regex#518]
I unfortunately have a public (optional) dependency on regex-0.2 [in combine](https://github.com/Marwes/combine/issues/188) which prevents me from depending on 1.0 now without a major version bump. If the [semver trick](https://github.com/dtolnay/semver-trick) were employed to create a `regex-1` crate I would be able to support both however.

Is this something that `rust-lang/regex` would want to create/maintain in crate or do you find it unnecessary and I need to create a `combine-regex-1` crate myself to solve the problem?

**Comment by BurntSushi** [comment]
I don't think I want to be on the hook for this, honestly. I've come across the semver trick used before (I think with `rand`? or `log`?) and honestly found it pretty annoying with respect to managing the minimum Rust version---although I admit it does nicely solve other, perhaps more important, problems. With that said, enough time has passed I think where I don't think that would be a blocking issue for me personally (AIUI, applying the semver trick to regex 0.2 will increase its minimum Rust version in a patch release). Mostly, I just don't want the added maintenance burden of dealing with this for just one crate. If there was an ecosystem wide pain, then I could reconsider, but I don't think that's the case.

**Comment by Marwes** [comment]
I figured I were probably the only having this issue (but without asking you never know). I aren't in any rush so I may just let it be for a little just in case there is actually someone else with this issue but I will probably just end up publishing a `combine-regex-1` crate (which I can probably forget about after that, at least until I can do a breaking release).

> (AIUI, applying the semver trick to regex 0.2 will increase its minimum Rust version in a patch release)

What do you mean? As far as what I need, only a `regex-1` crate is necessary so `regex:0.2` should be completely unaffected? (There could be ` regex-0.2` crate for completeness but that seems excessive).

**Comment by Marwes** [comment]
Woops, didn't realize that https://github.com/dtolnay/semver-trick were only about the more advanced re-exporting trickery. I only need https://github.com/serde-rs/legacy

**Comment by Marwes** [comment]
Solved this for my needs by doing a one of publish of a crate re-exporting regex-1 https://crates.io/crates/combine-regex-1
