### ISSUE TITLE
Support `\ ` (backslash space) as equivalent to space, at least in /x mode

### ISSUE THREAD

**Issue by zackw** [rust-lang/regex#523]
The documentation for insignificant-whitespace mode says this:

> If you wish to match against whitespace in this mode, you can still use `\s`, `\n`, `\t`, etc. For escaping a single space character, you can use its hex character code `\x20` or temporarily disable the x flag, e.g., `(?-x: )`.

Most other regex engines that support /x mode (and in particular Perl, which invented it) accept `\ ` (backslash space) as equivalent to space _and_ treat it as significant within /x mode.  This can be significantly more readable than either of the alternatives supported by Rust, compare

    Regex.new(r"(?x)When\ in\ the\ course\ of\ human\ events")

    Regex.new(r"(?x)When\x20in\x20the\x20course\x20of\x20human\x20events")

And it would also ease porting code from other languages if Rust supported this.

**Comment by BurntSushi** [comment]
Could you please provide a program that reproduces the undesirable behavior? `\ ` is already supported when `x` mode is enabled. See: https://play.rust-lang.org/?gist=32be08ffca301141e19037e296767725&version=stable&mode=debug&edition=2015

**Comment by BurntSushi** [comment]
See also: https://github.com/rust-lang/regex/issues/501#issuecomment-427826260

**Comment by zackw** [comment]
> Could you please provide a program that reproduces the undesirable behavior? `\ ` is already supported when x mode is enabled.

I was just going by the documentation.  Please consider this a request to change the documentation so it says `r"(?x)When\ in\ the\ course\ of\ human\ events"` will indeed behave the same way `/When\ in\ the\ course\ of\ human\ events/x` would in Perl.  (If you want to continue _recommending_ the use of `\x20` instead, that's fine by me.)
