### ISSUE TITLE
Crash on using this crate as Nginx module

### ISSUE THREAD

**Issue by yaa110** [rust-lang/regex#526]
I am developing a dynamic module for Nginx based on [this example](https://github.com/nginxinc/ngx-istio-mixer). A `so` file is generated to be loaded in Nginx config file. However `Regex::new` causes a crash in dynamic module when it is called.

**Comment by BurntSushi** [comment]
Can you please provide more details and a minimal reproducible example? Why did you close this issue? If you fixed it, can you please share how you fixed it?

**Comment by yaa110** [comment]
The problem was because of difference between build and load environments. The module was build on Ubuntu to be used in Arch Linux. However, this crate works fine. 
Thank you
