### ISSUE TITLE
Panic in regex_syntax, found by fuzzing

### ISSUE THREAD

**Issue by PaulGrandperrin** [rust-lang/regex#527]
While fuzzing the `regex_syntax` target from https://github.com/rust-fuzz/targets, I hit this panic:
```
thread 'main' panicked at 'tried to unwrap expr from HirFrame, got: Group { old_flags: None }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-syntax-0.6.2/src/hir/translate.rs:203:18
```
Here is the regex:
```rust
regex::Regex::new("(((?x)))");
```

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=57f41973342d58bd032feafe8601f234)

**Comment by BurntSushi** [comment]
Nice! It looks like `((?x))` also panics. `(?:(?x))` does as well. As does `((?x))x`.
