### ISSUE TITLE
Add unicode license for the unicode tables in regex-syntax

### ISSUE THREAD

**Issue by erickt** [rust-lang/regex#530]
We noticed that regex-syntax uses tables derived from unicode 11, but the license files don't include a reference to the [unicode terms of use](http://www.unicode.org/copyright.html). Could this be added? Thanks so much!

**Comment by BurntSushi** [comment]
In principle this sounds fine to me. But I don't actually know what the requirements are here though. What, specifically, is needed? Reading your link, I don't think I see any requirement to link to those terms of use? Moreover, it's not clear to me whether data _derived_ from Unicode's tables falls under those terms of use.

**Comment by dgonyeo** [comment]
We need the license terms around that data to be clear, and the unicode terms of use state that their data can be modified and distributed only if their copyright and permission notice appears with "all copies
of the Data Files or Software", or is "in associated Documentation".

(I'm assuming derived == modified here, I'm not a lawyer though)

**Comment by dgonyeo** [comment]
I guess the root of this is the question "did the data [in this directory](https://github.com/rust-lang/regex/tree/master/regex-syntax/src/unicode_tables) come from the unicode consortium"? If not, great. If it did, we'd love it if you could include that license. I can make a pull request to add it if that helps.

**Comment by BurntSushi** [comment]
It did. A PR would be welcome.
