### ISSUE TITLE
Add support for begin match and end match

### ISSUE THREAD

**Issue by hauleth** [rust-lang/regex#539]
`regex` do not support arbitrary look-arounds, but it would be helpful for tools like Ripgrep to support "start match" and "end match". This feature is available in Vim via `\zs` and `\ze` flags and basically is equivalent of group but just ignore everything outside it.

So (assuming the same flags like in Vim):

```rust
let re = Regex::new(r"f\zs[aeiou]{2}\zes").unwrap();
let text = "foos, faas, fees";
for cap in re.captures_iter(text) {
    println!("{}", &cap[0]);
}
```

would be the same as:

```rust
let re = Regex::new(r"f([aeiou]{2})s").unwrap();
let text = "foos, faas, fees";
for cap in re.captures_iter(text) {
    println!("{}", &cap[1]);
}
```

**Comment by BurntSushi** [comment]
I'm not sure I'm convinced of this feature. As you point out, this is easily solved with a capturing group. So why do we need additional constructs for it?
