### ISSUE TITLE
Possibility of splitting substring replacement functionality out as its own crate?

### ISSUE THREAD

**Issue by 8573** [rust-lang/regex#543]
How feasible and sensible would it be to split out `regex`'s [substring replacement functionality](https://docs.rs/regex/1.1.0/regex/struct.Regex.html#replacement-string-syntax) as a small crate, providing functionality for replacing the placeholders in a string such as `"Hello, ${title} ${name}"` with some mapping from keys such as `"title"` and `"name"` to replacement strings?

It doesn't seem like that much to re-implement if one wanted to, but I think it would be nice to guarantee that the replacement syntax is the same (and not duplicate code).

**Comment by BurntSushi** [comment]
Sorry, I missed this issue in my email. Could you please describe a use case for this?

Note that I do have this functionality duplicated in a separate crate, `grep-matcher`, as part of its [`Captures` trait](https://docs.rs/grep-matcher/0.1.1/grep_matcher/trait.Captures.html#method.interpolate).

I'm not particularly inclined to split this out into even more granular crates, so I would really like to see a compelling use case for this.

**Comment by BurntSushi** [comment]
I think it would be better if you either copied the implementation or re-implemented it from the API or use the grep-matcher crate. If there's an undocumented corner case, then we should update the docs.
