### ISSUE TITLE
Provide "infallible" numeric-parsing for captures

### ISSUE THREAD

**Issue by BatmanAoD** [rust-lang/regex#550]
This is a feature request that is mostly just for ergonomics, but could hypothetically permit some good optimizations as well.

When matching against text that includes string-representations of numeric data, the regex patterns used in matching *should* guarantee that the capture groups are valid stringified numbers. For instance, given this pattern:

    \w+ : (\d{1,5})$

...a valid match will always have exactly one capture, and that capture will correspond to an integer with at most five decimal digits. This is guaranteed to be a valid positive numeric value within the range of 32-bit and larger integer types.

But, given a valid `Captures` generated from this regex called `c`, the simplest way to parse the integer as `u32` (and `panic` on failure, since this should be an infallible operation) seems to be:

        c.get(1).unwrap().as_str().parse::<u32>().unwrap()

It would be nice if there were some way to guarantee (either at Regex-compile time, or, ideally, at Rust-compile time) that, for a given pattern, a particular capture group (1) will exist if there is a match (avoiding the first `unwrap`), and (2) that it can be parsed as a numeric type (avoiding the second `unwrap`). Given these guarantees, it would be nice to have an ergonomic way to actually do that parsing.

Guaranteeing the capture-group index would of course be easier with const-generics, so that may be out of the question for now. But providing a limited version of this feature that would help with many or most typical cases might not be too bad, e.g.:

* Create a new `ValueRegex<T>` struct representing a compiled regex pattern with *exactly one* capture-group representing a numeric type, where `T` is the numeric type
   * A pessimistic validation of the capture-group pattern should be fine, at least for now. For instance, there could be some simple rules permitting a small number of "permissible" patterns for a given `T`.
   * The most flexible/robust solution would probably be to use T::FromString somehow, but I think that would require modifying the actual regex syntax. For instance, it could be something like:

          r"foo: (?V<u32>)$"
     ... where `?V<T>` is used to indicate that the capture-group content corresponds to a string representation of type `T`. The `ValueRegex<T>` type would internally contain something like a compiled version of the pattern `foo: (.+?)$`, and matching would be a two-step process wherein, following a successful regex match, `T::FromStr` would be used to attempt to parse the group `(.+?)`; if the parse is successful, the value is saved internally, and if not, the entire match fails.
* `ValueRegex<T>` could implement mostly the same interface as `Regex`, but in addition it would have:
       fn find_value(&self, text: &'t str) -> Option<T>      // This will *only* fail if `text` does not contain the pattern!

Using it would look something like:

    let RE = ValueRegex::<u32>::new(r"\w+ : (\d{1,5})$").unwrap();
    some_function(RE.find_value("foo: 243\n")?);

**Comment by BatmanAoD** [comment]
(If I'm overlooking a much simpler method for parsing numeric data using the existing regex tools, please let me know!)

**Comment by BurntSushi** [comment]
> When matching against text that includes string-representations of numeric data, the regex patterns used in matching *should* guarantee that the capture groups are valid stringified numbers. For instance, given this pattern:
>
>    \w+ : (\d{1,5})$
> 
> ...a valid match will always have exactly one capture, and that capture will correspond to an integer with at most five decimal digits. This is guaranteed to be a valid positive numeric value within the range of 32-bit and larger integer types.

This is not quite correct. `\d` is Unicode aware, so it matches quite a few more character than `[0-9]`. Instead, you'd need to write `[0-9]`, `(?-u:\d)` or `[[:digit:]]`.

> But, given a valid `Captures` generated from this regex called `c`, the simplest way to parse the integer as `u32` (and `panic` on failure, since this should be an infallible operation) seems to be:
>
>        c.get(1).unwrap().as_str().parse::<u32>().unwrap()

I don't think that's what I'd write. Instead, I'd write this:

```rust
let num: u32 = c[1].parse().unwrap();
```

I would encourage you to prototype your idea in a separate crate. I don't think any of your proposed solutions are a good fit for this library.
