### ISSUE TITLE
[feature] access to detailed error

### ISSUE THREAD

**Issue by lovasoa** [rust-lang/regex#562]
Currently, the [Error](https://docs.rs/regex/1.1.2/regex/enum.Error.html) type is very simplistic. It contains only a pre-formated error message for syntax errors. It is not possible to extract the position of the syntax error in the input string, nor to format the error message in any other way than the default (in particular, it is not possible to have a one-line error message). 

It would be great if the error type exposed the position of the error, and some kind of `ErrorKind` enumeration.

**Comment by BurntSushi** [comment]
The error is intentionally opaque, and I don't see this changing.

If you need very specific error details, then you can use the [`Error` type in the `regex-syntax` crate](https://docs.rs/regex-syntax/0.6.5/regex_syntax/enum.Error.html). You should be able to stitch together a custom error message with the span information and the `Display` impls on the various `ErrorKind`s.

**Comment by lovasoa** [comment]
> The error is intentionally opaque, and I don't see this changing.

Could you give more details ? I can't see why allocating a string and storing an english-language error message would be preferred over returning an error that would weigh just a few bytes and would allow this crate's users to define custom behaviors ? 

Am I missing something ?

**Comment by BurntSushi** [comment]
> I can't see why allocating a string and storing an english-language error message would be preferred over returning an error that would weigh just a few bytes

Because the error type is defined inside `regex-syntax` and `regex-syntax` is specifically not a public dependency of the `regex` crate. It's not a public dependency so that the two crates can evolve independently.

The `regex` crate could redefine the entire error enum that is already defined in the `regex-syntax` crate, but I see no good reason to do that.

> would allow this crate's users to define custom behaviors ?

Could you please explain why you can't use `regex-syntax` to do this?

**Comment by lovasoa** [comment]
> Could you please explain why you can't use regex-syntax to do this?
I could, but it simply feels like a convoluted way to do things. 

> The regex crate could redefine the entire error enum that is already defined in the regex-syntax crate, but I see no good reason to do that.
Maybe the `regex` crate could also provide an optional span specifying where the error is, and a general error kind. And it does not need to allocate a string.

Plus, the string that gets generated contains ASCII art to display the error span, which makes it difficult to use in many different contexts (and really useless if we cannot guarantee it will be displayed in a mono font).

**Comment by BurntSushi** [comment]
> I could, but it simply feels like a convoluted way to do things.

Why?

> Maybe the regex crate could also provide an optional span specifying where the error is, and a general error kind. There is a range of possibilities, and I understand that re-exporting everything from regex-syntax may be extreme, but it seems that a single string is the opposite extreme.
>
> Plus, the string that gets generated contains ASCII art to display the error span, which makes it difficult to use in many different contexts (and really useless if we cannot guarantee it will be displayed in a mono font).

I don't see it as extreme at all. I'd be willing to guess that 99.999% of the time, the error message is being viewed inside a terminal with a monospace font.

Exporting additional error information is plausible, but I'd rather see work for that done in `regex-syntax` first. Then we can pick and choose what to expose in `regex`, if anything.

**Comment by BurntSushi** [comment]
N.B. One thing I would be potentially open to exposing in the `regex` crate is a way to get a "one line error message." I could see that being useful, and it's a high level enough operation that I don't think it would be a maintenance burden or a liability. It would probably need a bit of API design though.
