### ISSUE TITLE
Method to expose named_groups

### ISSUE THREAD

**Issue by volfco** [rust-lang/regex#563]
I have a use case where I want to be able to directly read the named_groups HashMap of a capture group.

```rust
   Compiling playground v0.0.1 (/playground)
error[E0616]: field `named_groups` of struct `regex::Captures` is private
  --> src/main.rs:15:20
   |
15 |     println!("{}", caps.named_groups["year"]);
   |                    ^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

I need to get the field names from the parsed regex to feed into a template (both the template and regex are dynamic), and unless I missed something in the documentation, I can't do that.

**Comment by BurntSushi** [comment]
This request has insufficient data and it's not actionable, sorry.

Firstly, could you please explain why you can't use [capture_names](https://docs.rs/regex/1.1.2/regex/struct.Regex.html#method.capture_names)?

Secondly, the mere existence of a use case isn't enough justification to expose an API. Please elaborate with more details on your specific use case, and in particular, describe the problem you're trying to solve *at a high level*.

**Comment by volfco** [comment]
That works. Didn't realize that was an option.

Thanks!
