### ISSUE TITLE
Problem with match iteration

### ISSUE THREAD

**Issue by ArekMiszcz** [rust-lang/regex#564]
## Expected Behavior

Fist match:
1. :test(\\d+)?
2. test
3. \\d+
4. ?

Second match:
1. :asd(\\d+)?
2. asd
3. \\d+
4. ?

## Actual Behavior

1. ":test(\\d+)?/auth/:asd(\\d+)?"
2. "test"
3. "\\d+)?/auth/:asd(\\d+"
4. ?

## Steps to Reproduce the Problem

```
let path_regexp: Regex = Regex::new(vec![
    // Match escaped characters that would otherwise appear in future matches.
    // This allows the user to escape special characters that won't transform.
    r"(\\.)",
    // Match Express-style parameters and un-named parameters with a prefix
    // and optional suffixes. Matches appear as:
    //
    // ":test(\\d+)?" => [":test(\\d+)?", "test", "\d+", None, "?"]
    // "(\\d+)"  => ["(\\d+)", None, None, "\d+", None]
    r"(?::(\w+)(?:\(((?:.|[^()])+)\))?|\(((?:\\.|[^\\()])+)\))([+*?])?"
].join("|").as_str()).unwrap();

for caps in path_regexp.captures_iter("/auth/:test(\\d+)?/auth/(\\d+)") {
    println!("{:#?}", caps);
}
```

## Online example:

[https://regex101.com/r/ssMlg9/1](https://regex101.com/r/ssMlg9/1)

**Comment by BurntSushi** [comment]
Please provide a smaller example. I can't make sense of this and don't have time to. Sorry.

**Comment by ArekMiszcz** [comment]
@BurntSushi My bad, it works like a charm. Sorry
