### ISSUE TITLE
aho-corasick 0.7

### ISSUE THREAD

**Issue by ignatenkobrain** [rust-lang/regex#565]
Hello,

it would be great if you'd update aho-corasick dependency to 0.7. It was rewritten by @BurntSushi in https://github.com/BurntSushi/aho-corasick/commit/e8493baf54d0685d35c2e0a3bf4104717bdf0bd2

**Comment by BurntSushi** [comment]
Yes, I maintain the regex crate too. :-)

It just so happens that this time, upgrading should hopefully be fairly easy and it's next on my TODO list, but that may not always be the case.

**Comment by BurntSushi** [comment]
Fixed in #566
