### ISSUE TITLE
Contradicting Rust versions in README.md?

### ISSUE THREAD

**Issue by moreati** [rust-lang/regex#569]
The main README seems to contain some contradicting information about the minimum Rust version for this crate

[![Rust](https://img.shields.io/badge/rust-1.20%2B-blue.svg?maxAge=3600)](https://github.com/rust-lang/regex) 

indicates Rust 1.20

> and this to your crate root (if you're using Rust 2015)

indicates Rust 1.0(?)

> This crate's minimum supported rustc version is 1.24.1.

indicates Rust 1.24.

I believe, given https://github.com/rust-lang/regex/blob/master/CHANGELOG.md#110-2018-11-30, that the last one is correct. PR on the way, if no one objects.

**Comment by BurntSushi** [comment]
Nice catch, although the only thing that's wrong is the badge. I'm not sure where you got Rust 1.0 from.

**Comment by moreati** [comment]
> I'm not sure where you got Rust 1.0 from

I think I made 2 mistakes

1. I wrongly assumed that Rust worked like Python - minimum language version is determined by max(d.lang_ver for d in dependencies).
2. Rust 2015 equates to Rust 1.0
