### ISSUE TITLE
What if I wanna do some tasks that needs lookaround technique?

### ISSUE THREAD

**Issue by ParadoxZW** [rust-lang/regex#573]
For example, there is a `c` snippet:
```c
{int x=1+4/2+2019;x++;}
```
I want to insert whitespaces between operaters, numbers and variables, namely, change the string into
```c
{ int x = 1 + 4 / 2 + 2019 ; x ++ ; }
```
I haven't figured out how to implement this while I cannot use lookaround. I mean, there maybe a way to deal with the string above, but hardly deal with other arbitrary strings of  `c` snippets.

**Comment by BurntSushi** [comment]
Sorry, but there's not enough information for me to answer your question here, and in general, this issue tracker isn't the place to task for general regex help. Since you haven't provided much information, my natural answer here is "don't use a regex and perhaps consider using a real C parser."
