### ISSUE TITLE
AhoCorasickBuilder is not optimized

### ISSUE THREAD

**Issue by vlisivka** [rust-lang/regex#577]
I'm trying to improve `regexredux.rust-4.rust` at Benchmark Games, but, as I can see, AhoCorasickBuilder uses major share of the CPU. IMHO,  this is a bug.

```
[vlisivka@localhost src]$ cargo profiler callgrind --release <regexredux-input50000000.txt 

Compiling rust-regex-redux in release mode...

Profiling rust-regex-redux with callgrind...

Total Instructions...8,272,585

2,353,140 (28.4%) ???:aho_corasick::ahocorasick::AhoCorasickBuilder
-----------------------------------------------------------------------
740,239 (8.9%) ???:_int_malloc
-----------------------------------------------------------------------
681,110 (8.2%) ???:_int_free
-----------------------------------------------------------------------
458,461 (5.5%) ???:memcpy@GLIBC_2.2.5
-----------------------------------------------------------------------
369,736 (4.5%) ???:<aho_corasick::nfa::State<S>>
-----------------------------------------------------------------------
308,696 (3.7%) ???:malloc
-----------------------------------------------------------------------
240,444 (2.9%) ???:realloc
-----------------------------------------------------------------------
229,390 (2.8%) ???:aho_corasick::dfa::Builder::build
-----------------------------------------------------------------------
182,489 (2.2%) ???:free
-----------------------------------------------------------------------
172,837 (2.1%) ???:regex_syntax::hir::literal::Literals

```

**Comment by BurntSushi** [comment]
Sorry, but this bug report is not actionable. Please do not file bugs based simply on the output of a profile. Instead, provide a complete program that _clearly_ shows the performance bug.

In particular, if you run `perf`, then the profile results are completely different from your output, and I'm much more inclined to trust `perf` than I am callgrind:

![regex-redux-perf](https://user-images.githubusercontent.com/456674/56471273-a74abb80-641e-11e9-9d71-0957bec7de06.png)

Moreover, the results shown by `perf` are generally what I'd epxect. Most of the time is being spent in Teddy and iterating over matches.

> AhoCorasickBuilder is not optimized

That's wrong. It _is_ optimized. It's likely it could be micro-optimized a bit more, but generally speaking, its construction time will be dwarfed by search time and/or overall compilation time of a regex.

**Comment by vlisivka** [comment]
Here is the whole program. I converted it from bytes to strings and replaced macros by function, to make it less scary. I turned off unicode support (except for 3 regex'es). Currently, I'm out of ideas, while C version is about 30% faster. Any suggestions?

```rust
// The Computer Language Benchmarks Game
// https://salsa.debian.org/benchmarksgame-team/benchmarksgame/
//
// contributed by Tom Kaitchuck
// contributed by Volodymyr M. Lisivka

extern crate regex;
use regex::Regex;

use std::io::{self, Read};
use std::thread;

fn regex(re: &str) -> Regex {
    regex::RegexBuilder::new(re).unicode(false).build().unwrap()
}

fn count_reverse_complements(sequence: String) -> Vec<String> {
    // Search for occurrences of the following patterns:
    let variants = vec![
        "agggtaaa|tttaccct",
        "[cgt]gggtaaa|tttaccc[acg]",
        "a[act]ggtaaa|tttacc[agt]t",
        "ag[act]gtaaa|tttac[agt]ct",
        "agg[act]taaa|ttta[agt]cct",
        "aggg[acg]aaa|ttt[cgt]ccct",
        "agggt[cgt]aa|tt[acg]accct",
        "agggta[cgt]a|t[acg]taccct",
        "agggtaa[cgt]|[acg]ttaccct",
    ];
    variants
        .iter()
        .map(|variant| {
            format!(
                "{} {}",
                variant,
                regex(variant).find_iter(&sequence).count()
            )
        })
        .collect()
}

fn find_replaced_sequence_length(sequence: String) -> usize {
    // Replace the following patterns, one at a time:
    let substs = vec![
        ("tHa[Nt]", "<4>"),
        ("aND|caN|Ha[DS]|WaS", "<3>"),
        ("a[NSt]|BY", "<2>"),
        ("(?u)<[^>]*>", "|"),
        ("(?u)\\|[^|][^|]*\\|", "-"),
    ];
    let mut seq = sequence;

    // Perform the replacements in the sequence:
    for (re, replacement) in substs {
        seq = regex(re).replace_all(&seq, regex::NoExpand(replacement)).into_owned();
    }
    seq.len()
}

fn main() {
    // Read whole input into String.
    let mut input = String::new();
    io::stdin().read_to_string(&mut input).unwrap();
    let input_len = input.len();

    // Erase comments, e.g. '>ONE Homo sapiens alu', and new line symbols.
    let sequence = regex("(?u)>[^\n]*\n|\n")
        .replace_all(&input, regex::NoExpand(""))
        .into_owned();

    // Length of cleared input.
    let clen = sequence.len();

    // Create copy of the input to perform replacements at.
    let seq_clone = sequence.clone();

    // Run two functions in separate threads, because they are independent.
    let result = thread::spawn(|| find_replaced_sequence_length(seq_clone));
    let counts = thread::spawn(|| count_reverse_complements(sequence));

    // Print results
    for variant in counts.join().unwrap() {
        println!("{}", variant)
    }
    println!("\n{}\n{}\n{:?}", input_len, clen, result.join().unwrap());
}
```

**Comment by BurntSushi** [comment]
> Any suggestions?

Nothing simple, no. I'm pretty sure you can't micro-optimize your way out of this one. In particular, none of your changes should really have any impact, and in particular, switching to strings is likely to make things slower since you end up needing to do a UTF-8 validation check on the input for no good reason.

The path to glory on this particular benchmark is likely a clever optimization in the regex engine. In particular, this benchmark, IIRC, iterates over a fair number of matches. For each match, the regex engine must scan the matched text in reverse to find the starting location of the match, where as PCRE2 does not (since it's a backtracking engine). This additional scan, IIRC, is a key reason for the performance difference. Figuring out how to remove this scan is non-trivial and it's not clear to me that it's possible. The regex engine internals are not amenable to it, so not only would I not want to attempt this until the internals have been refactored to be more flexible to particular types of optimizations, but I'd also want to see a good argument for why the complexity is worth it. Scoring a few points on the benchmark game on ancient hardware isn't enough.

It is possible you might be able to make up the match overhead somewhere else, but I'm not sure where. Maybe making Teddy faster is the path to glory. Not sure. You also might consider figuring out how to benchmark on the same hardware used by the game, since optimizations like Teddy depend on specific CPU features that might not be available in the game.

Of course, I could be wrong about all of this and maybe there is something simple. But you asked for my suggestions, and these are my current opinions based on my recollection.

**Comment by vlisivka** [comment]
Yep, Unicode support slows down code by about 1/40. Not a big deal for me, while code looks much cleaner.

Yep, I currently sittings at my parents Core2 Duo.

I had success with minor change to `binary-trees`. Now it faster than C.

As I see, most of the time reredux program spends at replace. When I commented out call to `count_reverse_complements()`, execution time dropped by about 5%. Here is report for `perf -F 99 -g `:

```
+   49,12%    49,12%  rust-regex-redu  rust-regex-redux    [.] <regex::re_trait::Matches<'t, R> as core::iter::traits::iterator::Iterator>::next  
+   13,33%    13,33%  rust-regex-redu  libc-2.26.so        [.] __memcpy_ssse3                                               
+    9,27%     9,27%  rust-regex-redu  rust-regex-redux    [.] regex::literal::teddy_ssse3::imp::Teddy::find_impl           
+    8,10%     0,00%  rust-regex-redu  [unknown]           [.] 0x0000000000000001                                           
+    7,56%     7,56%  rust-regex-redu  rust-regex-redux    [.] regex::re_unicode::Regex::replace_all                        
+    5,25%     0,00%  rust-regex-redu  [unknown]           [.] 0x4347475447474347                                           
```

It looks like code can be improved a bit by spending less on copying of data and by grouping of multiple regex-es into single regex with a smart closure, which will return correct replacement for a match.

**Comment by BurntSushi** [comment]
> and by grouping of multiple regex-es into single regex with a smart closure

It is not obvious to me that this change would be accepted by the game maintainer, but you can try.
