### ISSUE TITLE
Cannot Compile in Rust 1.36.0 Nightly

### ISSUE THREAD

**Issue by pnfcre** [rust-lang/regex#581]
Hi there,

Operating System: `Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux`
Rustc Version: `rustc 1.36.0-nightly (37ff5d388 2019-05-22)`
Cargo Version: `cargo 1.36.0-nightly (c4fcfb725 2019-05-15)`

```
   Compiling regex-syntax v0.6.6
error: failed to compile `vigil-server v1.9.0`, intermediate artifacts can be found at `/tmp/cargo-installWlu03T`

Caused by:
  Could not compile `regex-syntax`.

Caused by:
  process didn't exit successfully: `rustc --crate-name regex_syntax /root/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-syntax-0.6.6/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C opt-level=s -C metadata=ccda77ecd63c6781 -C extra-filename=-ccda77ecd63c6781 --out-dir /tmp/cargo-installWlu03T/release/deps -L dependency=/tmp/cargo-installWlu03T/release/deps --extern ucd_util=/tmp/cargo-installWlu03T/release/deps/libucd_util-f229009622233513.rlib --cap-lints allow` (signal: 9, SIGKILL: kill)
```

Many thanks!

Kind regards,
Casper.

**Comment by BurntSushi** [comment]
It compiles just fine. Please look at your error messages. In particular, note the `(signal: 9, SIGKILL: kill)` that appears at the end. The most likely explanation for that, in my experience, is that the compiler was killed by your operating system for trying to use too much memory. Either way, this isn't a problem with this crate.

**Comment by ralyodio** [comment]
I'm getting this too. how to fix?
