### ISSUE TITLE
"Unrecognized escape sequence" in Clippy

### ISSUE THREAD

**Issue by ThomasdenH** [rust-lang/regex#584]
I opened https://github.com/rust-lang/rust-clippy/issues/4170 and was to open an issue here. The escaped backslash is not recognized:

```
error: regex syntax error: unrecognized escape sequence
   --> src/compiler/utilities.rs:187:52
    |
187 |         static ref RE: Regex = Regex::new("^..?($|[\\/])").unwrap();
    |                                                    ^^
    |
    = note: #[deny(clippy::invalid_regex)] on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#invalid_regex
```

**Comment by ThomasdenH** [comment]
Apparently it needs to be escaped twice, which makes sense.

**Comment by BurntSushi** [comment]
Glad you figured it out. Note that the [first example in the docs](https://docs.rs/regex/1.1.6/regex/#example-find-a-date) specifically mentions this issue. In particular, you might consider using raw strings.
