### ISSUE TITLE
match character `ſ` \u017f for `s` character with case-insensitive flag

### ISSUE THREAD

**Issue by 2fd** [rust-lang/regex#587]
Hi, I'm doing a web tool to execute rust regular expressions and when I evaluate `(?i)[a-z]` in the range appear the character `ſ` (`\u017f`)
https://2fd.github.io/rust-regex-playground/#method=syntax&regex=%28%3Fi%29%5Ba-z%5D&text=s%C5%BF

The character match with the expression
https://2fd.github.io/rust-regex-playground/#method=find&regex=%28%3Fi%29%5Ba-z%5D%2B&text=123abc%C5%BF

And only appear when the `s` is in the group
* `(?i)s`:  https://2fd.github.io/rust-regex-playground/#method=syntax&regex=%28%3Fi%29s
* `(?i)[a-rt-z]`: https://2fd.github.io/rust-regex-playground/#method=syntax&regex=%28%3Fi%29%5Ba-rt-z%5D

I'm not  completely sure if this is a bug because something similar happens with the `k` that match with three characters (`\u004b`, `\ u006b`,  `\u212a`)
https://2fd.github.io/rust-regex-playground/#method=syntax&regex=%28%3Fi%29k

Is this the expected behavior?

Thanks

**Comment by BurntSushi** [comment]
Yes, it's correct, according to the Unicode simple case folding rules: http://unicode.org/reports/tr18/#Simple_Loose_Matches

Here's the table: ftp://ftp.unicode.org/Public/UNIDATA/CaseFolding.txt

And the relevant entry for `s` in particular:

```
017F; C; 0073; # LATIN SMALL LETTER LONG S
```

If you want to use only ASCII case rules, then disable Unicode mode: https://2fd.github.io/rust-regex-playground/#method=syntax&regex=%28%3Fi-u%29%5Ba-z%5D&text=s%C5%BF

Relevants docs are https://docs.rs/regex/1.1.7/regex/#unicode
