### ISSUE TITLE
overlapping pattern

### ISSUE THREAD

**Issue by dongweigogo** [rust-lang/regex#590]
Does this package support overlapping searching like finditer(patter, overlapped=True) in python package regex?

**Comment by BurntSushi** [comment]
Please provide more detail. I don't see any support for overlapping matches in Python's regex library: https://docs.python.org/3/library/re.html Please provide links, and, ideally a code sample.

**Comment by dongweigogo** [comment]
@BurntSushi  Sorry for that, [here is the link ](https://pypi.org/project/regex/), and please refer:

> ‘Overlapped’ argument for regex.findall and regex.finditer
regex.findall and regex.finditer support an ‘overlapped’ flag which permits overlapped matches.

**Comment by BurntSushi** [comment]
I asked you for a code sample so that I can understand what problem you're trying to solve. But you didn't give me one. As far as I can tell, strictly speaking, no, overlapping matches are not and will never be supported. However, some use cases may be aptly covered by `RegexSet`, which does permit overlapping matches to a degree.

**Comment by expenses** [comment]
Not sure if I should bump this but I have a use case for overlapping patterns. I'm writing a library for 2d pattern matching similar to what https://github.com/mxgmn/MarkovJunior does. This requires finding all overlapping patterns like `\0\0`. It's not very obvious how I should be doing this without overlapping patterns.

**Comment by BurntSushi** [comment]
@expenses Code examples would help. If it's just literals like `\0\0`, then you should be able to use the `aho-corasick` crate.

If you do need overlapping regex matches, then some of the low level APIs in `regex-automata` support it. Feel free ask Discussion questions about it.
