### ISSUE TITLE
return both capture group name and location?

### ISSUE THREAD

**Issue by aohan237** [rust-lang/regex#596]
the doc says about how to get capture group names,  and use find fn to get the capture location.

but what should we do if we want both group names and locations? 

it seems there is no such method

**Comment by BurntSushi** [comment]
The [`Regex::capture_names`](https://docs.rs/regex/1.1.9/regex/struct.Regex.html#method.capture_names) method returns an iterator over all capturing groups, where the `Option<&str>` element yielded is non-None precisely when there is a name. If you want a location associated with a name, then use the name to look it up upon a successful match.

**Comment by aohan237** [comment]
@BurntSushi 
i just use re.captures to get capture_names() . 
and in order to get location , i make another cap use re.find_iter(), to get these locations.
in order to do this, i will have to make **two** capture.

`If you want a location associated with a name, then use the name to look it up upon a successful match.`
how this can do it?

**Comment by BurntSushi** [comment]
Sorry, I don't understand. Please provide code and describe, at a high level, the problem you're trying to solve.

**Comment by aohan237** [comment]
`
let re = Regex::new(r"'(?P<title>[^']+)'\s+\((?P<year>\d{4})\)")
               .unwrap();

let text = "Not my favorite movie: 'Citizen Kane' (1941).";
let caps = re.captures(text).unwrap();
assert_eq!(caps.name("title").unwrap().as_str(), "Citizen Kane");
assert_eq!(caps.name("year").unwrap().as_str(), "1941");
assert_eq!(caps.get(0).unwrap().as_str(), "'Citizen Kane' (1941)");
`
how can i get <title>'s  location.

in order to get the location. 

i have to make another captures: such as:
`
let re = Regex::new(r"'(?P<title>[^']+)'\s+\((?P<year>\d{4})\)")
               .unwrap();
let text = "Not my favorite movie: 'Citizen Kane' (1941).";
let mat = re.unwrap().find(text).unwrap();
let start_location = mat.start()
let end_location = mat.end()
`
and use mat.start() and mat.end() to get the right locations

so my question is how can i get the capture group names and the correspond locations in just one action.
