### ISSUE TITLE
Alternative of PREG_OFFSET_CAPTURE

### ISSUE THREAD

**Issue by bcashier** [rust-lang/regex#600]
Hi,

Is there any alternative in RUST to:

```php
preg_match_all('/(^|;|\})(\w+)\|/i', $encodedData, $matchesarray, PREG_OFFSET_CAPTURE);
```

And return datas like this:

```php
foreach ($matchesarray[2] as $value) {
    ....
}
```

Note that I am using PHP in this examples.

If I can get a similar result with this crate it will be awesome :)

Thank you in advance.

**Comment by BurntSushi** [comment]
Could you please explain why [examples in the docs](https://docs.rs/regex/1.1.9/regex/#example-iterating-over-capture-groups) aren't sufficient to answer this question?

If the examples do not answer your question, then please provide a more specific question. Leave PHP code out of it. Specify your input and expected output, please.

**Comment by bcashier** [comment]
@BurntSushi I can't get the same result as PHP.

Here what I tried with your crate:

```rust
fn decodeit (encodedData: &'static str) {
	if encodedData.is_empty() {
		return ();
	}
    let re = Regex::new(r"/(^|;|\})(\w+)\|/i").unwrap();
	let decodedData = ();
	let lastOffset = 0;
	let currentKey = "";

    for value in re.captures_iter(encodedData) {
        println!("{:?}", value);
    }

}
```
The goal is to decode and unserialize this string:

```rust
decodeit (r#"number|i:1;test|s:6:"string";array_number|a:2:{i:0;i:1;i:1;i:2;}array_string|a:2:{i:0;s:5:"arr 1";i:1;s:5:"arr 2";}"#);
```

> number|i:1;test|s:6:"string";array_number|a:2:{i:0;i:1;i:1;i:2;}array_string|a:2:{i:0;s:5:"arr 1";i:1;s:5:"arr 2";}

This regex in action online: https://regex101.com/r/AP1DuQ/1

But using your crate, I haven't got no result unfortunatelly :( or for sure I am doing something wrong with it.

**Comment by bcashier** [comment]
@BurntSushi I can't get the same result as PHP.

Here what I tried with your crate:

```rust
fn decodeit (encodedData: &'static str) {
    if encodedData.is_empty() {
	return ();
    }
    let re = Regex::new(r"/(^|;|\})(\w+)\|/i").unwrap();
	let decodedData = ();
	let lastOffset = 0;
	let currentKey = "";

    for value in re.captures_iter(encodedData) {
        println!("{:?}", value);
    }

}
```
The goal is to decode and unserialize this string:

```rust
decodeit (r#"number|i:1;test|s:6:"string";array_number|a:2:{i:0;i:1;i:1;i:2;}array_string|a:2:{i:0;s:5:"arr 1";i:1;s:5:"arr 2";}"#);
```

> number|i:1;test|s:6:"string";array_number|a:2:{i:0;i:1;i:1;i:2;}array_string|a:2:{i:0;s:5:"arr 1";i:1;s:5:"arr 2";}

This regex in action online: https://regex101.com/r/AP1DuQ/1

But using your crate, I haven't got no result unfortunatelly :( or for sure I am doing something wrong with it.

**Here is the expected result:**

`array(4) { ["number"]=> int(1) ["test"]=> string(6) "string" ["array_number"]=> array(2) { [0]=> int(1) [1]=> int(2) } ["array_string"]=> array(2) { [0]=> string(5) "arr 1" [1]=> string(5) "arr 2" } } `

**Comment by BurntSushi** [comment]
Please consider reading the examples a bit more closely. Writing a regex as `/.../i` is a PHPism probably copied from Perl. Exactly none of the examples in the `regex` docs use `/.../i` to write a regex.

Here's your code with warnings and the regex fixed: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f800364615d9657a4c48a1c23635f4ca

**Comment by bcashier** [comment]
@BurntSushi 

What about the offset, how to get it inside the FOR LOOP please ?

As well as the current key used ?

Thank you again

**Comment by bcashier** [comment]
Expected offsets are as follow:

```
offset: 0

offset: 10

offset: 21

offset: 39

offset: 74
```

The first one is defined as ZERO.

**Comment by BurntSushi** [comment]
Again, **please consider reading the documentation**: https://docs.rs/regex/1.1.9/regex/struct.Captures.html#method.get

I still don't know what you're trying to do, and these offsets do not match yours, but extracting the offsets from a particular capturing group is trivial: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=11dc8ef288cfacc5307ff831e9224e52

**Comment by BurntSushi** [comment]
From what I can see, those offsets are correct given the regex you wrote and the input it is being matched on.

**Comment by bcashier** [comment]
@BurntSushi You are right !!!

The same result exatly you found !

Many thanks sir for your help, really appreciated :)

Since you are asking, I want just to convert a PHP function into Rust fn.

```PHP
function decodeit($encodedSessionData)
{
    if ('' === $encodedSessionData) {
        return [];
    }
    preg_match_all('/(^|;|\})(\w+)\|/i', $encodedSessionData, $matchesarray, PREG_OFFSET_CAPTURE);
    $decodedData = [];
    $lastOffset = null;
    $currentKey = '';
    foreach ($matchesarray[2] as $value) {
        $offset = $value[1];
        if (null !== $lastOffset) {
            $valueText = substr($encodedSessionData, $lastOffset, $offset - $lastOffset);
            $decodedData[$currentKey] = unserialize($valueText);
        }
        $currentKey = $value[0];
        $lastOffset = $offset + strlen($currentKey) + 1;
    }
    $valueText = substr($encodedSessionData, $lastOffset);
    $decodedData[$currentKey] = unserialize($valueText);
    return $decodedData;
}```
