### ISSUE TITLE
Could not compile regex_syntax on Alpine Linux

### ISSUE THREAD

**Issue by a1730** [rust-lang/regex#619]
cargo install sonic-server on Alpine Linux failed generating an error:  Sonic[#180](https://github.com/valeriansaliou/sonic/issues/180#issue-501482954) due to a regex dependency with the following message:
`error: Could not compile `regex-syntax`.

Caused by:
  process didn't exit successfully: `rustc --crate-name regex_syntax /home/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-syntax-0.6.12/src/lib.rs --color always --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="unicode"' --cfg 'feature="unicode-age"' --cfg 'feature="unicode-bool"' --cfg 'feature="unicode-case"' --cfg 'feature="unicode-gencat"' --cfg 'feature="unicode-perl"' --cfg 'feature="unicode-script"' --cfg 'feature="unicode-segment"' -C metadata=207ac757e1db3de0 -C extra-filename=-207ac757e1db3de0 --out-dir /tmp/cargo-installCJU94z/release/deps -L dependency=/tmp/cargo-installCJU94z/release/deps --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `sonic-server v1.2.2`, intermediate artifacts can be found at `/tmp/cargo-installCJU94z`
`
The sonic team suggested that I seek support from this team.
Any pointers for escaping this trap? Sorry, I do not speak rust.

**Comment by BurntSushi** [comment]
Sorry, but I'm not sure why you were referred here. It sounds like this is the compiler that is failing itself. Which isn't a problem in regex-syntax itself.

One thought you might consider is whether you have enough memory to build sonic. How much ram do you have?

Otherwise, you will need to report this against Rust itself or Cargo. Not sure which. You might want to attach a debugger and get a stacktrace.

**Comment by a1730** [comment]
Thank you for the pointer to memory/host resources.
FWIW: I was able to build sonic on a **one** processor box with 4GB of memory but build failed on a **four** processor box with 4GB of memory. I wish I know more about rust compile workflow. It probably would have been sufficient to do serial (non-parallel) build.
I'll make a note to the sonic team too.
Thank you for the speedy response.

**Comment by BurntSushi** [comment]
You could try setting `--jobs 1` when running `cargo build`. But yes, it makes sense that doing a parallel build will use more memory.

> I was able to build sonic on a one processor box with 4GB of memory but build failed on a four processor box with 4GB of memory.

This is an important detail. You should definitely include it in any subsequent issues you file.

**Comment by a1730** [comment]
Thank you for the followup.
It seems to be a memory issue. I was able to compile sonic without issues on a four (4) processor box with 16GB of memory. Problem solved.
