### ISSUE TITLE
Add a macro to reduce the lazy_static boilerplate

### ISSUE THREAD

**Issue by Canop** [rust-lang/regex#621]
The documentation recommends the use of `lazy_static`. This makes for quite a heavy code and it often breaks the reading flow:

```
fn some_helper_function(text: &str) -> bool {
    lazy_static! {
        static ref RE: Regex = Regex::new("...").unwrap();
    }
    RE.is_match(text)
}
```

Compare this to other languages where regular expressions are built-in.

I think a macro could make using regexes in rust more enjoyable:

```
fn some_helper_function(text: &str) -> bool {
    regex!("...").is_match(text)
}
```

It could be named otherwise, for example `lazy_regex!`, if we want to keep `regex!` for when we also get compile-time regex compilation.

An implementation of the macro could be this (thanks Shepmaster for the fix):

```
macro_rules! regex {
    ($s: literal) => {{
        lazy_static! {
            static ref RE: Regex = Regex::new($s).unwrap();
        }
        &*RE
    }};
}
```

A downside is that it adds a dependency but lazy_static has virtually no cost and is already advocated in the documentation.

A variant that I didn't investigate would be to wrap the call to `RegexBuilder` instead and allow flags in the construct.

**Comment by BurntSushi** [comment]
I appreciate the request, but I 1) do not want to add a dependency on `lazy_static!` and 2) I am holding out hope that [`once_cell`](https://crates.io/crates/once_cell) will supplant `lazy_static!`. The only reason I haven't migrated everything to it yet (including the docs) is because it requires a bit newer version of Rust that I haven't moved to.

My take is that if you are bothered by the use of `lazy_static!`, then I'd advise just defining your own macro for this.

**Comment by shepmaster** [comment]
> I am holding out hope that [`once_cell`](https://crates.io/crates/once_cell) will supplant `lazy_static!`

In such a world, would you implement a macro that uses `once_cell`, or does the dependency concern still reign?

**Comment by BurntSushi** [comment]
Not sure. Adding a dependency would still be a concern, although it could be behind a feature gate I suppose. The other issue here is that the API suggested hides an `unwrap`. [Some related discussion on that.](https://github.com/rust-lang/regex/issues/450) Another concern is really whether this "should" be in the domain of the regex library itself. I think it's reasonable to ask folks to compose crates like this, although I don't feel that strongly and certainly see the value in coupling.
