### ISSUE TITLE
\/ Causes panic

### ISSUE THREAD

**Issue by Parth** [rust-lang/regex#624]
Was attempting to parse some urls for: https://github.com/Parth/broken-links

[Here](https://github.com/Parth/broken-links/blob/master/src/main.rs#L37) the initial regex I used was: 
`https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)`

 but it panics due to `\/`. It works fine as:

`https?://(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)`

**Comment by BurntSushi** [comment]
It does not cause a panic. Using `\/` causes an error to be returned, and your use of unwrap converts that to a panic. Please understand that this is very different than a panic inside the library.

The error it's correct and expected behavior.

**Comment by Parth** [comment]
You're right, sorry about that
