### ISSUE TITLE
Unexpected `SetMatches::len()` behavior

### ISSUE THREAD

**Issue by EFanZh** [rust-lang/regex#625]
The document explains [`SetMatches::len()`](https://docs.rs/regex/latest/regex/struct.SetMatches.html#method.len) as “the total number of regexes in the set that created these matches”.

At first sight, I thought `SetMatches` as a collection of matched regular expression indices, so naturally, I expect the following function to always return `true`:

```rust
fn f(s: &SetMatches) -> bool {
    s.len() == s.iter().count()
}
```

But it seems that this method always returns the number of all regular expressions in the corresponding `RegexSet` object, not the number of matched regular expressions.

I think the name of `len()` strongly suggests that it is consistent with the behavior of `iter()`, maybe it’s better to rename this method or add a better explanation to reduce confusion.

**Comment by BurntSushi** [comment]
I probably agree that `len` and `iter` should be consistent. But I'm not going to rename it since this change on its own is not worth a breaking change release. I think just adding better docs is good enough here.

**Comment by BurntSushi** [comment]
In looking over past issues, I stumbled on this one and realized that there is no `iter()` method. So the premise of the problem described in this issue seems wrong.

**Comment by EFanZh** [comment]
I see there is a `SetMatches::iter` method: <https://docs.rs/regex/1.5.4/regex/struct.SetMatches.html#method.iter>.

**Comment by BurntSushi** [comment]
Oh, whoops. I did not re-read the issue closely enough.

I think the fix here is to clarify the docs. If I could do it over, I'd choose different names.

**Comment by ickk** [comment]
I hit this :( 

> If I could do it over, I'd choose different names.

Perhaps a different name could be chosen as an alias to the `len` method, and then `#[deprecated]` could be added to `len` itself? This would avoid the semver breaking-change, while still making letting some cleanup effectively happen.
