### ISSUE TITLE
need \xc0\xa8\x02\x17 meaning for the regular expression

### ISSUE THREAD

**Issue by manojt193** [rust-lang/regex#626]
ansi_re = TerminalBase.ansi_re
ansi_re.append(re.compile(br'\xc0\xa8\x02\x17'))
I need the meaning of the regular expression can any one crack the code for me.

\xc0\xa8\x02\x17

**Comment by BurntSushi** [comment]
Sorry, but this ticket doesn't make any sense to me. The code you've posted isn't Rust code, so it's impossible for me to answer your question.
