### ISSUE TITLE
Bad error message on multi-byte unicode ranges 

### ISSUE THREAD

**Issue by valarauca** [rust-lang/regex#629]
[rust playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b443a7de3049bd9365659f7ac227555b)

When given a regular expression of the format:

```
[\x2B740-\x2B81D]
```

It will state that the range is erroneous, and `0x2B740` is greater than `0x2B81D`. 

This appears _wrong_ as `0x2B81D` is greater than `0x2B740`, but I think the issue is related to the `\x` syntax only expects 2 characters, where I'm providing multiple. 

---

```
[\u0002B740-\u0002B81D]
```

Will present similar error messages. 

---

The code opperates correctly with

```
[\U0002B740-\U0002B81D]
```

But nothing seems to _guide the user_ to the `\U` vs `\x` vs `\u` decision when specifying code points.

**Comment by BurntSushi** [comment]
It's a good point, and it would be nice to improve the error message here, but I don't see how to do it without making the parser quite a bit more complex. Also, you don't need to use `\U` here. You can do `\x{2B740}` instead. This is documented here: https://docs.rs/regex/1.3.1/regex/#escape-sequences and here: https://github.com/rust-lang/regex/blob/master/UNICODE.md#rl11-hex-notation

**Comment by valarauca** [comment]
> It's a good point, and it would be nice to improve the error message here, but I don't see how to do it without making the parser quite a bit more complex

Could `\x`, `\u`, and `\U` just be compared identically as they're parsed identically?

**Comment by BurntSushi** [comment]
Sorry, can you say more words? I don't understand your suggestion.

Also, it's worth pointing out that the actual error message includes positional information pointing to what it thinks the start and end ranges are. That is, the error message is saying that `0` is not less than or equal to `\x2B`, which is correct (since `0 == 0x30`).

**Comment by valarauca** [comment]
> Sorry, can you say more words? I don't understand your suggestion.

Currently the parser accepts `\u`, `\x`, and `\U` data which is malformed, the error is confusing. Creating error messages specific to these character class prefixes is unneeded work. 

So, why not remove the different semantics in casting and comparison allowing for `\\[uUx][0-9a-fA-F]{2,8}` to just be a generalized input, for any character class prefix (e.g.: `\x`, `\u`, and `\U`). It appears the parser is already accepting these patterns, but under validation & semantic analysis the error we're discuss appears. 

In this manner the number of special cases are reduced within the validation & semantic analysis step. 

So instead of having a special hard to add error message, the patterns become valid inputs who are handled in an identical fashion during validation.

**Comment by BurntSushi** [comment]
That would be a breaking change.

**Comment by valarauca** [comment]
Cool.
