### ISSUE TITLE
Custom word boundary

### ISSUE THREAD

**Issue by elbaro** [rust-lang/regex#630]
I am trying to solve a very simple task:
Finding all space-separated occurrences of `@[a-z]+` in a string.

1. `\b@[a-z]+\b` - close to what I want, but since '@' is not a word character, '\b@' has a different meaning.
2. `\<@[a-z]+\>` - I don't want to match `+@aa+`.
3. `(\A\s)@[a-z]+(\z\s)` - This requires at least 2 spaces between matches. It only finds one match from `@a(space)@b`. Also `regex` has no overlapping matches.
4. `(?<=\A|\s)(@[a-z]+)(?=\z|\s)`  - Lookahead. Working, but `regex` doesn't support it.

- Is there a workaround?
- Since `regex` already supports `\b`, I believe it's possible to support the custom word bounary without increasing the time complexity. There is simply no interface to tell `regex` about the custom boundary. This can be a useful addition as a compensation for the lack of lookahead and overlapping matches.

**Comment by BurntSushi** [comment]
Thanks for the good issue. Just a few points up front:

1. If you really want to use look-around, then the solution there is to use a crate that supports it, such as `fancy-regex` or `pcre2`.
2. As such, I don't see a good reason to further complicate `regex` by supporting custom look-arounds.
3. Personally, unless I were using regex for some other good reason, I probably wouldn't use it for something like this.

Regardless, it's usually pretty straight-forward to drop the look-around if you're willing to do a tiny amount of extra work. Just treat your regex as something that can produce false positives and add an extra step to determine whether you have a true positive or not:

```rust
use regex::Regex;

fn main() {
    let haystack = "@foo testing a@wrong @bar  @also@wrong  testing @quux";
    
    let find = Regex::new(r"(\A|\s)@(?P<at>[a-z]+)").unwrap();
    
    for cap in find.captures_iter(haystack) {
        let candidate = cap.name("at").expect("at must match for all matches");
        if is_at(haystack, candidate.end()) {
            println!("{:?}", candidate.as_str());
        }
    }
}

fn is_at(haystack: &str, end: usize) -> bool {
    haystack[end..].chars().next().map_or(true, |c| c.is_whitespace())
}
```

Output:

```
"foo"
"bar"
"quux"
```

Playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=15346a949abcf91d3e34c8d4456daf4b
