### ISSUE TITLE
Regex parse error when try to match string literals "{{xxx}}"

### ISSUE THREAD

**Issue by bofeng** [rust-lang/regex#632]
My code in Python works like this:

```python
>>> content = "{{ static_prefix }}/home/js/asdf.js";
>>> a = re.compile("{{\\s*static_prefix\\s*}}");
>>> a.sub("/static", content)
'/static/home/js/asdf.js'
```

If I code the same logic with regex crate,

```rust
use regex::Regex;

fn main() {
    let content = "{{ static_prefix }}/home/js/asdf.js";
    let reg = Regex::new("{{\\s*static_prefix\\s*}}").unwrap();
    println!("{}", reg.replace(content, "/static"));
}
```

I got error:
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
regex parse error:
    {{\s*static_prefix\s*}}
    ^
error: repetition operator missing expression
```

But if I escape {{ with backslash, it works:
```rust
use regex::Regex;

fn main() {
    let content = "{{ static_prefix }}/home/js/asdf.js";
    let reg = Regex::new("\\{\\{\\s*static_prefix\\s*\\}\\}").unwrap();
    println!("{}", reg.replace(content, "/static"));
}
```

I tried in Python and Go, to match this string, I don't need to escape `{{` and `}}`, but with this regex crate in Rust, I need to put the extra escape, otherwise I got the above "parse error", regex can't compile.

Is this a bug?

**Comment by ethanpailes** [comment]
Regular expressions are not generally portable across different regex libraries, and compatibility with other regex implementations is an explicit non-goal of this crate, so I don't think this is a bug.

**Comment by BurntSushi** [comment]
Also, I would suggest using raw strings. You won't need to escape the backslashes.

**Comment by bofeng** [comment]
@BurntSushi I need to read this regexp string from a configuration file, can't create a raw string directly, but thank you for the suggestion.
Also @ethanpailes thank you for the explanation.
