### ISSUE TITLE
CI failure: cargo fmt --all -- --check

### ISSUE THREAD

**Issue by danielparks** [rust-lang/regex#634]
CI is failing on PRs in `cargo fmt --all -- --check`, [for example](https://travis-ci.com/rust-lang/regex/jobs/257680677). Affected files include:

* tests/bytes.rs
* tests/consistent.rs
* tests/crazy.rs
* tests/unicode.rs

Files generated by ucd-generate:

* regex-syntax/src/unicode_tables/property_bool.rs
* regex-syntax/src/unicode_tables/script.rs
* regex-syntax/src/unicode_tables/script_extension.rs

Generated scripts/regex-match-tests.py:

* tests/fowler.rs

**Comment by BurntSushi** [comment]
I believe this has been fixed.
