### ISSUE TITLE
find all unnamed capture groups in user supplied regex

### ISSUE THREAD

**Issue by ZacEllis** [rust-lang/regex#635]
This may be a feature request, or a request for more explicit documentation if this is already possible. 

I'm looking for a way to find unnamed capture groups in user supplied regex. My use case is to extract useful values from a line of text and then dump the rest into an "other" column.

__Example:__
*Input:*  `An error occurred on Date: 21-09-2019, where 'calc.exe' crashed with error code 999`
*(user supplied) regex:* `(.*)Date: (?<date>\d+-\d+-\d+)where \'(?<name>[^'])'(.*)`
*Ideal output:*

| Date | Name | Other |
| --- | --- | --- |
| 21-09-2019 | calc.exe | "An error occurred on", "crashed with error code 999" |

__Code:__
```
let caps = re.captures(line);
let date = caps.name("date").unwrap();
let name = caps.name("name").unwrap();
let others = caps.unnamed().unwrap().collect();
```

**Comment by BurntSushi** [comment]
You should be able to do this pretty easily with the capture_names method: https://docs.rs/regex/1.3.1/regex/struct.Regex.html#method.capture_names

See also: https://docs.rs/regex/1.3.1/regex/struct.CaptureNames.html

I'm on mobile. Let me know if you want an example. Your example, or something like it, might be a good one to put in the docs.

**Comment by ZacEllis** [comment]
From what I can see, named captures can also be referenced by index. So you're saying I'd have to collect all captures, collect the named captures, and xor to get unnamed?

**Comment by BurntSushi** [comment]
Not sure I follow. Just collect the indices of all elements from the iterator that are None (sans the first one). Then use those indices on your Capture match.

**Comment by ZacEllis** [comment]
Ohhh, I'd completely missed in the docs that `.capture_names()` iterates over not just the named ones. My bad, that definitely solves my problem. Thanks! 

_May be worth adding to the docs of the fn, rather than just the struct, but I can also see the case for conciseness in leaving it out._
