### ISSUE TITLE
Way to check if a capture group is optional?

### ISSUE THREAD

**Issue by umanwizard** [rust-lang/regex#638]
I am working on a tool that based on a user-supplied regex outputs some relational data that can subsequently be queried with SQL. The columns in the relation come from the capture groups in the regex.

It would be nice to know whether a capture group is guaranteed to appear, in order to know whether a column in the relation is nullable.

For example, in the regex `(?P<foo_col>(?:foo)*)(?P<bars_col>(?:bar)+)?`, the `foo_col` capture group is guaranteed to exist (though it is possibly the empty string), whereas the `bar_col` capture group can be None.

Given a `regex::Regex`, it doesn't seem possible to iterate over its capture groups to see which are optional and which are not. Is this feature desirable/planned ?

**Comment by BurntSushi** [comment]
It is not planned and I'm not sure how exactly this would be implemented. I would recommend prototyping this in another crate (using regex-syntax) first.

**Comment by umanwizard** [comment]
@BurntSushi thanks for the suggestion to use regex-syntax.

I think something like this should work, unless I am missing something: https://gist.github.com/umanwizard/e9d7f619a98c032b671b910b1d812a4c

**Comment by BurntSushi** [comment]
I think it will work for a subset of regexes, yeah. But it doesn't account for alternations, e.g., `a|(b)`.

**Comment by umanwizard** [comment]
Yep, that was an oversight, but if we account for alternations (as in my edited update), it seems like it should work
