### ISSUE TITLE
Fail to match

### ISSUE THREAD

**Issue by Eraden** [rust-lang/regex#642]
I have following lines:

```
    + param1: baz (string, optional) - all inline option parameter
    + param2: no description (string, optional)
    + param3 (integer, required) - parameter without example
    + param4: true (required) - no type
    + param5: 23423 (enum[string], required) - enumerable
```

Each line is checked against following regex:

```regex
(?i)(?P<leading_white>\s+)\+\s+(?P<name>[\w\d_]+)(?:[:]\s+(?P<example>[\w\d ]+))?\s+(?:\(\s*(?P<param_type1>([\w\d]+)|enum\[[^]]+\])\s*,\s*(?P<req_opt1>required|optional)\)|\(\s*(?P<req_opt2>required|optional)\s*\)|\(\s*(?P<param_type2>[\w\d]+)\s*\))?(?:\s+\-\s+(?P<desc>[^\n]+)?)?
```

I checked this regex here: https://regex101.com/r/C9MTGi/1/

In theory it should match all 5 but example 3 is failing

**Comment by ethanpailes** [comment]
The rust `regex` crate doesn't have the exact same semantics and syntax as python's regex module, so the fact that that `regex101` link you shared matches, but rust's regex crate doesn't isn't necessarily evidence of a bug.

That regex is pretty long. Can you try to shrink it down to a smaller and easier to understand test case that better highlights the exact match semantics that you think this crate should have?

**Comment by BurntSushi** [comment]
@Eraden When filing bug reports, please **include a reproducible example** that others can compile and execute. Not doing this costs time and energy on our part, which isn't fair.

I did this for you and every single one of your subjects matches.

```rust
fn main() {
    let re = regex::Regex::new(r"(?i)(?P<leading_white>\s+)\+\s+(?P<name>[\w\d_]+)(?:[:]\s+(?P<example>[\w\d ]+))?\s+(?:\(\s*(?P<param_type1>([\w\d]+)|enum\[[^]]+\])\s*,\s*(?P<req_opt1>required|optional)\)|\(\s*(?P<req_opt2>required|optional)\s*\)|\(\s*(?P<param_type2>[\w\d]+)\s*\))?(?:\s+\-\s+(?P<desc>[^\n]+)?)?").unwrap();
    let subjects = &[
        "    + param1: baz (string, optional) - all inline option parameter",
        "    + param2: no description (string, optional)",
        "    + param3 (integer, required) - parameter without example",
        "    + param4: true (required) - no type",
        "    + param5: 23423 (enum[string], required) - enumerable",
    ];
    for &subject in subjects {
        println!("{:?}", re.is_match(subject));
    }
}
```

Output:

```
true
true
true
true
true
```

Playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d8caf6746fb87a913560be70b53ee9a7
