### ISSUE TITLE
Extra characters in capture groups

### ISSUE THREAD

**Issue by jhelwig** [rust-lang/regex#65]
Using the following with `rustc 1.0.0-nightly (d8be84eb4 2015-03-29) (built 2015-03-29)`, `regex 0.1.24`, and `regex_macros 0.1.14`:

```Rust
#![feature(collections)]
#![feature(plugin)]
#![plugin(regex_macros)]
extern crate regex;

fn main() {
    let user_input = String::from_str("0,2,3-5 15\n");
    let re = regex!(r"(?i)\s*([0-9]+(?:-[0-9]+)?)(?:\s*|,)");

    for cap in re.captures_iter(&user_input) {
        println!("Captured: {:?}", cap.at(0).unwrap_or(""));
    }
}
```

I get the expected output on every `println!`, except for the last two.  Neither the whitespace, nor the newline should be included in the capture group.

```
% ./test
Captured: "0"
Captured: "2"
Captured: "3-5 "
Captured: "15\n"
```

Switching the `\s*` in the `regex!` to `\b` matches as I would expect:
```Rust
    let re = regex!(r"(?i)\b([0-9]+(?:-[0-9]+)?)(?:\b|,)");
```

```
% ./test2
Captured: "0"
Captured: "2"
Captured: "3-5"
Captured: "15"
```

It looks like the `\s` in the non-capture group immediately following the capture group is leaking in?

**Comment by BurntSushi** [comment]
Per [the docs](http://doc.rust-lang.org/regex/regex/enum.Regex.html#method.captures):

> Capture group 0 always corresponds to the entire match. [..] Note that the full match is at capture group 0. Each subsequent capture group is indexed by the order of its opening (.

In other words, try using `cap.at(1)`. This is standard behavior across most (all?) regex libraries that I know of.

**Comment by jhelwig** [comment]
I scanned right past that, entirely in the "iterating over capture groups" [example](http://doc.rust-lang.org/regex/regex/index.html#example:-iterating-over-capture-groups) (also mentioned there).
