### ISSUE TITLE
unexpected byte matching behaviour: * not capturing 0x0a

### ISSUE THREAD

**Issue by alxiong** [rust-lang/regex#651]
I was using `regex` in another project and a frustrating, bizarre trail of debugging leads me to reproduce it here:

```rust
// Cargo.toml
// [dependencies]
// regex = "1"

use regex::bytes::Regex; 
fn main() {
    let re: Regex = Regex::new(r"(?-u)^.{4}").unwrap();
    let b1 = b"\xFF\xFF\xFF\xFF".to_vec();
    let b2 = b"\x0a\x0a\x0a\x0a".to_vec();

    let cap1 = re.captures(&b1);
    let cap2 = re.captures(&b2);

    println!("cap1: {:?}, cap2: {:?}", cap1, cap2);
    // output: cap1: Some(Captures({0: Some("\\xff\\xff\\xff\\xff")})), cap2: None
    // expected: both captures are not None
}
```

I thought `*` is supposed to match any `u8` (including UTF-8 invalid ones since we set the flag) value, and through experimentation with the code snippet above, 

`*` just doesn't match `0x0a`, and match every other `u8` value!! 😕

I'm confused. Did I miss anything? Thanks!

**Comment by BurntSushi** [comment]
As [documented](https://docs.rs/regex/1.3.4/regex/#syntax), `.` matches anything except a newline character. `0xA` is a newline character.

This is standard across every regex engine I know of. You can make `.` match newline characters by enabling the `s` flag.
