### ISSUE TITLE
Can't pass regexes as argument

### ISSUE THREAD

**Issue by denisidoro** [rust-lang/regex#654]
```rust
let re = Regex::new(r"^\d{4}-\d{2}-\d{2}$").unwrap();
```

It's impossible to pass the value above as argument to another function because `re`'s type is private

**Comment by ethanpailes** [comment]
I don't think that's true.

With a `src/main.rs` of:

```rust
extern crate regex;

fn main() {
    let re = regex::Regex::new("foo|bar").unwrap();
    accepts_regex(&re);
}

fn accepts_regex(re: &regex::Regex) {
    println!("{:?}", re.is_match("foo"));
}
```

`cargo run` prints "true".

**Comment by denisidoro** [comment]
Hmm I was misled by my IDE that said that the return type was `regex::re_unicode::Regex`. I'm sorry

**Comment by BurntSushi** [comment]
In the future, please provide a _complete_ program that can be compiled that demonstrates your problem.
