### ISSUE TITLE
[Wishlist] Consider adding a lazy-regex like macro to the regex crate

### ISSUE THREAD

**Issue by benwbooth** [rust-lang/regex#664]
I found a great crate called [lazy-regex](https://github.com/Canop/lazy-regex) which has a regex! macro that automatically uses lazy_static to create a Regex object to use in a single expression. It would be great to have something like this in the regex crate.

**Comment by BurntSushi** [comment]
Sorry, I missed this issue. I don't think it's a good fit. Users should just use `lazy_static` or `once_cell`.
