### ISSUE TITLE
impose a limit on the size of a compiled regex program

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang/regex#67]
From the docs:

> Currently, there are no counter-measures in place to prevent a malicious user from writing an expression that may use a lot of resources. One such example is to repeat counted repetitions: ((a{100}){100}){100} will try to repeat the a instruction 100^3 times. Essentially, this means it's very easy for an attacker to exhaust your system's memory if they are allowed to execute arbitrary regular expressions. A possible solution to this is to impose a hard limit on the size of a compiled expression, but it does not yet exist.

The conclusion of this is that regexes specified by a user cannot be blindly trusted, since they can trivially exhausted all memory on your system. We can fix this by imposing some limit on the size of a regex program. (In fact, this probably has to be a limit on the size of a regex AST, which will need to be checked during construction.)

**Comment by huonw** [comment]
The limit should be controllable?

**Comment by BurntSushi** [comment]
:+1:

**Comment by clarkmcc** [comment]
Is this limit adjustable? I've got some nasty regexs I'm trying to compile but am getting the `CompiledTooBig(10485760)` error.
