### ISSUE TITLE
Feature request: Regex::replace expand escape sequences

### ISSUE THREAD

**Issue by sidju** [rust-lang/regex#672]
I am writing an ed clone (as one does) and came across that escape sequences do not expand in the replacing text.

For example: replacing with pattern "\\\\n" and replacement "\\\\n" will replace all newlines with \\n

Expanding the replacement for escape sequences is a generally expected part of regex replace and should be easy to add.

**Comment by BurntSushi** [comment]
Could you please provide a sample Rust program along with expected output and actual output? I don't think I understand what you're asking for.

> Expanding the replacement for escape sequences is a generally expected part of regex replace

Is it? What other orogramming language regex engines so this?

**Comment by sidju** [comment]
I might just be spoiled by running regex in scripting languages but standard sed does it.

`
let s = "test\nlines";
let r = regex::Regex::new("\\n").unwrap();
assert_eq!(s, &r.replace(s, "\\n"));
`
Since this replaces "\\n" with "\\n" no change should be made, but different treatment of "\\n" causes all newlines ("\n") to be replaced with "\\n".

**Comment by BurntSushi** [comment]
sed isn't a programming language's regex engine though. It's a CLI tool. Writing a custom replacement syntax for a specialized tool seems completely reasonable to me.

I guess I understand your request, but:

1. I don't understand why you want it when one could just write `\n` instead.
2. It would be a breaking change with the current behavior.

So for (2) alone, I don't think this is happening. Sorry. I'd recommend implementing your own escaping syntax for replacements.

**Comment by sidju** [comment]
Fair enough. After looking you don't seem to currently do anything like that, so the work would be considerable.
Thank you for quick responses.

**Comment by BurntSushi** [comment]
A simple parser for escape sequences is certainly not "considerable" work. Here is a function that is less than one hundred lines that not only handles newline escapes but also hex escapes. It would be very easy to expand or contract it to whatever use case you want: https://github.com/BurntSushi/ripgrep/blob/a2e6aec7a4d9382941932245e8854f0ae5703a5e/crates/cli/src/escape.rs#L91

After unescaping you could then just apply the result using the existing replacement routines in this crate.

**Comment by sidju** [comment]
Thank you. I'll do something along those lines.
