### ISSUE TITLE
Utility function to parse a match?

### ISSUE THREAD

**Issue by djahandarie** [rust-lang/regex#674]
I find that I often write things like

```rust
let cs = MY_REGEX::captures(s)?;
cs.get(1)?.as_str().parse::<MyType>().ok()?
```

and would much rather write something like
```rust
let cs = MY_REGEX::captures(s)?;
cs.get_as::<MyType>(1)?
```

or at least

```rust
let cs = MY_REGEX::captures(s)?;
cs.get(1)?.as::<MyType>()?
```

Personally, no particular preference these things return Option vs Result, but I guess a Result which preserves the ParseError vs CaptureError would be best.

This is totally purely an ergonomic thing, but I'd definitely appreciate something like it directly in the library. Sorry if this is a duplicate!

Related: https://github.com/rust-lang/regex/issues/550

**Comment by BurntSushi** [comment]
I don't think this is a good fit for `regex`. I think the regex APIs should really remain focused on strings and not start down the road of adding conveniences. This also appears to require adding a new error type, such that getting a capture group would either be an `Option<Match>` or ` Result<Match, CaptureError>`, which seems not particularly orthogonal to me.

On top of all of that, in most cases, you don't actually need to use `Captures::get`. Instead, you can use `caps["foo"].parse()` or `caps[1].parse()`. So long as `foo` (or `1`) are guaranteed to match when the regex itself matches, then index access like this will never fail.

**Comment by djahandarie** [comment]
You're right, the `Index<&str>` implementation does actually make it perfectly fine.

I wonder, maybe that pattern should be mentioned in the `Captures::get` docs? I think it's sort of the usual fault of the rustdoc UI not really telling you much about implementations, but right now it's very easy to miss that.

**Comment by BurntSushi** [comment]
Pretty much every example using capturing groups in the regex docs uses the `caps["index"]` syntax. See https://docs.rs/regex/1.3.7/regex/struct.Regex.html#examples-1 for example.

I'd be happy to accept a PR that added more notes to this on the `get` method.
