### ISSUE TITLE
Matches: `skip_bytes` or `skip_until` method

### ISSUE THREAD

**Issue by llogiq** [rust-lang/regex#692]
If I want to ignore matches in a certain region of my text, I currently need to loop until `.next()` returns `None` or the `.start()` of the returned `Match` is outside the region. I believe that the regex crate could include a faster implementation of that operation that text-processing code could benefit from.

**Comment by BurntSushi** [comment]
Could you please provide an example? I don't understand what you're asking for here. If you already know the bounds of your region, then why can't you search only outside of that region?

More concrete details about the proposed API would also be helpful.

**Comment by llogiq** [comment]
Let's say I write an iterator that want to find certain things *outside of* the regions that a `Matches` returns. There is also another token that when found will invalidate all the `Match` results until a third token is found (I cannot go into too many details, but let's imagine we're finding quotes and then don't care what they contain).

Then on finding the start token, we want to update the `Matches` position to the next item after the end token. For now I do it like this:

```
while match_start < next_token {
      match = matches.next();
      if let Some(m) = match {
             match_start = m.start();
      } else {
             break;
      }
}
```
As far as I'm aware, none of PCRE, RE2, Oniguruma, Perl or python regexes have anything similar. I could alternatively construct a new Matcher with the reduced substring, but that would require me to keep track of the start position and possibly incur other overhead.

**Comment by RReverser** [comment]
> I could alternatively construct a new Matcher with the reduced substring, but that would require me to keep track of the start position and possibly incur other overhead.

The overhead here would most likely be lower than running regex engine on the parts of text you already know you're not interested in.
