### ISSUE TITLE
Match subpattern group (?P=name)

### ISSUE THREAD

**Issue by pleshevskiy** [rust-lang/regex#693]
Will there be support for match subpattern group? `(?P=name)`

It very useful in multipart for example:

```rust
const RE_MESSAGE: &str = r"(?x)
    Content-Type:\smultipart\/form-data;\sboundary=(?P<boundary>[-\w]+)
    [\s\S]+?(?:--(?P=boundary)
    ([\s\S]+?)(?=--(?P=boundary)))+
";
```

```
POST /form.html HTTP/1.1
Host: server.com
Referer: http://server.com/form.html
User-Agent: Mozilla
Content-Type: multipart/form-data; boundary=-------------573cf973d5228
Content-Length: 288
Connection: keep-alive
Keep-Alive: 300

---------------573cf973d5228
Content-Disposition: form-data; name="field"

text
---------------573cf973d5228
Content-Disposition: form-data; name="file"; filename="sample.txt"
Content-Type: text/plain

Content file
---------------573cf973d5228--
```

Thank you!

**Comment by BurntSushi** [comment]
From the first paragraph of the crate docs:

> This crate provides a library for parsing, compiling, and executing regular expressions. Its syntax is similar to Perl-style regular expressions, **but lacks a few features like look around and backreferences. In exchange, all searches execute in linear time with respect to the size of the regular expression and search text.**
