### ISSUE TITLE
PWA for Rust Regex Explanations and online Testing

### ISSUE THREAD

**Issue by LucianoBestia** [rust-lang/regex#702]
Please feel free to try it and catch the bugs, so I can finalize it.
https://bestia.dev/rust_regex_explanation_pwa/

I started to write this web-app that runs entirely in Wasm/WebAssembly. The goal is to make a PWA.
For the input fields: regex, substitution and test_string it calculates:
1. Regex explanation (human readable)
2. runs 6 Regex methods and shows the result
3. generates Rust code for use with Regex

It uses the Regex and Regex-syntax crates. 
So it is 100% accurate if you need to test a regex for your Rust Regex code.
The repository is here:
https://github.com/LucianoBestia/rust_regex_explanation_pwa

First decision - no frameworks. Then no javascript.
Some basic html. Some basic css.
All the rest is in Rust with web-sys/wasm-bindgen for all the programming needs.
No other special requirements. 
Very minimal example how to use Rust and Wasm.

**Comment by BurntSushi** [comment]
Neat! Thanks for the heads up. I think you'll have better luck with feedback if you post this to [r/rust](https://reddit.com/r/rust).
