### ISSUE TITLE
Reading regex from file

### ISSUE THREAD

**Issue by btv** [rust-lang/regex#706]
This ticket is more about seeking help than anything being wrong with the code. My current problem is that I'm trying to load the regex configuration string, but something seems to get lost. Here is the string I'm searching through:

```
"hs=1090488148; svSession=7f5774a77907540af3ac18850d8857ee00b3a2a7f8651155b10b649da43f3e99b63a34a629f6574d945d1dba1a4c0da31e60994d53964e647acf431e4f798bcd848063a691d03ee36db2be2e4e3d388709b9451e1f45ad79d0ff062fdec20fe7; XSRF-TOKEN=1597434272|rwf40R9-irIq; TS01e85bed=01f0e931315cda203d15b22c81131df340a525edb0fd0757577b3a9317a6ea0fc837737e0bf8b4314c8b2f4c0a0c6c52760640a564; TS015649a3=01f0e93131382668cacf8a70cde79be0d713686eb006fcfd4797bae0f1ca34b6e4ab6d322bdb14dfad16ef64db3ec611c8f82fdcf2; ssr-caching=\"cache#desc=miss#varnish=miss#dc#desc=42\"; bSession=b1b001fe-40ae-42fc-b9a4-87e270b94ac3|1"
```

I'm trying to extract the value of the `svSession` key. Using https://regex101.com/, I can confirm that `r"svSession=(\S+)'"`, works. I have also been able to confirm that `"svSession=(\\S+);` works (note: not a raw string). And both of these work well if in the function I created to create a instance of Regex:

```
fn create_regex() -> Regex {
    let regex1 = String::from("svSession=(\\S+);");
    let re1 = Regex::new(&regex1).expect("could not encode regex!");
    re1
}
```

My challenges come when I try to load regex1 from a file:

```
fn create_regex() -> Regex {
    let mut regex2 = String::new();
    let mut file = File::open("traffic.in").unwrap();
    file.read_to_string(&mut regex2).unwrap();
    let re2 = Regex::new(&regex2).expect("could not encode regex!");
    re2
}
```

The contents of "traffic.in" are the same as regex1, `svSession=(\\S+);`. The code above compiles fine, but Regex::captures, never sees the regex in the search string.

I've tried using `dbg!()` to print out both regex variables after they've been initialized to see if anything is different there, and its not. 

I'm not sure what is going wrong, but any help with this would be greatly appreciated. I'm happy to help with any further information to help figure out what's going on here.

Thank you in advance.

**Comment by lespea** [comment]
If you're reading the regex from a file it shouldn't have double escapes (so not `\\S+` but `\S+`)

**Comment by BurntSushi** [comment]
@lespea is right. That does indeed sound like your issue. If your file contains `\\S+` instead of `\S+`, then your regex will try to match a literal `\` followed by `S+` (corresponding to one or more `S` characters). Given that your data doesn't contain any backslashes, there will never be a match.

The reason why you need the double escape in a string literal and not in the file is because the double escape is specifically to appease escape sequences in _Rust string literals_. But the contents of a file are not a Rust string literal, and thus the double escape doesn't apply.

This is why you should generally never use normal string literals for regex. Because if you do, you have to deal with the escape sequences of _both_ string literals and regexes. Just one should be enough for anyone. :-)

**Comment by btv** [comment]
Hi and thank you both for the suggestion. I thought I tried that in the past, but it didn't work, so I tried again without any luck. My current code to show this looks like this:

```
    let svSession = &local_headers
        .get("cookie")
        .unwrap();

    match re1.captures(&svSession) {
        Some(cap) => {
            info!("svSession: {:?}, re1: {:?}", &cap.get(1).map_or("", |m| m.as_str()), &re1);
        },
        _ => {
            info!("cookie: {:?}, re: {:?}", &svSession, &re1);
        }
    };
```

`localheaders` is a Hashmap<String,String>. the `re1` variable is returned from the function in my original post. When I run the code, this is the output:

```
[2020-08-19T17:10:10Z INFO  APP_NAME] cookie: "hs=1090488148; svSession=7f5774a77907540af3ac18850d8857ee00b3a2a7f8651155b10b649da43f3e99b63a34a629f6574d945d1dba1a4c0da31e60994d53964e647acf431e4f798bcd848063a691d03ee36db2be2e4e3d388709b9451e1f45ad79d0ff062fdec20fe7; XSRF-TOKEN=1597434272|rwf40R9-irIq; TS01e85bed=01f0e931317a2530a7d775faf0a58c68d6f60a550a352a5ee449edb3d1c0929f0eec5e1ed28d8c77d19423a929d6f69c1ac1586520; TS015649a3=01f0e93131382668cacf8a70cde79be0d713686eb006fcfd4797bae0f1ca34b6e4ab6d322bdb14dfad16ef64db3ec611c8f82fdcf2; bSession=21348a83-1bf7-4e2b-aed9-bbea0398490e|1; ssr-caching=\"cache#desc=hit#varnish=hit#dc#desc=42\"", re: svSession=(\S+);
```

**Comment by BurntSushi** [comment]
@btv Hmm. At this point, I think I'll have to ask for a small program and your input so that I can try to reproduce it and figure out what's going wrong.

**Comment by btv** [comment]
That's a very fair request. I'll see if I can recreate this problem with a smaller program, and I'll share the code with you when I'm done.

**Comment by btv** [comment]
Ok, I have created a small program showing off the problem. https://github.com/btv/regex_test

When I run it on my machine, the "problem" is reproduced.

```
❯ cargo run
warning: unused manifest key: profile.release.rustflags
   Compiling regex_text v0.1.0 (/home/bryce/programming/spectrust/regex_text)
    Finished dev [unoptimized + debuginfo] target(s) in 0.55s
     Running `/home/bryce/programming/spectrust/regex_text/target/debug/regex_text`
[src/main.rs:9] "{:?}" = "{:?}"
[src/main.rs:9] &re2 = svSession=(\S+);

[src/main.rs:22] "cookie: {:?}, re: {:?}" = "cookie: {:?}, re: {:?}"
[src/main.rs:22] &cookie = "hs=1090488148; svSession=7f5774a77907540af3ac18850d8857ee00b3a2a7f8651155b10b649da43f3e99b63a34a629f6574d945d1dba1a4c0da31e60994d53964e647acf431e4f798bcd848063a691d03ee36db2be2e4e3d388709b9451e1f45ad79d0ff062fdec20fe7; XSRF-TOKEN=1597434272|rwf40R9-irIq; TS01e85bed=01f0e931317a2530a7d775faf0a58c68d6f60a550a352a5ee449edb3d1c0929f0eec5e1ed28d8c77d19423a929d6f69c1ac1586520; TS015649a3=01f0e93131382668cacf8a70cde79be0d713686eb006fcfd4797bae0f1ca34b6e4ab6d322bdb14dfad16ef64db3ec611c8f82fdcf2; bSession=21348a83-1bf7-4e2b-aed9-bbea0398490e|1; ssr-caching=\"cache#desc=hit#varnish=hit#dc#desc=42\""
[src/main.rs:22] &re1 = svSession=(\S+);
```

**Comment by BurntSushi** [comment]
@btv Oh. That's because your file ends with a `\n`, and `read_to_string` reads that. Just use `Regex::new(regex2.trim())` and it should be fixed.

**Comment by btv** [comment]
You nailed it. Thank you very much for the help, that's been driving me crazy all day yesterday.
