### ISSUE TITLE
Add backreferences and nested subpatterns

### ISSUE THREAD

**Issue by alexchandel** [rust-lang/regex#71]
Named and numbered backreferences such as `^(a(?1)?b)$` are common in PCRE implementations, and would be very useful here.

**Comment by huonw** [comment]
Is it possible to do them without backtracking (and the associated risk of exponential time blow-up)?

**Comment by BurntSushi** [comment]
@alexchandel Per the docs:

> Notably, backreferences and arbitrary lookahead/lookbehind assertions are not provided. In return, regular expression searching provided by this package has excellent worst case performance.

Russ Cox's regex articles are useful here: https://swtch.com/~rsc/regexp/

My suggestion is that if you want PCRE's extra features, then you should probably just use PCRE. [`rust-pcre`](https://github.com/alexcrichton/rust-pcre) exists, although I'm not sure if it's being maintained.

**Comment by alexchandel** [comment]
> Is it possible to do them without backtracking

I would imagine so.

> Per the docs

That's my point. The issue is that they aren't implemented. Please reopen.

> then you should probably just use PCRE

My intention is specifically not to link against PCRE, but use a rust implementation. Hence this repository. Backreferences fit neatly within the concept of [Pay for what you use](http://doc.rust-lang.org/regex/regex/index.html#pay-for-what-you-use). A regex that doesn't compute the locations of subexpressions doesn't pay for the cost, and regexes that don't use backreferences wouldn't pay for them either.

**Comment by huonw** [comment]
Imagining isn't quite enough in this case. All evidence I can find (e.g. the more advanced re2 library not implementing them) strongly suggests it unfortunately isn't possible.
