### ISSUE TITLE
Does regex support "?=" and "?<=" ?

### ISSUE THREAD

**Issue by swordow** [rust-lang/regex#716]
Does regex support "?=" and "?<=" now ?
And is  "\z" same with "\Z" in perl?

**Comment by BurntSushi** [comment]
> Does regex support "?=" and "?<=" now ?

This is answered in the first paragraph of the docs:

> This crate provides a library for parsing, compiling, and executing regular expressions. Its syntax is similar to Perl-style regular expressions, but lacks a few features like look around and backreferences. In exchange, all searches execute in linear time with respect to the size of the regular expression and search text.

as for this:

> And is "\z" same with "\Z" in perl?

Again, the answer is in the docs: https://docs.rs/regex/1.3.9/regex/#empty-matches
