### ISSUE TITLE
regex v0.1.28 : compilation error

### ISSUE THREAD

**Issue by gbersac** [rust-lang/regex#72]
I am trying to compile regex as part of a project and I get the following error message :

```
$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling regex v0.1.28
/home/guillaume/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.28/src/re.rs:16:25: 16:32 error: unresolved import `std::str::pattern::Pattern`. Could not find `pattern` in `std::str`
/home/guillaume/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.28/src/re.rs:16 use std::str::pattern::{Pattern, Searcher, SearchStep};
                                                                                                                  ^~~~~~~
/home/guillaume/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.28/src/re.rs:16:34: 16:42 error: unresolved import `std::str::pattern::Searcher`. Could not find `pattern` in `std::str`
/home/guillaume/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.28/src/re.rs:16 use std::str::pattern::{Pattern, Searcher, SearchStep};
                                                                                                                           ^~~~~~~~
/home/guillaume/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.28/src/re.rs:16:44: 16:54 error: unresolved import `std::str::pattern::SearchStep`. Could not find `pattern` in `std::str`
/home/guillaume/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.28/src/re.rs:16 use std::str::pattern::{Pattern, Searcher, SearchStep};
                                                                                                                                     ^~~~~~~~~~
error: aborting due to 3 previous errors
Could not compile `regex`.
```

And the version of rustc :

```
$ rustc --version
rustc 1.0.0-beta (9854143cb 2015-04-02) (built 2015-04-02)
```

And the version of cargo :

```
$ cargo --version
cargo 0.0.1-pre-nightly (84d6d2c 2015-03-31) (built 2015-03-31)
```

**Comment by BurntSushi** [comment]
Which project? It looks like it's enabling the `pattern` feature, which doesn't work on beta because it is unstable.

**Comment by gbersac** [comment]
This is a personal project which you can find on github : https://github.com/gbersac/computorv1-42

Am I suppose to use nightly ? What if I want to stay with beta ?

**Comment by BurntSushi** [comment]
You can't use beta and enable unstable features: https://github.com/gbersac/computorv1-42/blob/master/src/main.rs#L1-L3 If you want to use unstable features, you must use the nightly.

One of the unstable features you're using is `regex_macros`, which only works on the nightly. It also enables the `pattern` feature, which is why you're getting this error. (`pattern` only works on nightly too.)

If you want to work on beta, you'll need to remove all uses of `#![feature(...)]` and change your dependencies to just `regex` (no `regex_macros`).

**Comment by BurntSushi** [comment]
You may find this useful :-) https://github.com/docopt/docopt.rs/blob/master/src/lib.rs#L231-L233

**Comment by havarnov** [comment]
Just note that that won't give you compile time errors, obviously.

**Comment by BurntSushi** [comment]
Nor a nice performance boost!
