### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [rust-lang/regex#723]
**Summary**
Installing regex on aarch64 via pip using command "pip3 install regex" tries to build wheel from source code

**Problem description**
regex doesn't have wheel for aarch64 on PyPI repository. So, while installing regex via pip on aarch64, pip builds wheel for same resulting in it takes more time to install regex. Making wheel available for aarch64 will benefit aarch64 users by minimizing regex installation time.

**Expected Output**
Pip should be able to download regex wheel from PyPI repository rather than building it from source code.

@regex-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make regex wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by BurntSushi** [comment]
Not sure how you ended up here, but this is not the home of the Python regex package.
