### ISSUE TITLE
pattern matching structure might (or not?) be too strict

### ISSUE THREAD

**Issue by hallya** [rust-lang/regex#733]
I've encountered a case where I am no expert to say wether  or not it a bug on this crate or on the site I'm using to test my regex.

[Here is a regex with string sample](https://regex101.com/r/8YN1Ly/1/).
It's working as I expect. First 6 lines match and the rest doesn't.

But if I use this regex as one element of `RegexSet::new` (`r"^[^a-z]([A-Z\W\d]*)[A-Z]+$"`) I miss those matches:
- `1, 2, 3 GO!", "Whoa, chill out!`
- `ZOMG THE %^*@#$(*^ ZOMBIES ARE COMING!!11!!1!`
- `WATCH OUT!`

I've figured out how to do the match (`r"^[A-Z\W\d]*[A-Z]+[A-Z\W\d]*[^a-z?]$"`) and I think I understood why, but I can't tell if this behavior is the norm or if it constraint too much regex structure.

It seems to me that it is actually capturing as much as possible from **_subpattern A_** composition and then if this **_subpattern A_** is met again later after a **_subpattern B_** it will require to specify again **_subpattern A_** in order to match

**Comment by BurntSushi** [comment]
Please provide a complete Rust program with any relevant inputs. Please provide expected output and actual output.

**Comment by hallya** [comment]
Well it is bob exercice on https://exercism.io/ rust track

You will need the cli to download it: https://exercism.io/cli-walkthrough

Then in a terminal, enter `exercism download --exercise=bob --track=rust` (installed at `/Users/<username>/Exercism/rust/bob`

my code:

*lib.rs*:
```rust
use regex::RegexSet;

pub fn reply(message: &str) -> &str {
  let yelling = r"^[A-Z\W\d]*[A-Z]+[A-Z\W\d]*[^a-z?]$";
  let rought_question = r"^[^a-z][A-Z]+[A-Z\W]*\?$";
  let calm_question = r"^[\w\W\d]+\? *$";
  let quiet = r"^\W*$";
  let anything = r".*";

  let answers = [
    "Whoa, chill out!",
    "Calm down, I know what I'm doing!",
    "Sure.",
    "Fine. Be that way!",
    "Whatever.",
  ];

  let patterns = RegexSet::new(&[
    yelling,
    rought_question,
    calm_question,
    quiet,
    anything,
  ]).unwrap();

  let matches: Vec<usize> = patterns.matches(message).into_iter().collect();
  answers[matches.first().unwrap().clone()]
}
```
test *matching-brakcets.rs*:
```rust
use matching_brackets::brackets_are_balanced;

#[test]
fn paired_square_brackets() {
  assert!(brackets_are_balanced("[]"));
}

#[test]
#[ignore]
fn empty_string() {
  assert!(brackets_are_balanced(""));
}

#[test]
#[ignore]
fn unpaired_brackets() {
  assert!(!brackets_are_balanced("[["));
}

#[test]
#[ignore]
fn wrong_ordered_brackets() {
  assert!(!brackets_are_balanced("}{"));
}

#[test]
#[ignore]
fn wrong_closing_bracket() {
  assert!(!brackets_are_balanced("{]"));
}

#[test]
#[ignore]
fn paired_with_whitespace() {
  assert!(brackets_are_balanced("{ }"));
}

#[test]
#[ignore]
fn partially_paired_brackets() {
  assert!(!brackets_are_balanced("{[])"));
}

#[test]
#[ignore]
fn simple_nested_brackets() {
  assert!(brackets_are_balanced("{[]}"));
}

#[test]
#[ignore]
fn several_paired_brackets() {
  assert!(brackets_are_balanced("{}[]"));
}

#[test]
#[ignore]
fn paired_and_nested_brackets() {
  assert!(brackets_are_balanced("([{}({}[])])"));
}

#[test]
#[ignore]
fn unopened_closing_brackets() {
  assert!(!brackets_are_balanced("{[)][]}"));
}

#[test]
#[ignore]
fn unpaired_and_nested_brackets() {
  assert!(!brackets_are_balanced("([{])"));
}

#[test]
#[ignore]
fn paired_and_wrong_nested_brackets() {
  assert!(!brackets_are_balanced("[({]})"));
}

#[test]
#[ignore]
fn paired_and_incomplete_brackets() {
  assert!(!brackets_are_balanced("{}["));
}

#[test]
#[ignore]
fn too_many_closing_brackets() {
  assert!(!brackets_are_balanced("[]]"));
}

#[test]
#[ignore]
fn early_incomplete_brackets() {
  assert!(!brackets_are_balanced(")()"));
}

#[test]
#[ignore]
fn early_mismatched_brackets() {
  assert!(!brackets_are_balanced("{)()"));
}

#[test]
#[ignore]
fn math_expression() {
  assert!(brackets_are_balanced("(((185 + 223.85) * 15) - 543)/2"));
}

#[test]
#[ignore]
fn complex_latex_expression() {
  let input = "\\left(\\begin{array}{cc} \\frac{1}{3} & x\\\\ \\mathrm{e}^{x} &... x^2 \
                 \\end{array}\\right)";
  assert!(brackets_are_balanced(input));
}
```

**Comment by BurntSushi** [comment]
I'm not downloading some other tool just to compile a Rust program. Please provide a normal Rust program that I can build with Cargo.

**Comment by hallya** [comment]
look, I don't know what you want and the way you speak isn't very friendly. I was just reporting this to help, so forget let's forget it 👋🏼

**Comment by BurntSushi** [comment]
> I don't know what you want

A program I can run with `cargo run` that produces output, along with desired/expected output.

> the way you speak isn't very friendly

I'm trying to help you during the holidays. When you file bug reports or support questions without an easy way to reproduce them, the result is that I have to spend more of my time away from family and other things in order to help you. I refuse to do that. Instead, I asked you to provide more information so that I can help you more easily.

What isn't friendly is expecting someone else to guess what you mean and do circuitous things to reproduce your problem, especially during the holidays _and then_ rage-quitting while accusing _me_ of being unfriendly.

**Comment by hallya** [comment]
So you think I'm expecting something here ? I expect nothing. This is also my free time, I'm not working for anyone doing this.
You are maintaining this crate, not me. So my guess was that you (meaning this lib) are probably looking for bugs in order to fix them and.
I need nothing here, I'm just reporting.

This program isn't running with `cargo run`, only `cargo test` so you have everything I can give you as far as I know. I also give you the way to reproduce exactly this case. If it seems to painful to do that's ok, again I'm don't expect anything I'm just reporting and if you need more specific infos I can surely give them to you.

Remember that your level in rust isn't necessary the level of your interlocutor. When you ask a "complete Rust program" event when I gave all I had I'm a bit confuse.

Rage-quitting implies a game where there is a loser and a winner. I hope that's not what you meant here so stay polit please.

Just be coherent with yourself, don't write "I love to code" as a description to then tell me about taking time from your precious holidays. I'm on holiday too, and I also love to code and because I really believe in this I hope I will never say something like this.
