### ISSUE TITLE
Support Branch Reset Groups

### ISSUE THREAD

**Issue by omid** [rust-lang/regex#740]
As far as I can see, we do not have the support of branch reset groups.
If you are not familiar with it, you can find the description here: https://www.regular-expressions.info/branchreset.html

A very short version of the description:
It's so similar to `?:`, but `?|` will reset the group number in every branch, also you can use the same variable name in all branches.

**Comment by BurntSushi** [comment]
Doesn't seem worth it to me personally. Seems overly complicated.
