### ISSUE TITLE
RegexSet bad performance

### ISSUE THREAD

**Issue by FH0** [rust-lang/regex#744]
regex v1.4.3

My test code. I think RegexSet faster than Vec\<Regex\>.
```rust
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut string_vec = Vec::new();
    let mut regex_vec = Vec::new();

    for index in 0usize..100_000 {
        let elem = format!(r"(^|\.){}\.com$", index);
        regex_vec.push(regex::Regex::new(elem.as_str()).unwrap());
        string_vec.push(elem);
    }

    let regset = regex::RegexSetBuilder::new(string_vec)
        .unicode(false)
        .size_limit(std::usize::MAX)
        .build()?;

    for _ in 0..10 {
        let start = std::time::Instant::now();
        for elem in &regex_vec {
            if elem.is_match("a.50000.com") {
                println!("regex {:?}", std::time::Instant::now() - start);
                break;
            }
        }

        let start = std::time::Instant::now();
        if regset.is_match("a.50000.com") {
            println!("regset {:?}", std::time::Instant::now() - start);
        }
    }

    Ok(())
}
```

It's my result, which is built with release flag.
```bash
regex 203.7967ms
regset 326.6608ms
regex 14.0224ms
regset 190.4967ms
regex 14.4504ms
regset 203.9489ms
regex 15.1789ms
regset 191.0099ms
regex 14.7549ms
regset 184.0801ms
regex 16.4629ms
regset 209.4672ms
regex 15.5065ms
regset 198.6308ms
regex 14.721ms
regset 177.5837ms
regex 15.6902ms
regset 185.1668ms
regex 14.9526ms
regset 183.2476ms
```

**Comment by BurntSushi** [comment]
My comment on your other issue applies here too. But also, your benchmark is incorrect. The regex set looks for all matches, including overlapping matches. But your iterative approach does not.

**Comment by FH0** [comment]
Sorry about the memory issue, I don't know regex should take so much memory. But I still think RegexSet should faster than Vec\<Regx\> when I use is_match function. [As it said](https://docs.rs/regex/1.4.3/regex/struct.RegexSet.html#method.is_match)

> My comment on your other issue applies here too. But also, your benchmark is incorrect. The regex set looks for all matches, including overlapping matches. But your iterative approach does not.

**Comment by BurntSushi** [comment]
> But I still think RegexSet should faster than Vec<Regex> 

You are welcome to think that. I personally see no reason why it should be true. It is only true sometimes.

**Comment by FH0** [comment]
> > But I still think RegexSet should faster than Vec
> 
> You are welcome to think that. I personally see no reason why it should be true. It is only true sometimes.

This is not my wishful thinking. I notice these words in document, which make think like this. On the other hand, if RegexSet slower than Vec\<Regex\>, when should I use RegexSet?

> This is because the underlying matching engine will quit immediately after seeing the first match instead of continuing to find all matches.

**Comment by BurntSushi** [comment]
> On the other hand, if RegexSet slower than Vec<Regex>, when should I use RegexSet?

I just told you that it isn't always slower. Use a regex set if your benchmark leads you there. Or if you need its functionality.

**Comment by BurntSushi** [comment]
The points of a regex set are:

1. It does overlapping matches.
2. Its algorithmic complexity is optimal.

This doesn't _necessarily_ translate into faster absolute performance. It only does sometimes. Like with _all_ such code, you need to benchmark your specific use case and determine the right tool. Expecting something to be a one-size-fits-all panacea will lead you astray eventually.

You also haven't responded to my suggestion to use the `aho-corasick` crate. That _looks_ like a better answer here, although I cannot be sure since your benchmark appears artificial and I haven't seen a high level description of the problem you're trying to solve.

**Comment by FH0** [comment]
Thanks for your help. I will try to use `aho-corasick` crate later. It's better to add some tips [here](https://docs.rs/regex/1.4.3/regex/struct.RegexSet.html#method.is_match) to remind someone like me to use Vec\<Regex\>.
