### ISSUE TITLE
Async Regex?

### ISSUE THREAD

**Issue by billyb2** [rust-lang/regex#746]
#### Describe your feature request

Having the ability to run Regex captures using async/await would be very useful, since these functions take a (relatively) long time on larger texts, and would do very well with running concurrently.

It would probably be a breaking change, so having it as a feature would be nice (maybe features=["async"]).

**Comment by BurntSushi** [comment]
This isn't practical to implement and, to be honest, doesn't make sense to me. Searching doesn't do I/O. There are no obvious "await" points.
