### ISSUE TITLE
Bug: match on "ϰϯ" for the regex "ϯ*"  

### ISSUE THREAD

**Issue by Miro-Andrin** [rust-lang/regex#789]
#### What version of regex are you using?
regex = "1.5.4"

#### Describe the bug at a high level.
I found a case were the regex matches on something it believe should not. 

#### What are the steps to reproduce the behavior?
```rust
#[test]
fn regex_bug() {
    let regex = "ϯ*";
    let input = "ϰϯ";
    let compiled = regex::Regex::new(&regex).unwrap();
    assert!(!(compiled.is_match(input)))
}
```

#### What is the actual behavior?
```
thread 'automata::quickcheck::regex::regex_bug' panicked at 'assertion failed: !(compiled.is_match(input))', src/automata/quickcheck/regex.rs:210:5
```
#### What is the expected behavior?
That it does not match for the given input. And therefore does not fail.

**Comment by lespea** [comment]
`ϯ*` checks for `ϯ` zero or more times... so it will always match.

**Comment by BurntSushi** [comment]
Could you say why you think this should not match?

**Comment by Miro-Andrin** [comment]
Because i was working late and mixed up fullmatch vs match.
