### ISSUE TITLE
Method `longest_match`

### ISSUE THREAD

**Issue by anovs** [rust-lang/regex#791]
There is `is_match` that checks if there is a match for the given string, there is `shortest_match` that checks if there is a match and returns the length of the shortest match, but no method that checks if there is a match and returns the length of the longest match.

Re-using the `shortest_match` example, we would have:

```
let text = "aaaaa";
let pos = Regex::new(r"a+").unwrap().longest_match(text);
assert_eq!(pos, Some(5));
```

**Comment by BurntSushi** [comment]
That's what `find` does.

(Well, technically `find` is "leftmost-first" or "preference-first." This crate doesn't implement POSIX "leftmost longest" semantics.)

**Comment by BurntSushi** [comment]
And note also that `shortest_match` is perhaps not the best name: https://github.com/rust-lang/regex/issues/747

**Comment by anovs** [comment]
I was confused about what `shortest_match` did, sorry. I thought it stopped if the first character of the string didn't match the regex (and I thought the same about `is_match`). I suggest to change the example of [`shortest_match`](https://docs.rs/regex/1.5.4/regex/struct.Regex.html#method.shortest_match) and have `text` be `"baaaa"` to illustrate that it's not the case. That would help clear the confusion for noobs like me who just discovered the crate.

Again sorry for the useless issue and thanks for the precision.
