### ISSUE TITLE
Add `add_item()` to RegexSet

### ISSUE THREAD

**Issue by oren0e** [rust-lang/regex#800]
I have a use case where I have structs that contain regexes e.g.
```rust
let issue_01 = Issue::new("name_of_issue", Regex::new(r"bla bla").unwrap(), Regex::new(r"something").unwrap());
```
and then later I want to iterate over these and add their corresponding regexes into one RegexSet. I didn't see this is possible currently (by searching through the docs).

**Comment by BurntSushi** [comment]
You can't. The only way to build a `RegexSet` is with the constructor that accepts an iterator of patterns: https://docs.rs/regex/1.5.4/regex/struct.RegexSet.html#method.new

You can't just arbitrarily add a `Regex` to a `RegexSet` after the fact.
