### ISSUE TITLE
\w consumes memory

### ISSUE THREAD

**Issue by Frozen1084** [rust-lang/regex#807]
#### What version of regex are you using?
`1.5.4`

#### Describe the bug at a high level.

\w takes up memory

#### What are the steps to reproduce the behavior?

I noticed that my software was suddenly using 2M more memory, even though it was working properly.
After my test, using \w, the software took up 4.2MB of memory
`let varr: Regex = Regex::new(r#"%([a-zA-Z]_[\w]{2,10})%"#).unwrap();`

If I replace \w with [a-zA-Z0-9_], it only takes up 1.3MB of memory
`let varr: Regex = Regex::new(r#"%([a-zA-Z]_[a-zA-Z0-9_]{2,10})%"#).unwrap();`

**Comment by BurntSushi** [comment]
This isn't a bug. `\w` is a large Unicode character class. So on its own, it uses a fair bit of memory. But it uses even more in this case because of the bounded repeat.

There's really nothing to be done here. If you want Unicode, then you have to pay for it.
