### ISSUE TITLE
Support for Keep out \K

### ISSUE THREAD

**Issue by F34th3R** [rust-lang/regex#853]
There is a method for this, without using lookbehind?

**Comment by BurntSushi** [comment]
What? Please consider adding more detail. I have no eathly clue what you're talking about. Consider providing more detail and examples.

**Comment by lespea** [comment]
I was curious what this was too and googling led me here: https://perldoc.perl.org/perlre#%5CK

> There is a special form of this construct, called \K (available since Perl 5.10.0), which causes the regex engine to "keep" everything it had matched prior to the \K and not include it in $&. This effectively provides non-experimental variable-length lookbehind of any length.

**Comment by BurntSushi** [comment]
@lespea Thanks!

Assuming this is a feature request, I'm going to close this, as this crate doesn't support look-around. (Beyond some simple cases for anchor/word-boundary assertions.)
