### ISSUE TITLE
expose the Input trait

### ISSUE THREAD

**Issue by njskalski** [rust-lang/regex#867]
I wanted to wire "Input" trait to ropey::Rope, but I get regex::prog is "private module". I can write patch myself, this is rather a question: is there a reason this is not enabled by default or just nobody needed it so far?

**Comment by BurntSushi** [comment]
The issue title here seems totally disconnected from the actual substance of the request. I've renamed the title...

Well, yes, there is a reason. It's not part of the public API and never will be.

For executing regexes on discontiguous text, see: https://github.com/rust-lang/regex/issues/425

For longer term plans, see: https://github.com/rust-lang/regex/issues/656

**Comment by BurntSushi** [comment]
Closing this because the `Input` trait will actually be removed at some point and there really aren't enough details in this request to make it actionable. #425 is probably a better general ticket if the use case is to indeed do a regex search on discontiguous text.
