### ISSUE TITLE
possible memory leak in use of RegexSet

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang/regex#875]
### Discussed in https://github.com/rust-lang/regex/discussions/874

<div type='discussions-op-text'>

<sup>Originally posted by **adamchalmers** June 22, 2022</sup>
Hi! I'm trying to find the source of some memory leaks in a gRPC server my team is building. One of the endpoints runs some RegexSets over some inputs. 

I'm using [dhat](docs.rs/dhat) to measure memory usage, and I notice running `RegexSet::matches(field).into_iter().next()` adds around 2.4kb of memory leak per run. I know the RegexSets have an internal cache where they store programs. I was wondering if this cache grows unboundedly? Is it possible to put a limit on the cache size, or to describe the cache behaviour in the crate's docs?</div>

**Comment by BurntSushi** [comment]
cc @adamchalmers

**Comment by BurntSushi** [comment]
Can you provide a repro? Here's one:

```rust
use regex::RegexSet;

const ITERS: usize = 1_000;

fn main() {
    let haystack = "Шерлок Холмс ".repeat(1_000);
    let re = RegexSet::new(&[
        r"\pL{5}",
        r"\w{6}",
        r"\w{6}\s+\w{5}",
    ]).unwrap();

    let mut count = 0;
    for _ in 0..ITERS {
        if let Some(_) = re.matches(&haystack).into_iter().next() {
            count += 1;
        }
    }
    println!("{:?}", count);
}
```

Running the program as-is:

```
$ cargo build --release
$ time ./target/release/d874
1000

real    1.039
user    1.032
sys     0.007
maxmem  9 MB
faults  0
```

Modifying the program to have `ITERS = 10_000` gives:

```
$ time ./target/release/d874
10000

real    10.270
user    10.261
sys     0.007
maxmem  9 MB
faults  0
```

So an order of magnitude more searches, but the memory usage remains invariant.

Here's another variant, where we compile the `RegexSet` in the loop:

```rust
use regex::RegexSet;

const ITERS: usize = 100;

fn main() {
    let haystack = "Шерлок Холмс ".repeat(1_000);

    let mut count = 0;
    for _ in 0..ITERS {
        let re = RegexSet::new(&[
            r"\pL{5}",
            r"\w{6}",
            r"\w{6}\s+\w{5}",
        ]).unwrap();
        if let Some(_) = re.matches(&haystack).into_iter().next() {
            count += 1;
        }
    }
    println!("{:?}", count);
}
```

Running that gives:

```
$ time ./target/release/d874
100

real    0.446
user    0.439
sys     0.007
maxmem  10 MB
faults  0
```

Setting `ITERS = 1_000` gives:

```
$ time ./target/release/d874
1000

real    4.217
user    4.205
sys     0.010
maxmem  10 MB
faults  0
```

In this case also, memory usage is invariant despite an order of magnitude more
compilations/searches.

This is generally what I would expect. With that said...

> describe the cache behaviour in the crate's docs?

I would prefer not. It's really an internal implementation detail. I would be
open to, perhaps, including something in `PERFORMANCE.md` though.

> Is it possible to put a limit on the cache size,

Technically that's what `RegexSetBuilder::dfa_size_limit` is for. However,
there may be other relevant limits, such as the total _number_ of such caches
built.

In general, I'd rather limits in the API be a last resort. I would want to
understand the leak first, and whether there is a way to robustly fix it in
general.

> I was wondering if this cache grows unboundedly?

That's the money shot. Technically, the answer to this is "yes." There is no
technical reason for why the cache must grow unbounded.

The "cache" exists at two levels:

* Each regex engine gets its own cache that basically involves regex engine
  specific state that is mutated during search.
* Since a Regex can be used from multiple threads simultaneously, there are
  two ways to give mutable space to each regex engine. Either the mutable
  space itself becomes thread safe (effectively a non-starter, but not
  impossible, but likely impossible without sacrificing search time), or the
  regex maintains multiple scratch spaces per regex engine so that they are
  entire independent. The current implementation takes the latter approach and
  will for the forseeable future.

The guts of that second piece are implemented here:
https://github.com/rust-lang/regex/blob/db1efc6842bab2c57f2b55c2eefac68735ea87d7/src/pool.rs#L166-L277

Conceptually, and ignoring optimizations, it's pretty simple:

* When a search is executed, it requests cache state from the pool.
* If cache state exists, it's popped from its internal storage and given to
  the caller in a guard. When the guard is dropped, the state gets pushed back
  into the internal storage.
* If cache state doesn't exist, then new state is created and returned inside
  a guard. As above, once the guard is dropped, the state is pushed back into
  the internal storage.

State doesn't care which thread it gets sent to. It's all interchangeable.

As I hinted at above, this is the part where cache size is unbounded. There is
no step in the current implementation that compacts the internal storage of the
pool.

Why? [Because I'm waiting for a real world use case.](https://github.com/rust-lang/regex/blob/db1efc6842bab2c57f2b55c2eefac68735ea87d7/src/pool.rs#L39-L41).
Your use case might be the one. But maybe not. I really need a repro.

I'd also like to make clear one specific point: the *expectation* is that
the cache grows without bound, but only in relation to the **number of regex
searches executing simultaneously for any single regex**. So for example, if
you have 100 threads running but only 10 of them are executing a search for the
same regex simultaneously, then the internal pool _should_ only have 10 copies
of the cache state. (Now, maybe there is a bug and that isn't happening.)

Another experiment you could do, which could potentially also be a work-around,
is to create a new regex for each thread you execute them in. That is, instead
of creating one and sharing it across multiple threads, you create one for
each thread. This can be done by cloning the regex. Internally, Regex uses
reference counting for its immutable state. But each cloned regex gets its
own pool. So if your leak is coming from the pool and it can be traced to the
lack of compaction in the pool---perhaps because threads are spinning up and
down---then in theory this would eliminate the problem because once the thread
gets spun down, the Regex it owns will be freed and so will its pool.
[This advice is already in `PERFORMANCE.md`](https://github.com/rust-lang/regex/blob/master/PERFORMANCE.md#using-a-regex-from-multiple-threads).
It might also improve search time as well, since the "owning" thread of a Regex
has a special fast path with the pool.

So... bottom line, I'd like to see this fixed, and the most important thing
that can be done to get it fixed is probably to give me a minimal reproduction
of the issue.

If I've got your usage completely wrong and you aren't even using multiple
threads, then that would be pretty bewildering. :-)

Also, any use of Regex above is interchangeable with RegexSet. They both use
identical machinery internally.

**Comment by adamchalmers** [comment]
Hi! I haven't been able to reproduce this, so I think something else must have been going on. Thanks for the thorough explanation.

**Comment by BurntSushi** [comment]
Aye. If you do wind up finding a repro, I would be happy to re-open this, dig into it and figure out a solution.
