### ISSUE TITLE
Feature Request: iterate over named capture groups

### ISSUE THREAD

**Issue by jtmoon79** [rust-lang/regex#876]
## Problem

I want to extract a datetime substring from a larger string with predictable extraneous substrings.

For example, given this contrived data
```text
[VERBOSE] 2000-01-01 00:00:01 -0700 saying hello :-)
[INFO] 2000-01-01 00:00:01 -0700 trying something...
[WARNING] 2000-01-01 00:00:02 -0700 something isn't quite right...
[ERROR] 2000-01-01 00:00:03 -0700 things are definitely wrong!
```

In my regular expression pattern, for clarity there are many capture groups, but only some named ones that I am interested in.  ***However, after calling `regex.captures`, it's difficult to associate each `Match` instance with it's named capture group***.

## Example

Here is [an example of the problem and one possible solution](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9e95a02760c80e527d93fb155ee09b1d).

The first capture group is unnamed (it's used for clarity to humans). However, the unnamed capture group is not important later on. The named captured groups are important and I would like to refer to them later.

```rust
use std::fs::File;
use std::io::{self, BufRead};
use std::path::Path;

extern crate regex;

fn main() {
    let pattern = r"^\[(INFO|ERROR|TRACE|WARNING|VERBOSE)\] (?P<year>\d{4})-(?P<month>\d{2})-(?P<day>\d{2}) (?P<hour>\d{2}):(?P<minute>\d{2}):(?P<second>\d{2}) (?P<tz>[\+\-]\d{4}) ";
    let regex_ = regex::Regex::new(pattern).unwrap();
    for line in [
        "[VERBOSE] 2000-01-01 00:00:00 -0700 saying hello :-)",
        "[INFO] 2000-01-01 00:00:01 -0700 trying something...",
        "[WARNING] 2000-01-01 00:00:02 -0700 something isn't quite right...",
        "[ERROR] 2000-01-01 00:00:03 -0700 things are definitely wrong!",
    ] {
        println!("{}", line);
        let captures: regex::Captures = regex_.captures(line).unwrap();
        // Feature Request suggestion: `iter_named`
        for capture_group_named_opt in captures.iter_named() {
            if let Some(capture_group_named) = capture_group_named_opt {
                eprintln!("name {:?}, group data {:?}", capture_group_named.name(), capture_group_named.text());
                // ... do something important with the named capture group ...
            }
        }
    }
}
```

I would like to the code to run and print:
```text
name "year", group data "2000"
name "month", group data "01"
name "day", group data "01"
name "hour", group data "00"
name "minute", group data "00"
name "second", group data "00"
name "tz", group data "-0700"
```

But currently, the first `regex_.captures(lines).unwrap().iter()` has `Match.as_str()` element values
- `"VERBOSE"` (the unnamed capture group)
- `"2000"`
- `"01"`
- `"01"`
- `"00"`
- `"00"`
- `"00"`
- `"-0700"`

I am only interested in the named capture groups.  I can do a bit of very tedious work to determine the named capture groups.  ***But it seems that the `regex` crate should provide easier method to distinguish named and unnamed capture groups when iterating over them.***  In this case, iterating over groups should provide the group name if available.

## Suggestions

Some different ideas for solving this problem.

- add `fn iter_named() -> Iter<CaptureGroup>` shown in the example
- add to `Match` a `fn group_name() -> Option<'a str>`. If `None` then the match instance was not part of a named capture group. `Some(val)` means it was part of a named capture group. This way I could use the already-implemented `iter()` from `regex_.captures(lines).unwrap().iter()`.

To be clear, these are just quick suggestions to help regex development experts get started. I'm sure there are many other design considerations that I'm not aware.

**Comment by BurntSushi** [comment]
You can do this today. The key is the [`Regex::captures_names`]() method, which lives on `Regex`, not `Captures`. Here's your example adapted to give the output you want using existing APIs:

```rust
fn main() {
    let pattern = r"^\[(INFO|ERROR|TRACE|WARNING|VERBOSE)\] (?P<year>\d{4})-(?P<month>\d{2})-(?P<day>\d{2}) (?P<hour>\d{2}):(?P<minute>\d{2}):(?P<second>\d{2}) (?P<tz>[\+\-]\d{4}) ";
    let regex_ = regex::Regex::new(pattern).unwrap();
    for line in [
        "[VERBOSE] 2000-01-01 00:00:00 -0700 saying hello :-)",
        "[INFO] 2000-01-01 00:00:01 -0700 trying something...",
        "[WARNING] 2000-01-01 00:00:02 -0700 something isn't quite right...",
        "[ERROR] 2000-01-01 00:00:03 -0700 things are definitely wrong!",
    ] {
        println!("{}", line);
        let captures: regex::Captures = regex_.captures(line).unwrap();
        // Feature Request code `iter_named`
        for group in regex_.capture_names() {
            if let Some(name) = group {
                eprintln!("name {}, group data {}", name, &captures[name]);
            }
        }
    }
}
```

Playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5cf41631c5f1f28235242b9f066e364c

**Comment by jtmoon79** [comment]
Thanks @BurntSushi .

I guess I was hoping for one call that would provide some thingy that referenced both the capture group name and the captured value.  Your example code does two calls, `regex.capture_names()` then `&captures[name]`.

That works fine.  Closing this Issue.
