### ISSUE TITLE
unescape using copy on write

### ISSUE THREAD

**Issue by ratmice** [rust-lang/regex#898]
I having written a function similar to `escape`,  noticed that `escape` appears to allocate even if the parameter requires no escaping.
Avoiding the allocation requires a bit more of an involved implementation, 

I don't really have a need or anything which actually calls this function, but would be happy to make a PR which implements this,
either as a new function, or an ABI change, if either of those options is desirable.

**Comment by BurntSushi** [comment]
I don't see a reason for it personally. If you can come up with a solid use case for it, then feel free to re-open. But given you don't have a need for it, I'm going to close it. (I kind of wonder why you wrote it if you don't have a need for it?)

> or an ABI change

Note that currently, the only way ABI is relevant in Rust is when using `repr(C)` and building a dynamic library. You probably meant API.

**Comment by ratmice** [comment]
The reason I wrote/opened what I wrote is a very similar function for another project, but slightly different.
It would require only minor modifications to convert the code in the case of `escape`.

If anyone does come up with a need or use case feel free to ping me, and I will make the changes and post a PR/reopen.
