### ISSUE TITLE
Allow regex-capi (`rure`) to be built as an rlib

### ISSUE THREAD

**Issue by mystor** [rust-lang/regex#909]
Currently the `rure` crate is only buildable as a `cstaticlib` or `cdylib` format ([code](https://github.com/rust-lang/regex/blob/159a63c85eb77ec321301bc4c4ebfb90343edc2b/regex-capi/Cargo.toml#L18)), and cannot be easily included within a larger rust `cstaticlib` as a dependency. It would be nice if this crate also allowed itself to be built as a normal rlib dependency, so that it could be depended on in this way. This would make it easier to share a single copy of the `regex` crate and its dependencies between C/C++ and Rust code within a single project.

**Comment by BurntSushi** [comment]
Sorry, but I don't understand the request. regex-capi is a C library, meant to be used over ffi. Why do you want it as an rlib? Please provide a concrete example. It would also help if you could find other Rust projects exposing C APIs via rlibs.

**Comment by mystor** [comment]
In gecko, we combine a [number of rust crates together](https://github.com/mozilla/gecko-dev/blob/cc6f01f78c37e86a8e994ca305099500f946420f/toolkit/library/rust/shared/lib.rs) into a [single `cstaticlib`](https://github.com/mozilla/gecko-dev/blob/cc6f01f78c37e86a8e994ca305099500f946420f/toolkit/library/rust/Cargo.toml) which is then linked into libxul alongside our C++ code. Many crates here expose C FFI of some form or another which is then used by our C++ code (and vice-versa). 

For this sort of project, it'd be preferable to avoid linking in `rure` as a separate `cstaticlib`, as that could lead to duplicate copies of the rust standard library and the `regex` crate, which would be undesirable.

There are a few examples of crates exporting C APIs via rlibs in that module, but a quick scan doesn't reveal any which are on crates.io (they're generally internal bindings). I mostly filed this bug because I noticed we have a custom [`regex` crate ffi wrapper](https://github.com/mozilla/gecko-dev/blob/df5d5f189ba2e0eb0524ffcf0e8f3ce29cd0eb4f/toolkit/components/regex-ffi/src/lib.rs), which might be nice to replace with the more feature-rich `rure` bindings. We could probably do that with a fork if needed.

**Comment by BurntSushi** [comment]
Ah that's cool. I think I just didn't realize that `rlib` was a useful output type for a library that was just a C API. I've added `rlib` and pushed the change out in `rure 0.2.2`.
