### ISSUE TITLE
Typeful construction of Regex

### ISSUE THREAD

**Issue by mingyli** [rust-lang/regex#938]
Apologies if this has been raised before.

`Regex` currently offers construction from strings via `Regex::new`. I've enjoyed using other regex libraries such as https://github.com/ocaml/ocaml-re where I can construct regular expressions through combinators

```ocaml
  let pattern =
    let open Re in
    let num = seq [ opt (char '-'); rep digit ] in
    seq
      [ str "x="
      ; group num
      ; str ", y="
      ; group num
      ]
    |> compile
  ;;
```

I think I'd enjoy using an API in this crate where I could construct something like an `Ast` from the `regex-syntax` crate and compile that into a `Regex`. From skimming other issues in this repository it seems like we wouldn't want to expose exactly that struct from `regex-syntax`, but I think exposing a type that reads like `Ast` could be a neat API.

**Comment by BurntSushi** [comment]
An `Ast` is _extraordinarily_ inconvenient to use. If you look more closely, I think you'd probably agree something closer to `Hir` would be better, but even that is not as convenient as you would want.

Aside from that, I think this kind of API is way too niche to warrant a place in the `regex` crate API. I also perceive a rather large design space for it, and I do not have the bandwidth to deal with that. But the main strike against it is that I just don't think it belongs in this crate. Importantly, such an API needn't be exposed in this crate. You or anyone can go off and build your own API in your own crate. In theory, after many years, if it caught on and lots of people were using it, _then_ I might consider adding it to the `regex` crate.

Also, just speaking personally, I find the traditional concrete syntax of regexes to be far easier to read than what you've presented here.

You might also consider using a parser combinator library, such as `nom`.

**Comment by mingyli** [comment]
Sounds reasonable thanks for the response
