### ISSUE TITLE
Docs are broken for `latest` aka `1.7.0`

### ISSUE THREAD

**Issue by swarnim-deepsource** [rust-lang/regex#945]
#### Describe the bug at a high level.

Welp, the latest version's doc page seems to be broken. 

#### What are the steps to reproduce the behavior?

Goto,
https://docs.rs/regex/latest/regex/index.html

#### What is the actual behavior?

From 1.6.0,
![image](https://user-images.githubusercontent.com/99165284/211247362-16fff110-5edf-40e3-9643-eeae8e12f402.png)

#### What is the expected behavior?

For latest,
![image](https://user-images.githubusercontent.com/99165284/211247318-e03fa8b1-cc02-4271-8327-813a7960a531.png)

#### Notes

I am open to fixing this issue if it's something that I can open a PR for, haven't had the time to look into it, I will take a look at the weekend.

The bug is repeatable on my friend's system and also on mobile devices.

**Comment by swarnimarun** [comment]
Oops(used the wrong id), ping me here, not sure if I will check my work github for notifications. :P

**Comment by BurntSushi** [comment]
OK, I've kicked off a new release with the hope it was just a temporary glitch, and that appears to be the case. The rendering for 1.7.1 looks good to me.
