### ISSUE TITLE
Program unexpected panic when vec is called

### ISSUE THREAD

**Issue by bhao-Soo** [rust-lang/regex#949]
### What version of regex are you using?

1.7.1

### Describe the bug at a high level.

Program index out of boud for vector, which causing a panic.

### What are the steps to reproduce the behavior?

Using auto-generated fuzz target can reproduce the behavior. it was uploaded to the issue platform.
[index_out_of_bound.zip](https://github.com/rust-lang/regex/files/10526545/index_out_of_bound.zip)

Similar problems were found in the fuzzy test:

- regex/src/re_unicode.rs:58:10
- regex/src/exec.rs:461:22
- regex/src/exec.rs:784:14
- regex/src/re_unicode.rs:58:10

### What is the actual behavior?

Panic happens, the program crashes.

### What is the expected behavior?

Handle index out of bound without causing a panic

**Comment by BurntSushi** [comment]
This issue is invalid in the same way that #948 is invalid. The offset provided is itself incorrect.
