### ISSUE TITLE
Program unexpected panic when index is not a char boundary

### ISSUE THREAD

**Issue by bhao-Soo** [rust-lang/regex#951]
### What version of regex are you using?

1.7.1

### Describe the bug at a high level.

Program index of slice is not a char boundary, which causing a panic.

### What are the steps to reproduce the behavior?

Using auto-generated fuzz target can reproduce the behavior. it was uploaded to the issue platform.
[byte_not_char.zip](https://github.com/rust-lang/regex/files/10526580/byte_not_char.zip)

Similar problems were found in the fuzzy test:

- regex/src/re_set.rs:448:1
- regex/src/dfa.rs:1415:45

### What is the actual behavior?

Panic happens, the program crashes.

### What is the expected behavior?

assert the index of the slice is char boundary without causing a panic

**Comment by BurntSushi** [comment]
Adding some `dbg!` statements to show the actual parameters reveals this:

```
$ cargo run crash_input
   Compiling byte_not_char v0.1.0 (/home/andrew/tmp/issues/regex/i951/byte_not_char)
    Finished dev [unoptimized + debuginfo] target(s) in 0.31s
     Running `target/debug/byte_not_char crash_input`
data = [0, 0, 0, 0, 0, 0, 0, 1, 0, 63, 200, 191, 101]
data len = 13
[main.rs:100] _param0 = "\0?"
[main.rs:100] _param1 = "ȿe"
[main.rs:100] _param2 = 1
thread 'main' panicked at 'byte index 1 is not a char boundary; it is inside 'ȿ' (bytes 0..2) of `ȿe`', /home/andrew/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.7.1/src/re_unicode.rs:58:10
```

So here the caller is again providing an invalid offset. The blame for the panic comes from the caller, not the regex engine.
