### ISSUE TITLE
Bad docs recommending `regex = "1"` in `Cargo.toml`

### ISSUE THREAD

**Issue by Enyium** [rust-lang/regex#952]
https://docs.rs/regex/latest/regex/ reads:

> This crate is [on crates.io](https://crates.io/crates/regex) and can be used by adding `regex` to your dependencies in your project’s `Cargo.toml`.
> 
> ```
> [dependencies]
> regex = "1"
> ```

See the following post why this is bad: https://users.rust-lang.org/t/psa-please-specify-precise-dependency-versions-in-cargo-toml/71277.

**Comment by BurntSushi** [comment]
Yes, I'm well aware. But it's a maintenance hazard to put the latest version there. I would rather have nothing at all.

Once `cargo add` has been around for a bit, we can include that.
