### ISSUE TITLE
Partition string into matches and non-matches

### ISSUE THREAD

**Issue by vwkd** [rust-lang/regex#953]
#### Describe your feature request

It would be great if there was a `partition` method that returned an iterator over non-matches and an iterator over matches of a regex.

My use case is to partition a string into two disjoint groups knowing only the regex for one group. For example, this method would allow to partition the string `"123abcdef456ghj789"` into the partitions `["abcdef", "ghj"]` and `["123", "456", "789"]` using a separator regex `\d+`.

Currently, one can can use `split` for the non-matches and `find_iter` for the matches. This doesn't express the disjoint groups as they need to be assembled separately.

**Comment by BurntSushi** [comment]
I don't think this is a good fit for this crate at this time. I think the use case is a bit too niche _and_ the API design space is quite large. For example, you suggested here returning two iterators, but that isn't particularly optimal and isn't the most flexible. I think a better approach would be to return partitions, where each partition is labeled as non-match and match. Like this:

```rust
use regex::Regex;

#[derive(Debug)]
enum Partition<'t> {
    Match(&'t str),
    NonMatch(&'t str)
}

#[derive(Debug)]
struct PartitionIter<'r, 't> {
    it: regex::Matches<'r, 't>,
    last_match_end: usize,
    text: &'t str,
    next_match: Option<&'t str>,
}

impl<'r, 't> PartitionIter<'r, 't> {
    fn new(re: &'r Regex, text: &'t str) -> PartitionIter<'r, 't> {
        PartitionIter { it: re.find_iter(text), last_match_end: 0, text, next_match: None }
    }
}

impl<'r, 't> Iterator for PartitionIter<'r, 't> {
    type Item = Partition<'t>;
    
    fn next(&mut self) -> Option<Partition<'t>> {
        if let Some(next_match) = self.next_match.take() {
            return Some(Partition::Match(next_match));
        }
        let m = self.it.next()?;
        if m.start() > self.last_match_end {
            let non_match = &self.text[self.last_match_end..m.start()];
            self.last_match_end = m.end();
            self.next_match = Some(m.as_str());
            Some(Partition::NonMatch(non_match))
        } else {
            self.last_match_end = m.end();
            Some(Partition::Match(m.as_str()))
        }
    }
}

fn main() {
    let re = Regex::new(r"\d+").unwrap();
    let text = "123abcdef456ghj789";
    for part in PartitionIter::new(&re, text) {
        dbg!(part);
    }
}
```

Playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=faabeeca32a571dd595c12b59142f67a
