### ISSUE TITLE
Not compiled...

### ISSUE THREAD

**Issue by egorovd** [rust-lang/regex#97]
Hello.

I'm trying to use it in your project, but does not compile:

http://joxi.ru/Dr8WDGQt1x8ZA6

**Comment by BurntSushi** [comment]
It is hard to debug problems without essential details. What version of `rustc` are you using? How are you building your project? If it's with Cargo, what does your `Cargo.toml` look like?

My guess is that one of two things is going on assuming you're using Rust stable:

1. You're using the `regex_macros` crate, which is a compiler plugin and does [not work on Rust stable](http://doc.rust-lang.org/regex/regex/index.html#the-regex!-macro).
2. You're explicitly enabling the `pattern` feature, which requires using an unstable feature and therefore also [does not work on Rust stable](http://doc.rust-lang.org/regex/regex/enum.Regex.html#using-the-std::str::strext-methods-with-regex).

If you're on Rust 1.0 stable, [then all you need to add to your `Cargo.toml` is](https://github.com/rust-lang/regex#usage):

```toml
[dependencies]
regex = "0.1"
```

**Comment by egorovd** [comment]
Yes, I use Rust 1.0 stable...

Thank you. )

**Comment by alexcrichton** [comment]
I believe @BurntSushi's diagnosis is the culprit, and it sounds like you got this resolved, so closing.
