### ISSUE TITLE
Define `\pN One-letter name Unicode character class` with reference to unicode spec.

### ISSUE THREAD

**Issue by nathan-at-least** [rust-lang/regex#975]
#### What version of regex are you using?

1.7.3

#### Describe the bug at a high level.

The crate docs under [Matching one character](https://docs.rs/regex/1.7.3/regex/index.html#matching-one-character) for syntax defines:

```
\pN           One-letter name Unicode character class
```

However, I cannot find a definition for "name Unicode character class" anywhere in the documentation, or through web searches.

Lower in [Unicode features](https://docs.rs/regex/1.7.3/regex/index.html#unicode-features), certain features link to Unicode specifications, which is helpful, but from these I still cannot determine what "name character class" is. For example the `unicode-gencat` feature enables category-specification in patterns which correspond to this link [Unicode general categories](https://www.unicode.org/reports/tr44/tr44-24.html#General_Category_Values) which does not have a "name" category.

#### What are the steps to reproduce the behavior?

Read the documentation and try to define what "name Unicode character class" is.

#### What is the actual behavior?

The specific definition is not found.

#### What is the expected behavior?

A definition would be provided, such as:

> The name Unicode character class is specified in `<link>`

-or if it's an equivalent to another pattern, that could also be provided. For example, my (unverified) guess is that the name category might be equivalent to the Unicode `Letter` category:

> The `\Pn` pattern is equivalent to `\P{Letter}`

**Comment by BurntSushi** [comment]
The crate docs link to [UNICODE.md](https://github.com/rust-lang/regex/blob/master/UNICODE.md#rl12-properties) which I believe answers your question here.

Or are you specifically asking for a link to all the possible single level property values? Because if so, I don't think such a link exists. That's contained inside the Unicode Character Database. With that said, at this specific moment in time, you can see the list of categories and their abbreviations. Abbreviations with a single letter can be written in `\pX` syntax:

https://github.com/rust-lang/regex/blob/9582040009820380a16819ca0d1ae262c7d454b0/regex-syntax/src/unicode_tables/property_values.rs#L71-L154

**Comment by BurntSushi** [comment]
> which correspond to this link [Unicode general categories](https://www.unicode.org/reports/tr44/tr44-24.html#General_Category_Values) which does not have a "name" category.

This actually looks like a good link to me. It lists out all the general categories and even clearly shows which ones have one-letter abbreviations. I'm not understanding what has confused you here?

**Comment by nathan-at-least** [comment]
I'm still confused what this means:

> \pN One-letter name Unicode character class

Does this mean a pattern can literally include `\pN` to match a "name Unicode character class"?

Based on your comments, I'm wondering if instead it means patterns can contain specifiers like `\pc' to mean the `Other` class, or `\pn` to mean the `Number` class, etc… Is that the case? That makes sense, but I didn't realize `N` was a syntactic variable! I'm not sure how to clarify in that case.

**Comment by BurntSushi** [comment]
I still don't understand your confusion. `\pL` is precisely equivalent to `\p{Letter}`. It is a short-hand. There's nothing else to it. The set of `\pN` things that exist correspond to the things that have a single letter abbreviation, as defined by Unicode.

**Comment by Erutuon** [comment]
It sounds like there's a problem with parsing "One-letter name Unicode character class", a long series of noun phrases where the relationships aren't made clear by function words. It should be parsed as [one-letter name] [Unicode character class], but it sounds like @nathan-at-least is parsing it as [one-letter] [name [Unicode character class]]. It might be easier to understand if it were rephrased as "Unicode character class identified by a one-letter name" or something.

**Comment by BurntSushi** [comment]
Ah I see okay, I have a fix incoming for this using your wording @Erutuon. Thanks!

**Comment by nathan-at-least** [comment]
Thanks! The clarification looks like it would be less confusing to past-me. Kind of embarrassing after I understood the semantics, but I guess that's the nature of docs.

**Comment by BurntSushi** [comment]
@nathan-at-least No worries! It's great feedback. The docs are better for it. :-)
