### ISSUE TITLE
mention the issue of fallibility in replacements in the API docs

### ISSUE THREAD

**Issue by obsgolem** [rust-lang/regex#976]
Currently the `Replacer` trait returns a string. If you have complicated replacement logic, there is a decent chance that you want to be able to return a `Result` or an `Option` instead, with short circuiting behavior. The API would basically be to add `try` variants of `replace_all` and `replacen` and a new `FallibleReplacer` trait with an associated `Error` type.

**Comment by BurntSushi** [comment]
I think in cases like this, it would be best to just write your own replacement routine. `replace_all` is not a particularly complicated routine IMO, and I'd really rather folks do that at this point than bloating the API.

This has been discussed somewhat before in #648, and note that I wrote a fallible replacement routine in 10 not-too-complex lines.
