### ISSUE TITLE
New "pattern can match invalid UTF-8" error in 1.8.0

### ISSUE THREAD

**Issue by jplatte** [rust-lang/regex#989]
#### What version of regex are you using?

1.8.1

#### Describe the bug at a high level.

In regex <1.8.0, it was possible to create a regex containing `\W` inside of a `(?-u:)` group. This no longer works and makes regex construction fail instead. Looks like we should have been using `regex::bytes::Regex` the whole time, but it hasn't been a problem so far and we were only searching within `str`s anyways.

#### What are the steps to reproduce the behavior?

```toml
[package]
name = "regex-bug"
version = "0.0.1"
edition = "2021"

[dependencies]
regex = "1.8"
```

```rust
use regex::Regex;

fn main() {
    Regex::new(r"(?-u:\W)").unwrap();
}
```

#### What is the actual behavior?

Crashes.

#### What is the expected behavior?

Doesn't crash. (not because that's more sensible, but because it has been possible for a very long time and people might be relying on it accidentally, like we did in [Ruma](https://github.com/ruma/ruma))

**Comment by BurntSushi** [comment]
Thanks for the report. This change was an explicit bug fix. See #895. It's mentioned in the CHANGELOG.

The previous behavior was incorrect, and it could result in runtime panics due to match spans that split a codepoint boundary. So it never really worked.
