### ISSUE TITLE
Debian 11 (stable) has rustc 1.48.0; new version of regex-syntax does not compile anymore due to Cargo incompatibility

### ISSUE THREAD

**Issue by shabiel** [rust-lang/regex#990]
#### What version of regex are you using?
regex-syntax-0.7.1

#### Describe the bug at a high level.
```
 Downloading crates ...
  Downloaded regex-syntax v0.7.1
error: failed to parse manifest at `/home/xxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-syntax-0.7.1/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
```

#### Give a brief description of the actual problem you're observing:

Debian 11 (stable) has rustc 1.48.0; new version of regex-syntax does not compile anymore due to Cargo incompatibility.

I know little of rust, but I am maintaining a pipeline where this problem showed up. 

This is our project: https://gitlab.com/YottaDB/Lang/YDBRust

As far as I can tell, our project uses `bindgen` v0.59.2, which pulled in the latest released version of `regex`, which pulled in `regex-syntax`, which caused this problem. I can't tell if the problem is in the `bindgen` code, or this repo; but I am guessing this repo.

Please let me know if the expectation of the Rust Community is that OS-provided toolchains are not considered usable.

This problem started happening 3 days ago.

#### What is the actual behavior?

n/a. Compilation issue.

#### What is the expected behavior?

n/a. Compilation issue.

**Comment by BurntSushi** [comment]
The Minimum Supported Rust Version (MSRV) was explicitly updated to Rust 1.60. This is noted in the README and the CHANGELOG for `regex 1.8`.

> Please let me know if the expectation of the Rust Community is that OS-provided toolchains are not considered usable.

Of course they're useable. The Rust toolchain I get from Archlinux is quite useable, even with the latest stable release of Rust.

What you might run into problems with are OS provided toolchains that haven't been updated in literal _years_, such as the one you're using. If you want to use a toolchain that old, then you should be totally fine using versions of crates release around that time as well.

Rust 1.60 was released over 1 year ago.
